### ISSUE TITLE
10m_admin_0_boundary_lines_land - Wrong border near the Mont Blanc between France and Italy

### ISSUE THREAD

**Issue by dgddgd** [nvkelso/natural-earth-vector#100]
I'm using this file to show the boundary lines but it seems like there's a problem around the Mont Blanc. It should be in France and not in Italy.

![mont_blanc](https://f.cloud.github.com/assets/5493053/1190060/2f5b7232-242c-11e3-8157-acfc7032b0e7.jpg)

**Comment by nvkelso** [comment]
I've noted the mountain as both French and Italian, but not moved it's location. You'r over-zooming the map data far past it's intended 1:10,000,000 scale.

There's a little border dispute here now that is beyond the scope of your issue.

- http://www.politico.eu/article/peak-of-discord-mont-blanc-europe-border-france-italy/
