### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by fraxen** [nvkelso/natural-earth-vector#113]
Hi,

I am a bit confused about the versions and the master for NE - I was looking at: [http://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-populated-places/](http://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-populated-places/) and I can see that this dataset is at _3.0.0_ - but when I download it the .VERSION file says 2.0.0 and the .README the same. And I can see that this repo hasn't gotten any commits lately... There is no changelog for this new major version...

**Comment by nvkelso** [comment]
The is an artifact of exporting the project VERSION with the theme, even if the theme hasn't updated this release. An existential issue, closing.
