### ISSUE TITLE
Seattle-Tacoma Int'l incorrectly named as "Tacoma Int'l"

### ISSUE THREAD

**Issue by almccon** [nvkelso/natural-earth-vector#115]
This is wrong in the 10m data. I haven't checked the 50m or 110m.

**Comment by elliotap** [comment]
Verified - https://en.wikipedia.org/wiki/Seattle%E2%80%93Tacoma_International_Airport

Compare to Google:
<img width="1680" alt="Screen Shot 2021-03-10 at 1 30 01 PM" src="https://user-images.githubusercontent.com/64806657/110700468-d601e480-81a4-11eb-8a25-581aca2d9084.png">
Apple:
<img width="1398" alt="Screen Shot 2021-03-10 at 1 30 23 PM" src="https://user-images.githubusercontent.com/64806657/110700483-db5f2f00-81a4-11eb-85f8-9d4d13b4cf51.png">
OpenStreetMap:
<img width="1680" alt="Screen Shot 2021-03-10 at 1 29 44 PM" src="https://user-images.githubusercontent.com/64806657/110700500-df8b4c80-81a4-11eb-8156-b5f8d9ba2ac5.png">

Proposed changes:
change name from Tacoma Int'l to Seattle-Tacoma Int'l

**Comment by nvkelso** [comment]
Works for me. 

Let's look at PR a bit though... I need to recall how the airports are made... are they a one time or dynamic selection of Mile High Club features?

**Comment by elliotap** [comment]
@nvkelso I looked through the makefile and wanted to confirm that the necessary function is ``make 50m_cultural/ne_50m_airports.shp`` from lines 642-644

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/509.
