### ISSUE TITLE
Attributes titles upper or lower case to standardize (name v. NAME)

### ISSUE THREAD

**Issue by hugolpz** [nvkelso/natural-earth-vector#119]
- _ne_10m_admin_1_states_provinces.shp_ , attribute titles are in lower case (i.e: `name`).
- _ne_10m_admin_0_countries.shp_,  attribute titles are in lower case (i.e: `name`).
- _ne_10m_admin_0_disputed_areas.shp_, attribute titles are in lower case (i.e: `name`) as well.
- _ne_10m_populated_places.shp_, attribute titles are in upper case (i.e: `NAME`).

This change in admin_1 makes some later scripts (`topojson`) to fails to look at them as the same field (name=NAME). Also : 
- what is the guideline for attributes titles: upper or lower case ?
- could someone align all files via some regex? (fix welcome)

**Comment by nvkelso** [comment]
+1

**Comment by nvkelso** [comment]
Column names capitalization in DBF is not significant. Suggest wrapping the column names in `lower()` or some equivalent approach when you parse them if your lib is having problems.
