### ISSUE TITLE
Column meanings

### ISSUE THREAD

**Issue by jmagnusson** [nvkelso/natural-earth-vector#121]
Can't find a reference of what each column in the datasets mean and which ones are unique. Is this data available somewhere?

**Comment by jalbertbowden** [comment]
hey, any update on this?  
i've pieced together a list of links with some info, and i think labeled a few correctly for 110m cultural boundaries, but a) there's alot of gaps and b) i'm not 100% on the ones i have.  
if you can fill in the gaps, or add to the list, that would be sweet. 
trying to format it the data, but its hard without the definitions  
https://gist.github.com/jalbertbowden/1a94aa339682eabfdc6a

**Comment by nvkelso** [comment]
This is a dup of #153.
