### ISSUE TITLE
Change "Holy Sea" to "Holy See" for Vatican

### ISSUE THREAD

**Issue by almccon** [nvkelso/natural-earth-vector#122]
This is in the `name_alt` column of ne_10m_admin_0_countries_lakes and ne_50m_admin_0_countries_lakes. I haven't checked other files to see if the misspelling is there, too.

**Comment by nvkelso** [comment]
Partial work in Excel file via 3aa1a4eaad91459b083f23167db087f8b258234f, needs to be propagated to all related admin0 themes.

**Comment by nvkelso** [comment]
Remainder tracked via https://github.com/nvkelso/natural-earth-vector/issues/207.
