### ISSUE TITLE
Makefile does not create directories

### ISSUE THREAD

**Issue by ajmas** [nvkelso/natural-earth-vector#132]
Running the Makefile on MacOS X I get the following failure:

    % make
    cp VERSION  10m_cultural/ne_10m_admin_0_boundary_lines_disputed_areas.VERSION.txt
    curl http://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-breakaway-disputed-areas/ >  10m_cultural/ne_10m_admin_0_boundary_lines_disputed_areas.README.html
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 23654    0 23654    0     0  19033      0 --:--:--  0:00:01 --:--:-- 19045
    zip -j -r zips/10m_cultural/ne_10m_admin_0_boundary_lines_disputed_areas.zip  10m_cultural/ne_10m_admin_0_boundary_lines_disputed_areas.*
    zip I/O error: No such file or directory
    zip error: Could not create output file (zips/10m_cultural/ne_10m_admin_0_boundary_lines_disputed_areas.zip)
    make: *** [zips/10m_cultural/ne_10m_admin_0_boundary_lines_disputed_areas.zip] Error 15

Investigation shows that the zips/10m_cultural directory does not exist. The Makefile should be updated to create the directories.

**Comment by ajmas** [comment]
Looks like a 'make clean' needs to be run first, to have the directories created. Wondering with mkdir elements should be a normal step of a build? In the meantime will simply update the docs.

**Comment by nvkelso** [comment]
NTBF
