### ISSUE TITLE
Kosovo and ISO_A2

### ISSUE THREAD

**Issue by ajmas** [nvkelso/natural-earth-vector#134]
Given the European union is using XK for Kosovo, should the shapefiles be using that value and if so in what field? The link below includes a discussion on the subject:

https://geonames.wordpress.com/2010/03/08/xk-country-code-for-kosovo/

**Comment by nvkelso** [comment]
Sure. But all the X extensions are optional and debatable codes (they
aren't standardized). So this wouldn't really be an ISO code (yet). If
Kosovo was recognized by ISO, it likely wouldn't receive an XK code in the
final standard.

**Comment by nvkelso** [comment]
PR https://github.com/nvkelso/natural-earth-vector/pull/199 has changes for admin-1 ISO-3166-2 and ISO-3166-1 and codes.

**Comment by nvkelso** [comment]
Admin-0 work was done in 87086e21c0c96acd9c2405a70ff7dbe0423e619a.

**Comment by nvkelso** [comment]
More via 3aa1a4eaad91459b083f23167db087f8b258234f and 4f738751e1d60fe5025054f7a82df9237d36f963.
