### ISSUE TITLE
Map for ITU Regions

### ISSUE THREAD

**Issue by ajmas** [nvkelso/natural-earth-vector#135]
Interested in an ITU region map. I have started by trying the ne_10m_admin_0_countries source, but given that certain territories , such as France cover both South America and Europe, it makes it hard to use without modification. I had considered an extra field for this, but the multi-region aspect makes it hard.

Open to suggestions that would not need another file.

Information on ITU regions:

http://en.wikipedia.org/wiki/International_Telecommunication_Union_region

**Comment by ajmas** [comment]
Probably best covered by "map units", though would still be interested in "ITU_REGION" property in the "map units" files, if this is seen as okay.

**Comment by nvkelso** [comment]
The way to do this is to use the "map subunits" as a building block. This
file is attributes (and built from with dissolves) the attributes in

https://github.com/nvkelso/natural-earth-vector/blob/master/housekeeping/ne_admin_0_details.xls

That file should be edited using OpenOffice to preserver unicode UTF8
encodings. If you edit the subunit DBF file, it can be integrated with the
Excel file without too much hassle.
