### ISSUE TITLE
Pribonka mislabelled Peribonka (Window1252 > UTF8 encoding funk)

### ISSUE THREAD

**Issue by taejo** [nvkelso/natural-earth-vector#140]
The river labelled Pribonka north of Québec city should be Peribonka, it seems: https://en.wikipedia.org/wiki/Peribonka_River

**Comment by almccon** [comment]
Probably an encoding issue, since in French the name has an accent: Péribonka. https://fr.wikipedia.org/wiki/Rivi%C3%A8re_P%C3%A9ribonka

I suspect the é is getting dropped somewhere along the way, resulting in Pribonka.

**Comment by taejo** [comment]
The river flowing through Tbilisi into the Caspian Sea is labelled Kr, but according to https://en.wikipedia.org/wiki/Kura_River it is called Kura, Kür, Kur or Mt'k'vari. I'm not sure if this is the same issue (ü being dropped in Kür) or a separate one.

**Comment by nvkelso** [comment]
My guess is dropping the ü in error in the last version. Thanks for finding these!

_n

**Comment by taejo** [comment]
The same issue affects ne_10m_lakes: Lago Poopó is labelled "Lago Poop". In fact, this lake has dried up. What's the procedure for updating the data in this case?

**Comment by nvkelso** [comment]
Lago Poopó is already classified as an Alkaline Lake, should it be a Playa instead (move themes), or be deleted? [Wikipedia](https://en.wikipedia.org/wiki/Lake_Poopó) says it's dried up completely in 2015. Suggest wait another year and see if it comes back with the big rains this year.

**Comment by nvkelso** [comment]
Looks like some of this was Windows-1252 > UTF8 encoding conversion funk... but others (including most the example here) were an earlier something > Windows-1252 encoding error that has been lost to time. I've fixed the specific examples, and a few more. But likely more remain.

**Comment by nvkelso** [comment]
Related: https://github.com/nvkelso/natural-earth-vector/issues/155

**Comment by nvkelso** [comment]
Related: https://github.com/nvkelso/natural-earth-vector/issues/139

**Comment by nvkelso** [comment]
(These 3 spelling fixes are only in 10m, not in 50m series.)
