### ISSUE TITLE
Roads, Rivers and Lakes are not queryable for AUS

### ISSUE THREAD

**Issue by Spaxe** [nvkelso/natural-earth-vector#142]
When I tried to select a part of the data (using `ogr2ogr`), many of the data points outside of USA and Canada have `null` for its `admin` or related attribute. 

This makes filtering really difficult. Is there an easy way to approach this, and hopefully one day update the actual dataset to better reflect their locations?

**Comment by nvkelso** [comment]
You'll need to use OGR's functionality to clip source to the country
polygon for Australia. While most the cultural themes include a country
code, the physical themes do not (this is problematic for rivers, say, that
are shared between N number of countries).

**Comment by nvkelso** [comment]
This won't be fixed.
