### ISSUE TITLE
Incorrect locations in ne_10m_admin_1_label_points

### ISSUE THREAD

**Issue by almccon** [nvkelso/natural-earth-vector#145]
@clhenrick and I are trying to use the admin 1 label points. There are points for every polygon, it seems, so we are using `adm0_sr` to find the one preferred label point for each US state. Is this the correct field to use? It looks like each state has only one polygon where `adm0_sr=1`. 

However, there are a couple of exceptions to this rule. Kentucky, Rhode Island, and Maryland each have two points where `adm0_sr=1`, and North Carolina has three.

Also, the point locations for a few states are incorrect. Both Indiana and Vermont have their label points right at the edge of the state, not in the middle. Also, the label point for Florida is questionable, placed near Tallahassee rather than in the middle of the state.

I haven't checked in other countries, but a glance at Canada shows some issues up there too. 

Here's a quick QGIS map showing all of the records in `ne_10m_admin_1_label_points` where `adm0_sr=1`

![screen shot 2015-09-07 at 7 sep 8 26 07](https://cloud.githubusercontent.com/assets/1212178/9725827/d665a9e4-559e-11e5-9d9f-c182a496faf1.png)

**Comment by nvkelso** [comment]
This file is for creating polygons out of line inputs and "labeling" the resulting so it can receive the correct attributes (spatial join, then attribute join). This is an archaic ArcInfo term.

Instead use mapshaper.org to generate label points suitable for cartographic display. Or use Who's On First, which bakes the result into the feature attributes.

_n

**Comment by almccon** [comment]
Gotcha. Thanks!

**Comment by clhenrick** [comment]
just an FYI this PostGIS query seems to have favorable results for achieving centroids for labels:

```sql
DROP TABLE IF EXISTS ne_10m_admin_1_states_provinces_labels;

CREATE TABLE ne_10m_admin_1_states_provinces_labels AS (
  WITH geoms AS (
    SELECT name, admin, scalerank, (ST_Dump(geometry)).geom AS geometry 
    FROM ne_10m_admin_1_states_provinces
  )
  SELECT DISTINCT ON (name) name, admin, scalerank, ST_PointOnSurface(geometry) AS geometry
  FROM geoms
  ORDER BY name ASC, ST_Area(geometry) DESC
);
```
