### ISSUE TITLE
Tolopogy relations in countries

### ISSUE THREAD

**Issue by ppKrauss** [nvkelso/natural-earth-vector#148]
Can I use a shapefile of natural-earth-vector project to get topology? The main operation is a neighbor list, as below

``` sql
    -- Get neighbor_list column for country-codes.csv
    SELECT 
        m.country_id, 
        array_agg(scan.country_id) as neighbor_list 
    FROM mundi AS m INNER JOIN mundi AS scan 
         ON (m.geom && scan.geom) and ST_Touches(m.geom, scan.geom)
    WHERE m.country_id>scan.country_id;
    -- PS: country_id can be internal or ISO3166-1-numeric code.
```

What sacale (or best shapefile) to do that operations?  I need only the ~250 countries defined by ISO3166-1 codes (no disputed territory or another kind of division).

**Comment by nvkelso** [comment]
Use the 1:10m countries file for this (the one that still has lakes as part
of the country polygons). You should get good results, feel free to share
them here!

**Comment by ppKrauss** [comment]
Thanks a lot!  So, to download 247  polygons of countries in the world is http://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-countries/ (is it? not units?).

-----

PS: [error](http://naciscdn.org/naturalearth/10m/cultural/countryList.zip) link in "Download admin-0 Excel file" at http://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-details/

**Comment by ppKrauss** [comment]
Hum.. Another problem: **topology not perfect** at *natural-earth-vector*  [ne_10m_admin_0_countries.zip](http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip) polygons, only few  with [ST_Touches()](http://postgis.org/docs/ST_Touches.html) espected behaviour ... producing 

country|neighbor_list
------------ | -------------
AZ|AM
BF|BJ
BR|AR
CD|AO
CG|CM,CF
...|...

so, a lack of other neighbors (ex. *BR* need *{AR,BO, PE, UY, etc.}*)  [see illustration](http://www.zonu.com/images/0X0/2009-11-06-10858/World-political-ISO-map.png).... 

... I will replace `scan.geom` by `ST_BUFFER(scan.geom,1)`, or compare with `ST_AREA(ST_INTERSECTION())` 
perhaps works....
