### ISSUE TITLE
ne_10m_admin_1_states_provinces_shp - Hormozgan

### ISSUE THREAD

**Issue by murraybiscuit** [nvkelso/natural-earth-vector#149]
ARE-3228 (Hormozgan) is listed as a province under UAE but it's a province of Iran. Is this correct?
OMN-3229 (Fujayrah) is listed under Oman, but this is normally an Emirate of UAE (see ARE-341/2)
This filename also has _shp.shp at the end, which doesn't seem to follow naming conventions...

**Comment by nvkelso** [comment]
These were corrected in the 3.x series. I suspect you were referencing a 2.x series file (especially from the `_shp.shp` comment).
