### ISSUE TITLE
Mt. McKinley -> Denali

### ISSUE THREAD

**Issue by almccon** [nvkelso/natural-earth-vector#154]
`ne_*m_geography_regions_elevation_points` needs to switch from Mt. McKinley to Denali. 

`name_alt` is empty, so we could put Mt. McKinley there, although it's probably not necessary.

<img width="350" alt="screen shot 2015-11-03 at 11 07 00 am" src="https://cloud.githubusercontent.com/assets/1212178/10918669/c88ef6fa-821b-11e5-8570-3c2675cc04bb.png">

**Comment by nvkelso** [comment]
Good catch.
