### ISSUE TITLE
Internationalization?

### ISSUE THREAD

**Issue by scottseeker** [nvkelso/natural-earth-vector#156]
Are there any plans to internationalize the metadata associated with the data?  

If not, are you familiar with any site which provides data with metadata in multiple languages (or tools for generating it)?  

Thank you.

**Comment by nvkelso** [comment]
For most the features internationalization work is happening now in https://github.com/whosonfirst/whosonfirst-data/. Once it's cleaned up there, including adding concordance to Natural Earth records, I'll back port a subset of the internationalized names to Natural Earth (8-12 common languages), but the entire set won't be (all 1000s).

**Comment by scottseeker** [comment]
Thank you for the reply!

**Comment by nvkelso** [comment]
Dup of #13
