### ISSUE TITLE
Sri Lanka coastline is at wrong scalerank?

### ISSUE THREAD

**Issue by teahan36** [nvkelso/natural-earth-vector#157]
Just downloaded v3.0.0 of the ne_10m_coastline shapefile and Sri Lanka appears to be classified at scalerank 6 instead of scalerank 0 (or at most 1) as I'd be expecting.  Is this fixed in one the later versions?  I doesn't appear to get a mention in the change log.

**Comment by nvkelso** [comment]
Agree that's an error. I'll have a look.

**Comment by nvkelso** [comment]
Subtask of #202.

**Comment by nvkelso** [comment]
The new `min_zoom` will be **1.0** (scalerank will be similarly low).
