### ISSUE TITLE
Intersection Overshoot: Yukon & Porcupine rivers

### ISSUE THREAD

**Issue by pinakographos** [nvkelso/natural-earth-vector#158]
10m rivers: the intersection of the Yukon and Porcupine rivers in Alaska has an overshoot.
![overshoot](https://cloud.githubusercontent.com/assets/5448396/11188821/7358af46-8c52-11e5-9ac2-bfe774bbe4e4.png)

**Comment by nvkelso** [comment]
Ahem, this one is 1:20,000 @pinakographos.

**Comment by nvkelso** [comment]
Fixed in 04f866e711c2212f1ca8dc02a05e8c1a7eecfbff.
