### ISSUE TITLE
Klamath River Gap

### ISSUE THREAD

**Issue by pinakographos** [nvkelso/natural-earth-vector#159]
Another topology issue in the 10m rivers: there's a gap in the middle of the Klamath River, at about -121.81, 42,251
![klamathgap](https://cloud.githubusercontent.com/assets/5448396/11189684/f3c28342-8c56-11e5-822a-bfeb5077fdf0.png)

**Comment by nvkelso** [comment]
I will fix for you @pinakographos, but seriously 1:10,000,000 scale data shouldn't be over-zoomed to 1:25,000 (the scale of your screenshot).

**Comment by nvkelso** [comment]
Fixed in 04f866e711c2212f1ca8dc02a05e8c1a7eecfbff.
