### ISSUE TITLE
Norfolk Island, Australia feature is actually Lord Howe Island

### ISSUE THREAD

**Issue by almccon** [nvkelso/natural-earth-vector#161]
https://en.wikipedia.org/wiki/Norfolk_Island
https://en.wikipedia.org/wiki/Lord_Howe_Island

See issue report https://github.com/CartoDB/CartoDB-basemaps/issues/53

Looks like it's an error in the `ne_10m_admin_1_states_provinces_shp` file. Here are the name labels in that file, rendered in QGIS:

<img width="783" alt="screen shot 2016-03-02 at 2 mar 5 26 23" src="https://cloud.githubusercontent.com/assets/1212178/13461770/6dc9023a-e038-11e5-800a-b6af6c86505e.png">

The feature at the left labeled "Norfolk Island" is actually "Lord Howe Island". The feature at the right labeled "NFK-00 (Norfolk Island aggregation" is the true Norfolk Island.

**Comment by nvkelso** [comment]
This is correct in the Admin0 subunits.

**Comment by nvkelso** [comment]
Fixed via e2c3bf122de77e0e67abd1cf49803b3ca00d3acc, needs some more propagation to not lakes file.
