### ISSUE TITLE
Bad records in ne_10m_time_zones.shp?

### ISSUE THREAD

**Issue by xangregg** [nvkelso/natural-earth-vector#164]
When I read ne_10m_time_zones.shp (2.0) with my own parser, it seems three of the records (6, 23 and 85) take up more space than their record lengths indicate. 

For example, record 6 begins at offset 13180 (decimal):

13180:  00000006 00000C70 05000000 ...

The next record should begin at 13180 + 8 + 2*0xC70 = 19556. Instead it begins at

19652:  00000007 00002120 05000000 ...

If I skip those extra 96 bytes (6 points?) I don't see anything bad. That appears to be what MapShaper does in this situation. See huntForNextShape() in [shp-reader.js](https://github.com/mbloch/mapshaper/blob/master/src/shapefile/shp-reader.js).

```
  // Very rarely, in-the-wild .shp files may contain junk bytes between
  // records; it may be possible to scan past the junk to find the next record.
  shape = huntForNextShape(recordOffs + 4, i);
```

QGIS also has no problem reading the file, but it apparently relies on the SHX file for the record positions instead of trusting the lengths in the SHP file.

So I need to update my parser to be more tolerant, but you might want to check you SHP file and fix it if you confirm the issue.

**Comment by humberry** [comment]
I have also issues with getting the right shapetype from ne_10m_time_zones.shp. Record number 7 shows me a value of 1845871296 instead of 5 (polygon).
And also ne_10m_railroads.shp shows me a wrong value at record 18480, I got 305419896 instead of 3 (polyline). Thanks for reading and maybe fixing it.

**Comment by nvkelso** [comment]
I suspect changes in 04413bd0b2fd6cd1dfb05b742f562b59188265b9 address this for you (basically re-saving the file from QGIS instead of ArcMap). Please re-open if that's no the case.
