### ISSUE TITLE
Incorrect ISO 3166-2 code for Southwest Finland

### ISSUE THREAD

**Issue by migurski** [nvkelso/natural-earth-vector#165]
[Southwest Finland](https://en.wikipedia.org/wiki/Southwest_Finland) is missing the `FI-19` ISO 3166-2 code.

<img width="848" alt="screen shot 2016-05-01 at 10 35 47 am" src="https://cloud.githubusercontent.com/assets/58730/14943255/87118f8a-0f88-11e6-999d-7d0d04d2a01b.png">

**Comment by nvkelso** [comment]
Fixed in PR https://github.com/nvkelso/natural-earth-vector/issues/199
