### ISSUE TITLE
Minnesota has the wrong FIPS code, should be 27 not 32

### ISSUE THREAD

**Issue by yaph** [nvkelso/natural-earth-vector#166]
In the ne_10m_admin_1_states_provinces_lakes.shp shapefile Minnesota has the FIPS code US32 assigned, which is the FIPS code of Nevada. Minnesota should be US27, see https://www.census.gov/geo/reference/ansi_statetables.html

The `code_local` attribute in the same file for Minnesota also has the value US32.

**Comment by nvkelso** [comment]
Same as http://www.naturalearthdata.com/corrections/admin/admin_ticket.php?track=MYJL36PN7T&Refresh=53380.
