### ISSUE TITLE
Kosovo ISO_N3

### ISSUE THREAD

**Issue by dmadeka** [nvkelso/natural-earth-vector#168]
How does one access Kosovo? It doesnt seem to have a supported 'ISO_n3'/'iso_a2'/'iso_n3' code

**Comment by nvkelso** [comment]
The natural earth adm_A3 code

**Comment by dmadeka** [comment]
Ahh okay its not 'XK' it's 'KOS', it would be nice to have an override to set the `iso_n3` code to the reserved one or to the country that a territory belongs to. But thanks so much!
