### ISSUE TITLE
ne_10m_geography_regions_elevation_points: Slide Mt. has wrong elevation

### ISSUE THREAD

**Issue by mojodna** [nvkelso/natural-earth-vector#169]
It's currently listed as 4200m. OSM (via GNIS) has it at 1266m.

**Comment by nvkelso** [comment]
We generally use http://www.peakbagger.com/peak.aspx?pid=7335 for this and they list:

```
Elevation range: 4180 - 4200 ft
    (20-foot closed contour)
NAVD88 Elevation: 4179 ft / 1274 m
    (Range 4179 - 4199 ft)
```

**Comment by nvkelso** [comment]
(Someone pasted feet into a meters field, that's never happened before ;)

**Comment by nvkelso** [comment]
https://geonames.usgs.gov/apex/f?p=138:3:0::NO:3:P3_FID,P3_TITLE:975759,Slide%20Mountain says:

Entry Date: | 01-Jan-2000
-- | --
*Elevation: | 4153/1266

**Comment by nvkelso** [comment]
Using `1274` meters via https://github.com/nvkelso/natural-earth-vector/commit/e98b9b62d11261bfa3cff6cdb06617d6fa86b364.
