### ISSUE TITLE
Russia and Ukraine changes

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/natural-earth-vector#177]
- [x] Crimea to Russa (disputed by Ukraine) **B89**
- [x] Breakaway changes in eastern Ukraine **B90**

**Comment by simgislab** [comment]
there are no changes worth mapping for point 2

**Comment by nvkelso** [comment]
There are a few commits for this but all have landed in master, closing.

**Comment by nvkelso** [comment]
Related to http://www.naturalearthdata.com/corrections/admin/admin_ticket.php?track=T5DPJ1EBD6&Refresh=53380.
