### ISSUE TITLE
Name fixes needed, mostly hydro

### ISSUE THREAD

**Issue by CaucasusandMercury** [nvkelso/natural-earth-vector#182]
**10 Lakes:**

- [x] `Lake Sevana` should be `Lake Sevan` [link](https://en.wikipedia.org/wiki/Lake_Sevan)
- [x] `Ysyk Köl` should be `Issyk-Kul`, with `Ysyk Köl` as `name alt` [link](https://en.wikipedia.org/wiki/Issyk-Kul)
- [x] `Kiyevskoye reservoir` ought to be `Kiev reservoir` [link](https://en.wikipedia.org/wiki/Kiev_Reservoir)

**10 rivers:**

- [x] `Selenge (Selenga)` is commonly called `Selenga` [link](https://en.wikipedia.org/wiki/Selenga_River)
- [x] `rivernum1002`, the name of this river is `Sheksna` [link](https://en.wikipedia.org/wiki/Sheksna_River)

**10 lakes europe:**

- [x] There are two lakes weirdly called `Sheksinskoe Reservoir river part 1` and `Sheksinskoe Reservoir river part 2`. These two lakes are the `Sheksna reservoir`, simply [link](https://en.wikipedia.org/wiki/Sheksna_Reservoir)
- [x] id `23983` is called `Belomorcanal`, that can't really be correct as Belomorcanal is a canal and not a lake. Rather, river `objectid 4895` found in 10 rivers europe should be named Belomorcanal, though only as far south as Lake Vygozero (found in the 10 lakes dataset) [link](http://photo.qip.ru/photo/uritsk/2785135/76888914.jpg) [link](https://en.wikipedia.org/wiki/White_Sea–Baltic_Canal) [link](http://www.planetadorog.ru/img/reports/723/belomorkanal_01.jpg)
- [x] And on the whole, `Belomorcanal` ought to be called `White Sea Canal` in English

**Lakes 110:**

- [x] Lake `Balqash Kli` with the `name_alt` `Lake Balkhash` should change places so `Lake Balkhash` is name and `Balqash Kli` is name_alt. This would make it consistent with the 50 and 10 datasets

**50 and 10 rivers:**

- [x] The `river Ob'` is sometimes spelled as `Ob`. Same goes for dissolve column sometimes `RiverOb'`, sometimes `RiverOb`
- [x] `Svernaya Dvina` should be `Severnaya Dvina` [link](http://www.thefreedictionary.com/Severnaya+Dvina) [link](https://en.wikipedia.org/wiki/Northern_Dvina_River)

**50 geography regions polygons:**

- [x] `KURIL ISANDS` should be spelled ISLANDS
- [x] `PENNSULA IBRICA` I suppose this should be `PENINSULA IBERICA`
- [x] `QIZILQUM DESERT` weird spelling it's usually called `KYZYLKUM` [link](https://en.wikipedia.org/wiki/Kyzylkum_Desert)

**And, quite significantly -**

**10 land 50 lakes:**

- [x] `Ozero` in Russian means `Lake` in English. There are many examples of lakes called `Seletskoe ozero`, `Loukhskoe ozero` etc. These ought to be called `Lake Seletskoe` and so on.
- [x] There are also many called ex `O. Nerpich'ye`, that ought to be `L. Nerpich'ye` then
- [x] There is also an example of this translation issue in 10 marine labels polys `Ozero Mogotoyevo`

**Comment by nvkelso** [comment]
Keep the corrections coming and I'll update the files, thank you!

**Comment by CaucasusandMercury** [comment]
Alright one more:

Rivers 10:

`Pivd. Buh` is Ukrainian - it should be `Southern Bug` [link](https://en.wikipedia.org/wiki/Southern_Bug).

**Comment by nvkelso** [comment]
Regarding:

> Ozero in 10 land 50 lakes (and marine areas)

I've added the English translations as name_alt, but kept the original for now.

- http://web.archive.org/web/20160806004756/http://www.naturalearthdata.com/about/map-update-committee/

>> For other languages, transliterated names of major features (mountain ranges, plateaus, deserts, etc.) received English place name descriptors. For example, Verkhoyansk Khrebet in Russia is labeled on the map as Verkhoyansk Range. Smaller physical features, such as mountains within ranges, have entirely local names.

**Comment by nvkelso** [comment]
> QIZILQUM DESERT weird spelling it's usually called KYZYLKUM link

Added as name_alt in 10m and 50m – we prefer the local spelling (no change to default name).

**Comment by nvkelso** [comment]
Everything should be resolved in PR https://github.com/nvkelso/natural-earth-vector/pull/199.

**Comment by nvkelso** [comment]
Related changes in 04f866e711c2212f1ca8dc02a05e8c1a7eecfbff.
