### ISSUE TITLE
Flo of the Po

### ISSUE THREAD

**Issue by dshorthouse** [nvkelso/natural-earth-vector#183]
Comment from a user of an app I develop that makes use of NaturalEarth: https://disqus.com/home/discussion/simplemappr/simplemappr/#comment-3046649655. That annotated image makes reference to the correct location of the Po river in Switzerland ne_10m_rivers_lake_centerlines and the naming of one river, incorrectly called Orco and should be called Dora Baltea.

**Comment by nvkelso** [comment]
- Renamed `Orco` to `Dora Baltea` (Italy)
- Renamed `Rhne` to `Rhône` (Switzerland and France)
- Fixing the Po is slightly more complicated and still **to-do**. 
    - The portion south of Turin is partially the Po and then splits with the northern route shown being the Po, and,
    - the existing southern route something more like `Varaita` with a worse scale_rank / min_zoom.

![](https://uploads.disquscdn.com/images/b9016c154f8045294af74026d48acc9df4e7d834a9e3c8836f39e6af9da30d3d.jpg?w=600&h=468)

**Comment by nvkelso** [comment]
Po is fine in the 1:50m theme (and not present in the 1:110m theme), but is wrong in 1:10m theme,

**Comment by nvkelso** [comment]
Fixed in 04f866e711c2212f1ca8dc02a05e8c1a7eecfbff.
