### ISSUE TITLE
Include cpg file with shapefiles

### ISSUE THREAD

**Issue by pnorman** [nvkelso/natural-earth-vector#186]
A cpg file can specify the encoding, and this is likely to help with encoding problems some people experience.

**Comment by nvkelso** [comment]
Good idea! I've started doing that with a few of the newer commits. That
should be extended to all SHPs.

**Comment by nvkelso** [comment]
Two commits b34e34e1715b2093cd3dbe7ccb572eecebadb280 and 3bc5cf8c97dceec379e180017dac080fab095a53 should address this.

Will be released in v4.0
