### ISSUE TITLE
Brazil cities

### ISSUE THREAD

**Issue by jvcunha** [nvkelso/natural-earth-vector#187]
Hi, I have a JSON file with the coordinates of the states of Brazil to use in HighMaps. I need one with the division of cities.
How do I do that?
Is there anyone or any company that has or does?
sorry this post in issues :(

Example Brazil states:
{"title":"Brazil","version":"1.1.2","type":"FeatureCollection","copyright":"Copyright (c) 2015 Highsoft AS, Based on data from Natural Earth","copyrightShort":"Natural Earth","copyrightUrl":"http://www.naturalearthdata.com","crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG:29101"}},"hc-transform":{"default":{"crs":"+proj=poly +lat_0=0 +lon_0=-54 +x_0=5000000 +y_0=10000000 +ellps=aust_SA +towgs84=-57,1,-41,0,0,0,0 +units=m +no_defs","scale":0.000161701268187,"jsonres":15.5,"jsonmarginX":-999,"jsonmarginY":9851.0,"xoffset":2791531.40873,"yoffset":10585904.489}},
"features":[{"type":"Feature","id":"BR.SP","properties":{"hc-group":"admin1","hc-middle-x":0.43,"hc-middle-y":0.34,"hc-key":"br-sp","hc-a2":"SP","labelrank":"2","hasc":"BR.SP","alt-name":null,"woe-id":"2344868","subregion":null,"fips":"BR32","postal-code":"SP","name":"São Paulo","country":"Brazil","type-en":"State","region":null,"longitude":"-48.5206","woe-name":"São Paulo","latitude":"-22.2267","woe-label":"Sao Paulo, BR, Brazil","type":"Estado"},"geometry":{"type":"MultiPolygon","coordinates":[[[[6776,1722],[6767,1687],[6733,1678],[6718,1696

**Comment by nvkelso** [comment]
I've never used HighMaps, and Natural Earth only has the largest cities in Brazil.

**Comment by jvcunha** [comment]
In this JSON file that I use, if I can get the coordinates of each state's cities, how do I implement it?
What is the value for you to do this job?
