### ISSUE TITLE
Confusion about name, name_long and formal_en

### ISSUE THREAD

**Issue by instantdelay** [nvkelso/natural-earth-vector#188]
What exactly is supposed to be the definition for each of these:
* name
* name_long
* formal_en

There are a few countries where name_long seems inconsistent since it is using the formal English name rather than a shorter common name.

North Korea and Laos have abbreviations in their name_long column so their name and name_long are the same.

sovereignt|name|name_long|formal_en
-------|-------|-------|--------
North Korea|Dem. Rep. Korea (North Korea?)|Dem. Rep. Korea (North Korea?)|Democratic People's Republic of Korea
Laos|Lao PDR (Laos?)|Lao PDR (Laos?)|Lao People's Democratic Republic
Federated States of Micronesia|Micronesia|Federated States of Micronesia (Micronesia?)|Federated States of Micronesia
South Korea|Korea (?)|Republic of Korea (South Korea?)|Republic of Korea
Russia|Russia|Russian Federation (Russia?)|Russian Federation

Should any of these be changed?

**Comment by nvkelso** [comment]
Updating the names to the following in 24dc83ffb26eafe8e79d3c9a62ff365a351fc62f:

- North Korea
- Laos
- South Korea

No change for Micronesia and Russia. A couple other minor things changed, too.
