### ISSUE TITLE
Encoding problem importing time zone data into SQL Server

### ISSUE THREAD

**Issue by jstawski** [nvkelso/natural-earth-vector#192]
I've imported the Time Zone shape file using `ogr2ogr`:

`"c:\Program Files\GDAL\ogr2ogr.exe" -overwrite -f MSSQLSpatial "MSSQL:server=localhost;database=db;trusted_connection=yes" ne_10m_time_zones.shp -f "ESRI Shapefile" -nln TimeZone`

I have tried using `-oo ENCODING=Windows-1252` with different types of the encoding, but they all end up with the same result: all string data has the same weird character

![image](https://cloud.githubusercontent.com/assets/873800/24481287/4efc57da-14b7-11e7-9450-1b98e8940967.png)

Furthermore, if I ran the command line again, there is a new character inserted. The command line is creating the right data types and columns as it is using `NVARCHAR` with the right lengths (compared with QGIS).

How can I fix this?

**Comment by nvkelso** [comment]
Are you referring to the Û character in the screenshots? I've seen
character encoding funk in corrupted Natural Earth data before, but that's
never been reported for timezones, and the fact that the same Û is
appearing multiple places seems like ogr2ogr + MSSQLSpatial funk. Suggest
posting to SlackOverflow to see if the geo community there has suggestions.

**Comment by jstawski** [comment]
What is the encoding that is used on the Time Zone shape files?

**Comment by jstawski** [comment]
and here's the question in GIS StackExchange: http://gis.stackexchange.com/questions/234118/encoding-issue-with-ogr2ogr-and-sql-server

**Comment by nvkelso** [comment]
I can't reproduce this problem – the original shapefile looks good to me. 

To clarify: in v3.x it may have been Windows-1252 encoding, but in the upcoming v4.x series it'll be forced to UTF8 (but there wasn't anything exotic here).
