### ISSUE TITLE
Incorrect UN features codes and regions

### ISSUE THREAD

**Issue by Toshakins** [nvkelso/natural-earth-vector#195]
Some features representing UN M49 standard are entered incorrectly. For example, natural earth cultural admin 0 countries dataset has next value for REGION_UN feature: Seven seas (open ocean). This value is set for French Southern Islands, US Minor Outlying Islands and, possible, some other territories.

However, this doesn't correspond to the current M49 standard. Steps how to check:
1. Open https://unstats.un.org/unsd/methodology/m49/overview/
2. Enter 'minor' in a search field.

Expected behaviour:
Minor Outlying Islands are listed under some region called 'Seven seas'

Actual behaviour:
Minor outlying islands are part of Micronesia and Micronesia is part of Oceania.

PS: won't you mind a pull request from me? 🤓

**Comment by Toshakins** [comment]
@nvkelso 

If pull requests are welcome, can you also point me to docs/introduce how to correctly do that? Thanks in advance.

**Comment by Toshakins** [comment]
UN_A3 property is also incorrect:
````
$ ogrinfo  -dialect sqlite -sql "select distinct admin from ne_110m_admin_0_countries where un_a3='-099'" ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp
````

````
INFO: Open of `ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp'
      using driver `ESRI Shapefile' successful.

Layer name: SELECT
Geometry: None
Feature Count: 6
Layer SRS WKT:
(unknown)
admin: String (0.0)
OGRFeature(SELECT):0
  admin (String) = Antarctica

OGRFeature(SELECT):1
  admin (String) = French Southern and Antarctic Lands

OGRFeature(SELECT):2
  admin (String) = Northern Cyprus

OGRFeature(SELECT):3
  admin (String) = Kosovo

OGRFeature(SELECT):4
  admin (String) = Somaliland

OGRFeature(SELECT):5
  admin (String) = Taiwan
````

Antarctica and French Southern Territories do have UN code.

**Comment by nvkelso** [comment]
This Excel file is the master copy of attributes: 

- https://github.com/nvkelso/natural-earth-vector/blob/master/housekeeping/ne_admin_0_details.xls

You can change all the resulting country DBF files in the 3 scalesets (10m, 50m, 110m), but the Excel needs to be updated else those will be overwriten in the next full build.

**Comment by Toshakins** [comment]
@nvkelso I finally created a PR for this issue, please take a look if possible #232

**Comment by nvkelso** [comment]
Fixed in 82788323e8c10cc5b16f03a2258dcd0ee1f76c06, scheduled for v5 release. 

Unfortunately the associated PR grew stale as it wasn't merged right away (my bad, and it's in OpenOffice now too), so I recreated it for the 2 UN codes and the several++ regions you called out, 2x checking with your PR's Excel file.

**Comment by Toshakins** [comment]
> the associated PR grew stale

No worries, thanks for doing God's work!

I am not able to verify shapefiles in provided commit at the moment, do you need any action from my side? If not, feel free to close the issue whenever is comfortable for you.

**Comment by nvkelso** [comment]
Thanks! No further action required from you. Once the associated PR is merged I'll close this issue.

**Comment by nvkelso** [comment]
![image](https://user-images.githubusercontent.com/853051/121844956-9b26b580-cc99-11eb-890e-647f64565689.png)

![image](https://user-images.githubusercontent.com/853051/121844978-a37ef080-cc99-11eb-9377-341cf788a9fb.png)

**Comment by nvkelso** [comment]
Closed via https://github.com/nvkelso/natural-earth-vector/pull/446.
