### ISSUE TITLE
French Guiana has `name=France` and `continent=Europe`

### ISSUE THREAD

**Issue by johnbaums** [nvkelso/natural-earth-vector#196]
In http://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-admin-0-countries-2/, the polygon associated with French Guiana has been assigned the `name` "France", and the `continent` "Europe". Is this intentional?

![image](https://user-images.githubusercontent.com/818438/27415217-2ef0291a-5749-11e7-9602-9c919dd17d3c.png)

**Comment by nvkelso** [comment]
Yes it is, it's an integral part of France just like Alaska and Hawaii are integral to the United States.

That said, all those feature can be found in the admin-0 map units and map subunits themes.
