### ISSUE TITLE
Winslow, Ariz. mislocated

### ISSUE THREAD

**Issue by jschleuss** [nvkelso/natural-earth-vector#204]
One of our copy editors noticed that Winslow, Arizona is located a bit farther north than it should be in the `ne_10m_populated_places` dataset found in `10m_cultural`

<img width="867" alt="screen_shot_2017-07-17_at_4_05_54_pm" src="https://user-images.githubusercontent.com/695934/28293755-9627ad40-6b0a-11e7-82a3-ea19d3254c90.png">

Based on on the latest Census place data QGIS determined the centroid should be at `35.02522793, -110.7098497`

<img width="640" alt="screen_shot_2017-07-17_at_4_09_52_pm" src="https://user-images.githubusercontent.com/695934/28293829-070c8e72-6b0b-11e7-906a-68a7b1935732.png">

I can create a pull request if that's easier, but I figured I should make an issue first. 

cc @aquintero4354 related to https://github.com/datadesk/web-map-maker/issues/153

**Comment by nvkelso** [comment]
Oops! I'll take care of it :)

**Comment by nvkelso** [comment]
Fixed in ebe9c34823b6cb1e5339483ed41d5661c536e0e5, but in a branch pending release.

**Comment by jschleuss** [comment]
Thank you sir!

**Comment by jschleuss** [comment]
This is still an issue, shouldn't it have been fixed?
![la-mapmaker-09-19-2017-26-57-2](https://user-images.githubusercontent.com/695934/30617409-cc56381a-9d4a-11e7-83da-c7f055679ad1.png)

**Comment by nvkelso** [comment]
Not yet incorporated into Mapzen tiles.
