### ISSUE TITLE
Download page/link is broken

### ISSUE THREAD

**Issue by Erutan409** [nvkelso/natural-earth-vector#209]
Currently throwing a 404 error.

**Comment by nvkelso** [comment]
Can you include a full URL for the page that's down, please?

I've heard reports the last 2 months that various mid-level download lists are down, but never the main download page at http://www.naturalearthdata.com/downloads/.

Ultimately this relates to some WordPress funk that is proving difficult to track down.

**Comment by nvkelso** [comment]
Seems to have resolved itself, closing.
