### ISSUE TITLE
Add missing US National Park areas

### ISSUE THREAD

**Issue by aaronlidman** [nvkelso/natural-earth-vector#210]
Using [wikipedia](https://en.wikipedia.org/wiki/List_of_national_parks_of_the_United_States) as truth, these are missing:

- Acadia
- America Samoa
- Arches
- Biscayne
- Black Canyon of the Gunnison
- Bryce Canyon
- Carlsbad Caverns
- Congaree
- Cuyahoga Valley
- Dry Tortugas
- Gates of the Arctic
- Great Basin
- Great Smoky Mountains
- Guadalupe Mountains
- Haleakalā
- Hot Springs
- Mammoth Cave
- Mesa Verde
- Pinnacles
- Saguaro
- Theodore Roosevelt
- Virgin Islands
- Wind Cave

---

- Total in truth: 59
- Total in Natural Earth: 38 (64%)

Related: #206

**Comment by nvkelso** [comment]
I suspect most/all of these are in there as POINTS instead of polygons
(there are also some parts shown as lines in Natural Earth).

**Comment by aaronlidman** [comment]
Ah true they are.

That's intentional because they are less significant as indicated by their lower scale rank?

**Comment by nvkelso** [comment]
Generally speaking, yes. The maximum recommended scale for Natural Earth is 1:10,000,000 (equivalent to 7 in web map zooms) and these park areas still wouldn't register at that scale so we show them as points instead.
