### ISSUE TITLE
Some more name fixes needed

### ISSUE THREAD

**Issue by CaucasusandMercury** [nvkelso/natural-earth-vector#211]
**In ne_50m_lakes:**

- [x] `Viljuiskoe Reservoir` should be `Vilyuy Reservoir` [link](https://www.lakepedia.com/lake/vilyuyskoye.html) [link](https://commons.wikimedia.org/wiki/Category:Vilyuy_Reservoir) [link](https://en.wikipedia.org/wiki/Vilyuy_Dam)

**In ne_10m_lakes:**

- [x] `Nizhnekamskoe Reservoir` should be `Nizhnekamsk Reservoir` or possibly `Lower Kama Reservoir` [link](https://en.wikipedia.org/wiki/Nizhnekamsk_Reservoir)
- [x] `Votkinskoe Reservoir` should be `Votkinsk Reservoir` [link](https://en.wikipedia.org/wiki/Votkinsk_Reservoir)
- [x] `Saratovskoe Reservoir` should be `Saratov Reservoir` [link](https://en.wikipedia.org/wiki/Saratov_Reservoir)
- [x] `Viljuiskoe Reservoir` should be `Vilyuy Reservoir` [link](https://www.lakepedia.com/lake/vilyuyskoye.html) [link](https://commons.wikimedia.org/wiki/Category:Vilyuy_Reservoir) [link](https://en.wikipedia.org/wiki/Vilyuy_Dam)
- [x] `Krasnoyarskoe Reservoir` should be `Krasnoyarsk Reservoir` [link](https://en.wikipedia.org/wiki/Krasnoyarsk_Reservoir)
- [x] `Novosibirskoe Reservoir` should be `Novosibirsk Reservoir` [link](https://en.wikipedia.org/wiki/Novosibirsk_Reservoir)
- [x] `Ust-Ilimskoe Reservoir` should be `Ust-Ilimsk Reservoir` [link](http://encyclopedia2.thefreedictionary.com/Ust-Ilimsk+Reservoir) [link](http://www.geographic.org/geographic_names/name.php?uni=-4242997&fid=5262&c=russia) [link](https://en.wikipedia.org/wiki/Ust-Ilimsk_Hydroelectric_Power_Station)
- [x] `Qapshaghay Bgeni` should be `Kapchagay Reservoir` [link](https://en.wikipedia.org/wiki/Kapchagay_Reservoir)

**In ne_50m_rivers_lake_centerlines_scale_rank:**

- [x] An earlier reported issue in [#182 ](https://github.com/nvkelso/natural-earth-vector/issues/182) still remains: in **50 rivers** the **river Ob** is sometimes spelled `Ob` and sometimes `Ob’`,  likewise the dissolve column sometimes spells `RiverOb`, sometimes `RiverOb’`.

And:

- [x] In **ne_50m_lakes:** a lake is spelled `O. Chërnoye`, in **ne_10m_lakes:** its spelled `Ozero Chrnoye`. I suggest correct spelling would be `Ozero Chernoe` or `Lake Chernoe`.
- [x] In **ne_10m_urban_areas_landscan** `Zürich` is spelled `ZÌùrich`
- [x] In **ne_10m_admin_0_countries** and **ne_10m_admin_0_countries_lakes** Åland is spelled `Aland`. In **ne_10m_geography_regions_polys** the spelling is correct - `Åland`.
- [x] Lastly: I still cannot understand why lakes in Russia are sometimes named `Ozero...`, sometimes `Lake...` well nevermind perhaps not a big deal.

**Comment by nvkelso** [comment]
Thanks! I'll have a look now.

**Comment by nvkelso** [comment]
> In ne_10m_urban_areas_landscan Zürich is spelled ZÌùrich

I suspect there are a few more of these. I know this is technically wrong, but do you actually use this theme?

**Comment by nvkelso** [comment]
> In ne_10m_admin_0_countries and ne_10m_admin_0_countries_lakes Åland is spelled Aland. In ne_10m_geography_regions_polys the spelling is correct - Åland.

Renaming things (and using more local scripts and translations) is a v4.1 milestone task, added as https://github.com/nvkelso/natural-earth-vector/issues/212.

**Comment by nvkelso** [comment]
@CaucasusandMercury What about the following in the 50m lakes theme?

- Ubinskoye L.
- Pskoyskoye O.
- O. Yarroto Vtoroye
- O. Yarroto Pervoye
- O. Kulundinskoye
- O. Khantayskoye
- O. Chërnoye
- Lake Segozerskoye

**Comment by nvkelso** [comment]
Vilyuy Reservoir fixed in both 50m and 10m themes.

**Comment by nvkelso** [comment]
> In ne_50m_lakes: a lake is spelled O. Chërnoye, in ne_10m_lakes: its spelled Ozero Chrnoye. I suggest correct spelling would be Ozero Chernoe or Lake Chernoe.

We mix `noye` and `noe` endings already so until that's consistent across the board I propose keeping in the "same" but making the 50m and 10m themes consistently named.

**Comment by CaucasusandMercury** [comment]
> Vilyuy Reservoir fixed in both 50m and 10m themes.
- Oh you mean it had already been fixed? I downloaded the `master` today and think I still found it...I'm not very much at home at Github am I doing things wrong?

> I suspect there are a few more of these. I know this is technically wrong, but do you actually use this theme?
- Eh I actually do with [my map](https://api.mapbox.com/v4/maxmeles.map-a2km8b40/page.html?access_token=pk.eyJ1IjoibWF4bWVsZXMiLCJhIjoiZXdQcXN6RSJ9.ggLVnh7kOU_tv6pDDC_AtA#7/48.148/8.800). There Zürich becomes Zrich but I think it's got to do with me using _old old old_ Tilemill.

> @CaucasusandMercury What about the following in the 50m lakes theme?
> 
> Ubinskoye L.
> Pskoyskoye O.
> O. Yarroto Vtoroye
> O. Yarroto Pervoye
> O. Kulundinskoye
> O. Khantayskoye
> O. Chërnoye
> Lake Segozerskoye

- I'm not sure I understand what you mean? Well to me it's a bit confusing as it's sometimes Ozero or O., and sometimes Lake or L. Would make more sense using one variant only?

> We mix noye and noe endings already so until that's consistent across the board I propose keeping in the "same" but making the 50m and 10m themes consistently named.

-That makes sense.

**Comment by nvkelso** [comment]
I'm working on it right now and ticking them off. Once it's merged to master I'll close this issue and you'll see the changes.

> Lastly: I still cannot understand why lakes in Russia are sometimes named Ozero..., sometimes Lake... well never mind perhaps not a big deal.

Yeah, it's confusing. In general the larger, more well-known outside of Russia lakes get Lake and the less well-known get Ozero. Adding internationalization is a v4.1 task (like with the admin0 names).

> Ubinskoye L.
> Pskoyskoye O.
> O. Yarroto Vtoroye
> O. Yarroto Pervoye
> O. Kulundinskoye
> O. Khantayskoye
> O. Chërnoye
> Lake Segozerskoye

Those all have `oye` endings like some of your other fixes. Is that an expected ending?

> Landscap names... Eh I actually do with my map. There Zürich becomes Zrich but I think it's got to do with me using old old old Tilemill.

Nice map! I recommend labeling with the populated places theme instead. (Which is also another way of saying I'm not going to get to that in this release.)

**Comment by CaucasusandMercury** [comment]
> Yeah, it's confusing. In general the larger, more well-known outside of Russia lakes get Lake and the less well-known get Ozero. Adding internationalization is a v4.1 task (like with the admin0 names).

Sounds good, makes some sense. Like I wrote at he beginning its no big deal.

> Those all have oye endings like some of your other fixes. Is that an expected ending?

Ooo that's an academic question, we'll have to reach out to some linguist or translator for a pro answer there. My idea is that some major features have an established English name already; like we call it Moscow and not Moskva, and we call it the Saratov reservoir and not Saratovskoe vodokhranilishche... most people haven't been to O. Yarroto Pervoye, I suppose, so I'd just leave it like that.

**Comment by nvkelso** [comment]
(These will be the last content changes before final v4.0 polygon building and adm0, adm1 property sorting and public release.)
