### ISSUE TITLE
Oh no the city Dnipropetrovsk has officially changed name to Dnipro

### ISSUE THREAD

**Issue by CaucasusandMercury** [nvkelso/natural-earth-vector#213]
The Ukrainian city `Dnipropetrovsk` ought to be changed to `Dnipro`. 
Changed in 2016; it's a pretty major city after all, about a million. Too late to fix? 
[Link](https://en.wikipedia.org/wiki/Dnipro)

**Comment by nvkelso** [comment]
That's a minor change, I'll fix this release.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/commit/101c9cab4d51ac3c12102fafb8bd6743e8956e55.
