### ISSUE TITLE
Campobello Island and Deer Island

### ISSUE THREAD

**Issue by MattBlissett** [nvkelso/natural-earth-vector#221]
Campobello Island and Deer Island should be in Canada, not the USA.

https://en.wikipedia.org/wiki/Campobello_Island 

https://en.wikipedia.org/wiki/Deer_Island_(New_Brunswick)

**Comment by nvkelso** [comment]
I agree with the suggestion: `c` and `d` going to Canada with `m` remaining in USA. 

Will also require moving the maritime indicator line as indicated in red.

<img width="600" alt="screen shot 2017-09-18 at 14 36 45" src="https://user-images.githubusercontent.com/853051/30566135-a26706a4-9c7f-11e7-9fe5-de20faf553b9.png">

**Comment by nvkelso** [comment]
Fixed via c034dccd73b13a4a2a8e4f0187562bcd7ee1b347.

**Comment by nvkelso** [comment]
In the associated PR:

![image](https://user-images.githubusercontent.com/853051/121844521-002ddb80-cc99-11eb-9bb3-2b58d16b9d0c.png)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/446.
