### ISSUE TITLE
Limited data in 50m, 110m cultural

### ISSUE THREAD

**Issue by econandrew** [nvkelso/natural-earth-vector#228]
Is there a reason the lower detail files have a reduced data set? The use case I have in mind is producing PDF maps at different detail levels (e.g. say 10m for print, 50m for online PDF). But at the moment you can't really process the layers in a detail-independent way, because the data attributes are different. For example for disputed boundaries it's nice to be able to refer to left/right countries, but those only exist in 10m.

I realise that the rows are necessarily different b/c of the different detail level, but it's not obvious that the columns should also be.

(Somewhat related to #143.)

**Comment by nvkelso** [comment]
Mostly this is due to history more than deliberate. Generally speaking the 50m has more attributes than the 110m, and the 10m has more attributes than the 50m – because the extra scale gives you more room to, say, label boundary lines left and right.

**Comment by econandrew** [comment]
Understood, and I guess it would be a breaking change. But referring back to the user case above, the boundary lines left & right fields are useful in their own right even without displaying anything - e.g. to select a particular boundary in a scripted way.

I since discovered mapshaper (which is amazing) and generated my own lower detail layers, so this is moot for me now.
