### ISSUE TITLE
geojson files in repo are out of date

### ISSUE THREAD

**Issue by mfogel** [nvkelso/natural-earth-vector#229]
It seems that recent changes to the `10m_cultural` and `10m_physical` source files haven't propagated to the `geojson` directory. The last commit to the `geojson` directory was [almost three years ago](https://github.com/nvkelso/natural-earth-vector/commits/master/geojson).

**Comment by nvkelso** [comment]
Thanks. I'll update those as part of final v4 milestone packaging (likely tonight).

**Comment by nvkelso** [comment]
After https://github.com/nvkelso/natural-earth-vector/pull/230 landed and I've run the entire Make process there are a handful of problems with the ogr2ogr conversion related to EOF errors (!?):

- zips/10m_physical/ne_10m_rivers_lake_centerlines.zip
- zips/50m_cultural/ne_50m_admin_0_scale_rank.zip
- zips/50m_physical/ne_50m_rivers_lake_centerlines.zip

After those are investigated and fixed I can proceed with final packaging.

**Comment by nvkelso** [comment]
There were a few strange renames in the diff, but all the resulting files checkout so if there was funk before, it's fixed now. Huzzah?

```
renamed:    geojson/ne_10m_admin_1_states_provinces_scale_rank.geojson.gz -> geojson/ne_10m_urban_areas.geojson
renamed:    geojson/ne_10m_roads.geojson.gz -> geojson/ne_10m_bathymetry_G_4000.geojson
renamed:    geojson/ne_10m_admin_0_scale_rank_minor_islands.geojson.gz -> geojson/ne_10m_bathymetry_H_3000.geojson
renamed:    geojson/ne_10m_admin_1_states_provinces_lakes.geojson.gz -> geojson/ne_10m_admin_1_states_provinces.geojson
renamed:    geojson/ne_10m_admin_1_states_provinces_shp.geojson.gz -> geojson/ne_10m_admin_1_states_provinces_lakes.geojson
renamed:    geojson/ne_10m_admin_1_states_provinces.geojson.gz -> geojson/ne_10m_admin_1_states_provinces_lines.geojson
renamed:    geojson/ne_10m_admin_1_states_provinces_lakes_shp.geojson.gz -> geojson/ne_10m_admin_1_states_provinces_scale_rank.geojson
renamed:    geojson/ne_10m_railroads.geojson.gz -> geojson/ne_10m_admin_0_scale_rank.geojson
renamed:    geojson/ne_10m_urban_areas.geojson.gz -> geojson/ne_10m_admin_0_scale_rank_minor_islands.geojson
```

**Comment by nvkelso** [comment]
Regarding https://github.com/nvkelso/natural-earth-vector/issues/229#issuecomment-338454725:

- `10m_physical/ne_10m_rivers_lake_centerlines.shp` has **20 geometry errors** according to QGIS Report Geometry Errors function. Some are odd. This is a derived theme, weird that the scale_rank version of the file is fine.
- `50m_cultural/ne_50m_admin_0_scale_rank.shp` has **10 geometry errors**. It's a polygon theme that was previously run thru MapShaper.org to remove intersections. Re-running in MapShaper.org didn't fine any more intersections, though.
- `50m_physical/ne_50m_rivers_lake_centerlines.shp` has **4 geometry errors**, including the strange `Unknown geometry type 0`.

**Comment by nvkelso** [comment]
I worked around this by commenting out the `ogr2ogr` GeoJSON commands for these 3 files in the Makefile and manually exporting them in QGIS to GeoJSON format. It's a mystery to me why that works since I thought QGIS was using `ogr` under the hood. But done enough for this issue.

Tracking followup in https://github.com/nvkelso/natural-earth-vector/issues/231.
