### ISSUE TITLE
Missing Telangana, India Admin 1

### ISSUE THREAD

**Issue by justinelliotmeyers** [nvkelso/natural-earth-vector#234]
I don't see Telangana, India in the admin 1 datasets. https://en.wikipedia.org/wiki/Telangana

**Comment by systemcatch** [comment]
We also noticed this in https://github.com/tmrowco/electricitymap-contrib/issues/1097. Maybe this could be added in the next release?

**Comment by elliotap** [comment]
Verified

Compare to OpenStreetMap:
<img width="1680" alt="Screen Shot 2021-03-11 at 2 05 23 PM" src="https://user-images.githubusercontent.com/64806657/110861361-dff21900-8272-11eb-9abf-88b2c2c0808a.png">


Proposed edits:
Admin-1 Polygons:
-   Create new geometries splitting Andhra Pradesh into 2 states using geo from https://spelunker.whosonfirst.org/id/1108805979/ 
-   add attributes for Telangana to new geometry

Populated Places:
For Hyderabad:
change ADM1NAME from Andhra Pradesh to Telangana

This leaves Andhra Pradesh without an extant admin-1 capital candidate in 10m populated places. The current capital of Andhra  Pradesh is the new master-planned city Amaravati (https://en.wikipedia.org/wiki/Amaravati#Timeline), which is on the other side of the river from Vijayawada, which is in the 10m populated places set.
A plan has been made to decentralize administration to multiple cities, which has led to protests by farmers going into 2020 (see: https://www.thenewsminute.com/article/amaravati-protest-enters-day-200-andhra-capital-issue-remains-unresolved-127934 ; https://en.wikipedia.org/wiki/2019%E2%80%932020_Amaravati_protests). 

Proposed edit here would be to create a new feature for Amaravati, and track ongoing developments.

**Comment by justinelliotmeyers** [comment]
@nvkelso @stepps00 
https://data.telangana.gov.in/story/telangana-district-mandal-and-revenue-shape-files

**Comment by nvkelso** [comment]
Sounds good, let's add both the new admin-1 and it's functional capital city.

**Comment by nvkelso** [comment]
Process detailed in https://github.com/nvkelso/natural-earth-vector/issues/396#issuecomment-789428141.

**Comment by nvkelso** [comment]
Partial fix via https://github.com/nvkelso/natural-earth-vector/pull/522. The populated places work remains todo so keeping this issue open to hang that off of @elliotap.

**Comment by nvkelso** [comment]
Added new `Admin-1 capital` of **Amaravati** for Andhra Pradesh in India via 93895a4d36326da85faf6262218f75f2d30925f4.

![image](https://user-images.githubusercontent.com/853051/116352475-1398ec00-a7aa-11eb-8d31-30e006ca7c80.png)
