### ISSUE TITLE
Airports: gps_code property should be icao_code

### ISSUE THREAD

**Issue by planemad** [nvkelso/natural-earth-vector#235]
The 4 letter `gps_code` property for airports is actually the [ICAO](https://en.wikipedia.org/wiki/ICAO_airport_code) code identifier. 

Is there any reason this is called a GPS code?

**Comment by nvkelso** [comment]
History.

**Comment by nvkelso** [comment]
Fixed in 155a6fdc2a2e062c5ce80b23a7e4c2370758d538.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/446.
