### ISSUE TITLE
Min_zoom typo in ne_110m_coastline

### ISSUE THREAD

**Issue by PetersonGIS** [nvkelso/natural-earth-vector#238]
In ne_110m_coastline, the min_zoom column is written as "min_zooom" with an extra o.

**Comment by nvkelso** [comment]
Oops, thanks for the catch! I’ll rollout a patch release for this.

**Comment by nvkelso** [comment]
Master has the fix, waiting on a few CMS issues to take live onto naturalearthdata.com (it's on one server but not the other).
