### ISSUE TITLE
Eastern part of Bosnia & Herzegovina is missing

### ISSUE THREAD

**Issue by systemcatch** [nvkelso/natural-earth-vector#239]
In version 4.0.0 of ne_10m_admin_0_countries and ne_10m_admin_0_sovereignty the Eastern part of Bosnia and Herzegovina is missing from the whole.  It seems to be unlabeled.  I don't see any problems with the admin_1 states file.

Maybe this is related to #104?

Great project by the way, really useful.

![b h_missing](https://user-images.githubusercontent.com/30196510/34383420-f6982fa6-eb0c-11e7-8f17-2e8978920a96.png)

**Comment by TomBor** [comment]
Could you reopen the issue? Because you fix it in your project but it's not in NE.
Thanks

**Comment by nvkelso** [comment]
???

**Comment by systemcatch** [comment]
@TomBor I fixed it in our project by using the admin_1 states file.

@nvkelso If you need any more information I'm happy to provide it. Also looks like the admin_0 subunits dataset is effected.

**Comment by TomBor** [comment]
As shown by this capture, eastern part of bosnia is missing in ne_10m_admin_0_countries I download right now from the [website](http://www.naturalearthdata.com/downloads/10m-cultural-vectors/)
![ne-missing-bosnia](https://user-images.githubusercontent.com/8322713/35185859-c812e4ee-fe0a-11e7-845f-9795566032e5.PNG)

**Comment by nvkelso** [comment]
Ah, I’ll fix on my end.

**Comment by lcapel** [comment]
+ 1 🙏

**Comment by nvkelso** [comment]
Still in my queue... will be fixed in v4.1

**Comment by raybellwaves** [comment]
I also would like this

**Comment by nvkelso** [comment]
Agree this is a dup of #104. The fix seems to be adding label points back for both the eastern section of the RS and the northern "joint" area so they'll derive attributes in the join and not be stripped during the "remove oceans" build step.

**Comment by nvkelso** [comment]
EL2WLMNR36 also dup's to here.

**Comment by nvkelso** [comment]
Some progress, using Mapshaper!

<img width="585" alt="screen shot 2018-05-02 at 16 59 04" src="https://user-images.githubusercontent.com/853051/39566805-a5c68c3a-4e71-11e8-8496-de5cd28ffec1.png">

Because of the different snapping tolerances from ArcGIS I will need to go thru the admin 1 and admin 2, and physical themes making sure we don't leave (other) polygons behind.

**Comment by nvkelso** [comment]
And Azerbaijan and Armenia build correctly now using the new system. But waiting on a few other topology and attribute fixes unrelated to this issue before release.

**Comment by nvkelso** [comment]
Fixed by https://github.com/nvkelso/natural-earth-vector/pull/249.

**Comment by systemcatch** [comment]
Thank you for fixing this, I appreciate it.

**Comment by nvkelso** [comment]
This has been released on the public download site: https://www.naturalearthdata.com/blog/miscellaneous/natural-earth-v4-1-0-release-notes/
