### ISSUE TITLE
Add disputed area Brasileira I. between Brazil and Uruguay

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/natural-earth-vector#24]
B85 Braziliera I.                           Uncontested boundary dispute between Brazil and Uruguay over Braziliera/Brasiliera Island in the Quarai/Cuareim River leaves the tripoint with Argentina in question

**Comment by thesocialdev** [comment]
I want to raise a typo in the name: it should be Brasileira, not Brasiliera. If you're going to translate to English it's fair to say Brazilian Island/Ilha Brasileira.

Source: https://pt.wikipedia.org/wiki/Ilha_Brasileira and https://en.wikipedia.org/wiki/Brazilian_Island

**Comment by nvkelso** [comment]
Thank you for the report!

**Comment by nvkelso** [comment]
In the associated PR:

![image](https://user-images.githubusercontent.com/853051/121844421-d4aaf100-cc98-11eb-8480-0f3be8130527.png)

![image](https://user-images.githubusercontent.com/853051/121844400-cbba1f80-cc98-11eb-963b-ce033d65ff9d.png)

![image](https://user-images.githubusercontent.com/853051/121844450-de345900-cc98-11eb-8652-460d390a70e7.png)

**Comment by nvkelso** [comment]
Closed via https://github.com/nvkelso/natural-earth-vector/pull/446.
