### ISSUE TITLE
Missing states from ne_10m_admin_1_states_provinces

### ISSUE THREAD

**Issue by antonioribeiro** [nvkelso/natural-earth-vector#240]
Not sure if I'm looking at this right, but those countries **have no states** in the database `ne_10m_admin_1_states_provinces`:

```
ALA Åland Islands

ATG Antigua and Barbuda

BEL Belgium

BIH Bosnia and Herzegovina

ESH Western Sahara

IRQ Iraq

UNK Kosovo

NOR Norway

PNG Papua New Guinea

PRT Portugal

PSE Palestine

SJM Svalbard and Jan Mayen

SOM Somalia

SRB Serbia

SSD South Sudan

SYR Syria

UMI United States Minor Outlying Islands
```

**Comment by nvkelso** [comment]
That's pretty odd – most (but not all) of those should have states. How are
you determining this?

**Comment by antonioribeiro** [comment]
By loading the shapefile this way:

        $shapeRecords = new ShapeFile($this->dataDir('natural_earth/ne_10m_admin_1_states_provinces'));

        $result = [];

        foreach ($shapeRecords as $record) {
            if ($record['dbf']['_deleted']) {
                continue;
            }

            $result[] = $record['dbf'];
        }

And generating one file per country. But if you say they should be there, I'll look in a bit further.

**Comment by antonioribeiro** [comment]
You are right, sir, of course ;)

I was using the field `gu_a3` to group states by country, but looks like `adm0_a3` may be what I need.

Sorry and thank you.

**Comment by antonioribeiro** [comment]
This one is missing: https://en.wikipedia.org/wiki/State_of_Palestine (PSE Palestine) and we have some others with divergent adm0_a3 codes (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) like 

ALA | Åland Islands

Which is found in your database as 

ALD

The natural-earth-vector database is probably using the correct one, since we cannot rely very much on Wikipedia these days, but could you, please, link a reference to the correct country codes, please? Here's the ones I found different:

```
[adm0_a3] => ALD !== ALA - Åland Islands
[adm0_a3] => SAH !== ESH - Western Sahara
[adm0_a3] => NOR !== SJM -  Svalbard and Jan Mayen
[adm0_a3] => SDS !== SSD - South Sudan
```

**Comment by nvkelso** [comment]
Good to hear!

The `adm0_a3` codes are Natural Earth-isms. If you're looking for ISO codes look in the `iso_a3` column (and related columns) instead.

The listed country-equivalent features are not going to have admin-1 regions/provinces in Natural Earth anytime soon...
