### ISSUE TITLE
Missing Netherlands states

### ISSUE THREAD

**Issue by antonioribeiro** [nvkelso/natural-earth-vector#241]
I'm using your data in a package and I got some complaints about missing states, so I went to check one of those, and this is what I get for the Netherlands in current version (ne_10m_admin_1_states_provinces 4.0):

    "" => "Zuid-Holland"
    "DR" => "Drenthe"
    "FL" => "Flevoland"
    "FR" => "Friesland"
    "GE" => "Gelderland"
    "GR" => "Groningen"
    "LI" => "Limburg"
    "OV" => "Overijssel"
    "ZE" => "Zeeland"

Different from this page: https://en.wikipedia.org/wiki/Provinces_of_the_Netherlands. Why is this different? (Assuming both sources are fairly right, of course).

**Comment by antonioribeiro** [comment]
Sorry the problem is not on missing states, but on missing postal codes for those states: This is the correct list without postal codes:

    0 => "Bonaire"
    1 => "Drenthe"
    2 => "Flevoland"
    3 => "Friesland"
    4 => "Gelderland"
    5 => "Groningen"
    6 => "Limburg"
    7 => "Noord-Brabant"
    8 => "Noord-Holland"
    9 => "Overijssel"
    10 => "Saba"
    11 => "St. Eustatius"
    12 => "Utrecht"
    13 => "Zeeland"
    14 => "Zuid-Holland"

**Comment by nvkelso** [comment]
Postal in this case refers to a 2 or 3 char postal delivery code ala US Post system's CA for California.
