### ISSUE TITLE
github issues vs. tickets

### ISSUE THREAD

**Issue by DaveInCaz** [nvkelso/natural-earth-vector#242]
What's the difference between issues created here vs. things created as tickets on [http://www.naturalearthdata.com/corrections/index.php?a=add](http://www.naturalearthdata.com/corrections/index.php?a=add) ?

Thanks

**Comment by nvkelso** [comment]
Github is preferred because it’s where actual development happens, and it’s all in the public. But because it’s more dev focused and requires an account the old anyone can submit (but more into a private bucket) is maintained.

Changelogs here reference issue ids in both trackers.

**Comment by DaveInCaz** [comment]
Thanks for the explanation.
