### ISSUE TITLE
Norway ISO_A3_EH Code is -99

### ISSUE THREAD

**Issue by nickpeihl** [nvkelso/natural-earth-vector#252]
There's been [previous](https://github.com/nvkelso/natural-earth-vector/issues/12#issuecomment-343972857) [discussion](https://github.com/nvkelso/natural-earth-vector/issues/131) about this and I think I understand the concerns about linking ISO codes to boundaries and why ISO_A3_EH was added. With that understood, could we add `NOR` to the ISO_A3_EH column for Norway? It's currently -99.

I'd be happy to submit a PR but I'm not sure if I need to update all the shapefiles attribute tables or if they each pull their attributes from a central location.

**Comment by enorazza** [comment]
What about ISO_A2?
Norway is totally missing the two characters code..
There already 7 different "NOR", but not a single "NO", which is very weird.
It is accepted as ISO A2 from 1974 as you can see [here](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#NO)

**Comment by mentalstring** [comment]
Same for Portugal, where ISO_A2, ISO_A3 and ISO_A3_EH are all -99.

**Comment by pronebird** [comment]
Norway and France miss ISO_A2 codes. Any progress on fixing this? Seems trivial to fix.

**Comment by nvkelso** [comment]
Added this to the v5 milestone for the `iso_a3_eh` values.

**Comment by nvkelso** [comment]
![image](https://user-images.githubusercontent.com/853051/66962286-76da8780-f025-11e9-9c92-e57e0c47680d.png)

**Comment by mvrhov** [comment]
Well the iso_a2 is still missing on your screenshot.. and there is more replys where the ppl say that some others are also missing
