### ISSUE TITLE
geography_regions_polys are clipped

### ISSUE THREAD

**Issue by ungarj** [nvkelso/natural-earth-vector#253]
It seems some polygons have been clipped. Must have happened between version 2 and 4 (sorry, didn't have version 3 available to check). Greenland for example seems to have been clipped with the North America polygon.

version 2.0.0
![greenland_v2 0 0](https://user-images.githubusercontent.com/3802285/38488418-ae8c67f4-3be3-11e8-9c51-06f356ca8b0a.jpg)

version 4.0.0
![greenland_v4 0 0](https://user-images.githubusercontent.com/3802285/38488419-aeae326c-3be3-11e8-9f31-1690a97734ff.jpg)

This does not seem intentional and rather an error which happened in between?

**Comment by nvkelso** [comment]
Uh oh, that's a bug! I'll have a look...

**Comment by nvkelso** [comment]
This commit is the last good full geom: https://github.com/nvkelso/natural-earth-vector/commit/1cf0feab58b5747487e81e9a2a4af223cb6b509d#diff-a0aae74e9cd2bc5f8d2a839e6aed708c

The subsequent 2 commits aimed to fix geometry / topology – and that's "complicated" even on a good day.

**Comment by ungarj** [comment]
Can I help you somehow to fix this?

**Comment by nvkelso** [comment]
This commit includes the fix: https://github.com/nvkelso/natural-earth-vector/commit/cdebe09ed4a653978b139f6c5126551fd17fcde5.

To test download the following 3 files:

- https://github.com/nvkelso/natural-earth-vector/raw/cdebe09ed4a653978b139f6c5126551fd17fcde5/10m_physical/ne_10m_geography_regions_polys.shp
- https://github.com/nvkelso/natural-earth-vector/raw/cdebe09ed4a653978b139f6c5126551fd17fcde5/10m_physical/ne_10m_geography_regions_polys.dbf
- https://github.com/nvkelso/natural-earth-vector/raw/cdebe09ed4a653978b139f6c5126551fd17fcde5/10m_physical/ne_10m_geography_regions_polys.shx

**Comment by nvkelso** [comment]
Fixed by https://github.com/nvkelso/natural-earth-vector/pull/249.

**Comment by nvkelso** [comment]
This has been released on the public download site: https://www.naturalearthdata.com/blog/miscellaneous/natural-earth-v4-1-0-release-notes/

**Comment by ungarj** [comment]
Cool, thanks :)
