### ISSUE TITLE
Swaziland becomes eSwatini

### ISSUE THREAD

**Issue by pinakographos** [nvkelso/natural-earth-vector#254]
As you've probably seen, Swaziland has been renamed to the Kingdom of eSwatini.
http://www.bbc.com/news/world-africa-43821512

**Comment by nvkelso** [comment]
Fantastic :)

**Comment by ImreSamu** [comment]
Wikidata:   https://www.wikidata.org/wiki/Q1050   ( for tracking label changes )

**Comment by nvkelso** [comment]
Thanks!
