### ISSUE TITLE
Bir Tawil and Halaib unclaimed territories not present

### ISSUE THREAD

**Issue by tehandyb** [nvkelso/natural-earth-vector#255]
Hi I was trying to find if these two territories were present in any of the downloadable map data but I couldn't find them. I looked in the Admin 0 Cultural data and also the Admin 0 Breakaway, Disputed Areas but didn't find the boundaries. Are these ever going to be incorporated into the data? If not I am trying to figure out how to get the json so maybe I can splice it into my own GeoJson using a tool called MapShaper.

**Comment by nvkelso** [comment]
![image](https://user-images.githubusercontent.com/853051/107887356-6d338f00-6eba-11eb-9e28-f66a1f2e33f2.png)

![image](https://user-images.githubusercontent.com/853051/107887367-7fadc880-6eba-11eb-90da-03d2c6a74667.png)

![image](https://user-images.githubusercontent.com/853051/107887376-8b998a80-6eba-11eb-8a97-7f740a288d64.png)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/446.
