### ISSUE TITLE
Offer naturalearthdata.com over HTTPS

### ISSUE THREAD

**Issue by pnorman** [nvkelso/natural-earth-vector#259]
https://www.naturalearthdata.com/ gives a bluehost.com login page.

I'm in an environment where it's easier to have everything over HTTPS.

See https://phabricator.wikimedia.org/T194850

**Comment by nvkelso** [comment]
Good idea. I'll look into it, looks like Bluehost offers a free cert (though their cPanel is a pain).

**Comment by nvkelso** [comment]
Done.

![image](https://user-images.githubusercontent.com/853051/40257175-0461225a-5aa2-11e8-9e46-ac289bcf3940.png)

**Comment by nvkelso** [comment]
The download links themselves start as http (they don't detect https config) but using https does work:

- https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip
