### ISSUE TITLE
Haida Gwaii

### ISSUE THREAD

**Issue by pinakographos** [nvkelso/natural-earth-vector#260]
Haida Gwaii (formerly the Queen Charlotte Islands) are inconsistently named in the 10m and 50m _geography_regions_polys files.

The "name" field lists "Queen Charlotte Islands" but all the other language name fields (and the label field) list "Haida Gwaii," which is presently the official name of the archipelago. I recommend that "Queen Charlotte Islands" be moved to the _namealt_ field.

**Comment by elliotap** [comment]
Verified - https://en.wikipedia.org/wiki/Haida_Gwaii

Compare to Apple:
<img width="1398" alt="Screen Shot 2021-03-18 at 9 35 28 AM" src="https://user-images.githubusercontent.com/64806657/111667812-52fb1280-87d2-11eb-9863-e60fcc7889de.png">

OSM: 
<img width="1680" alt="Screen Shot 2021-03-18 at 10 12 22 AM" src="https://user-images.githubusercontent.com/64806657/111668015-850c7480-87d2-11eb-9bdf-a4b63c54028c.png">

Google:
<img width="1680" alt="Screen Shot 2021-03-18 at 10 13 27 AM" src="https://user-images.githubusercontent.com/64806657/111668095-9fdee900-87d2-11eb-8a7c-94de5bbf22b0.png">

Proposed edits:
for ne_id 1159103495:
Change name from Queen Charlotte Islands to Haida Gwaii
change namealt from NULL to Queen Charlotte Islands

**Comment by nvkelso** [comment]
Works for me, thanks!

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/505.
