### ISSUE TITLE
"Holy See" is misspelled in SOV0NAME

### ISSUE THREAD

**Issue by ericfischer** [nvkelso/natural-earth-vector#261]
In `ne_110m_populated_places`, the Vatican City point has `"SOV0NAME": "Vatican (Holy Sea)"` but `"ADM0NAME": "Vatican (Holy See)"`. They should both, as far as I know, be "Holy See".

**Comment by nvkelso** [comment]
FWIW: I think this got fixed a while ago in the admin-0 themes but it wasn't propagated to the populated places themes (as that was a one-time build a while ago).

**Comment by nvkelso** [comment]
Fixed.
