### ISSUE TITLE
Exclude water glow

### ISSUE THREAD

**Issue by rouen-sk** [nvkelso/natural-earth-vector#264]
Hello, I love this raster: https://www.naturalearthdata.com/downloads/10m-cross-blend-hypso/10m-cross-blended-hypso-with-shaded-relief-and-water/  but I need it without the "glow" of water near islands and continets, so the water is just monotone blue everywhere. Can I somehow generate it like this (right now I have no idea about the process behind this), or can you maybe include this variant? Thanks!

**Comment by nvkelso** [comment]
Please see: https://www.naturalearthdata.com/downloads/10m-cross-blend-hypso/shaded-relief/

You’ll need to bring your own water, which can be from Natural Earth.
