### ISSUE TITLE
http://www.naturalearthdata.com/corrections/ points to an older ticket system

### ISSUE THREAD

**Issue by Fil** [nvkelso/natural-earth-vector#265]
http://www.naturalearthdata.com/corrections/ should probably point [here](https://github.com/nvkelso/natural-earth-vector/issues), or at least mention that corrections for NE-vector should be sent here.

**Comment by nvkelso** [comment]
The older corrections system is for folks without Github accounts, which is a large % of people. Both systems are monitored (and both are mentioned in release notes).

**Comment by nvkelso** [comment]
It redirects to Github directly now, closing.
