### ISSUE TITLE
Part of Virginia Missing, admin_1_states_provinces_lakes

### ISSUE THREAD

**Issue by DylanMoriarty** [nvkelso/natural-earth-vector#269]
![screenshot 2018-09-04 at 3 01 27 pm](https://user-images.githubusercontent.com/9341928/45052001-9c8c1380-b053-11e8-8d94-5be7b425a440.png)

Looks like the east-most part of Virginia is currently not being drawn at all in the current iteration of this file. Would assume it was a simplification thing if the smaller coastline islands weren't still being drawn.

From the 10m files: https://www.naturalearthdata.com/downloads/10m-cultural-vectors/

**Comment by nvkelso** [comment]
It’s probably a snapping bug with the mapshaper refactor, thanks for reporting it!

**Comment by mbloch** [comment]
I just looked into this issue a bit (looked like it might be a mapshaper bug)... I see that the missing piece of Virginia is getting filtered out in the Makefile target `build_a7_ne_10m_admin_1_all`, in the following line:

`		-filter 'adm0_sr <= 6' + \`

The polygon in question has a value of 8:
![image](https://user-images.githubusercontent.com/1232222/46538354-d2562f00-c881-11e8-9d75-8324d419c05f.png)

... I'm not familiar with how these datasets get built, maybe you could take a look, @nvkelso ?

**Comment by nvkelso** [comment]
Yes, fix by editing `10m_cultural/ne_10m_admin_1_label_points.shp` so that point is **adm0_sr** of `2` to match rest of Virginia and neighbour Maryland.

**Comment by nvkelso** [comment]
This particular issue was been resolved. Possibly still more widespread, but that's for another day.

![image](https://user-images.githubusercontent.com/853051/66730352-1cafab80-ee06-11e9-88a0-1f95fff4d314.png)

**Comment by timwallace** [comment]
Looks like it's still missing from these endpoints?
https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces.zip
https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces_lakes.zip

**Comment by nvkelso** [comment]
It’s fixed in v5-prerelease in the branch. Have a look at files in the active PR?
