### ISSUE TITLE
Missing polygon for Hanoi / Ha Noi / Hà Nội

### ISSUE THREAD

**Issue by MichaelChirico** [nvkelso/natural-earth-vector#276]
For this file: https://github.com/nvkelso/natural-earth-vector/blob/master/10m_cultural/ne_10m_admin_1_states_provinces_lakes.shp

https://en.wikipedia.org/wiki/Hanoi

<img width="1011" alt="screen shot 2018-10-14 at 8 43 57 pm" src="https://user-images.githubusercontent.com/7606389/46916805-356a6300-cff2-11e8-9c70-c521536afbb6.png">

**Comment by mbloch** [comment]
@MichaelChirico The version of the Shapefile on the current master branch seems to include Hanoi... is it possible that you're looking at an older version of the file?
![image](https://user-images.githubusercontent.com/1232222/46953109-ddb41200-d05a-11e8-8d7a-9002bcb2a10c.png)

**Comment by MichaelChirico** [comment]
Fixed in latest master

![screen shot 2018-10-16 at 5 34 45 pm](https://user-images.githubusercontent.com/7606389/47009806-f4985880-d16f-11e8-9c83-3ee59f8d5a52.png)

Repro R code

```
library(rgdal)
x = readOGR('.', 'ne_10m_admin_1_states_provinces')

plot(p <- x[which(x$name_en == 'Hanoi'), ], lwd = 3)
text(coordinates(p), labels = p$name_vi)
plot(x, add = TRUE, border = 'gray')
```

**Comment by MichaelChirico** [comment]
Thanks @mbloch for the suggestion, I thought I'd updated but ostensibly not.
