### ISSUE TITLE
Trengganu Malaysia -> Terengganu

### ISSUE THREAD

**Issue by MichaelChirico** [nvkelso/natural-earth-vector#278]
`adm1_code` `MYS-1149`

Spelling has changed... I only see it spelled the "old" way in the `name` field. All the other `name_*` fields (in Roman script) have `Terengganu`.

I don't see anything about when exactly the "old" name was changed on Wikipedia... Though if the update of this page is to be believed, it's at least since 2012:

http://www.nas.gov.sg/archivesonline/photographs/record-details/261d6107-1162-11e3-83d5-0050568939ad

**Comment by elliotap** [comment]
Verified

Compare to Google:
<img width="1680" alt="Screen Shot 2021-03-11 at 1 58 05 PM" src="https://user-images.githubusercontent.com/64806657/110860668-eaf87980-8271-11eb-9f3b-90c1eaced21d.png">


Apple:
<img width="1398" alt="Screen Shot 2021-03-11 at 1 58 17 PM" src="https://user-images.githubusercontent.com/64806657/110860678-edf36a00-8271-11eb-96f5-c0d8fa528082.png">


OpenStreetMap:
<img width="1680" alt="Screen Shot 2021-03-11 at 1 58 33 PM" src="https://user-images.githubusercontent.com/64806657/110860688-f0ee5a80-8271-11eb-903f-4324dba8bf81.png">

Change seems to have been in effect in 1991 (https://search.library.wisc.edu/catalog/999721051902121)

Proposed edits:
Change name from Trengganu to Terengganu

**Comment by nvkelso** [comment]
For admin-1 with **adm1_code** = `MYS-1149`, update the **name** to `Terengganu`, put the old name in **name_alt** as `Trengganu`.

This is a property fix in the admin-1 details "housekeeping" file in the 10m cultural directory. Once updated there, the Makefile target for mapshaper rebuilding needs to be run and will detect the change. This feature is only in the 10m theme so:

> make build_a7_ne_10m_admin_1_all

**Comment by nvkelso** [comment]
Process detailed in https://github.com/nvkelso/natural-earth-vector/issues/396#issuecomment-789428141.

**Comment by nvkelso** [comment]
After #452 

![image](https://user-images.githubusercontent.com/853051/115507066-7af5ef80-a230-11eb-8216-8d244159126d.png)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/520.
