### ISSUE TITLE
Wiki detailing variables and datatypes?

### ISSUE THREAD

**Issue by indolering** [nvkelso/natural-earth-vector#280]
I find myself struggling to Google all the acronyms in the dataset and I'm unsure of the datatype for certain identifiers (ne_id is a 32-bit integer ... right?).  A Github wiki could contain a key with a description of each column, datatype, and any senitinal values.

**Comment by kannes** [comment]
Dupe: https://github.com/nvkelso/natural-earth-vector/issues/153
