### ISSUE TITLE
Downloads don't work!

### ISSUE THREAD

**Issue by malcolm061990** [nvkelso/natural-earth-vector#287]
Hi.
There are critical problems with your downloads page and "open ticket" page.
I can't download anything (for example):
https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip

I can't open the ticket. The problem appears:
Can't connect to database!
Please notify webmaster at support@naturalearthdata.com

**Comment by nvkelso** [comment]
Investigating...

In the meantime, please download from Github (here)!
