### ISSUE TITLE
Coastline and state boundaries vector for Connecticut and New England

### ISSUE THREAD

**Issue by AdamKtriviumInteractive** [nvkelso/natural-earth-vector#289]
Not sure if this worthy as a ticket item, but I am working on a project where I need to isolate Connecticut, but the vector of the state boundary and coastline are not accurate. Can NE fix this? Or, is there a way to import and use my own vector of the state?

I'm using: ne-10m-admin-1-states-provinc-1ta7i4

Thank you,
Adam

![CT-coastline](https://user-images.githubusercontent.com/50710818/57875356-bb48c980-77e0-11e9-9960-64d603466f22.jpg)
![CT-coastline-closeUp](https://user-images.githubusercontent.com/50710818/57875358-bbe16000-77e0-11e9-980a-aa0690178472.jpg)

**Comment by nvkelso** [comment]
You're vastly overzooming Natural Earth from the intended 1:10,000,000 scale (zoom 7 web). Use a different dataset at this zoom like OpenStreetMap.
