### ISSUE TITLE
Burundi Capital City Update

### ISSUE THREAD

**Issue by justinelliotmeyers** [nvkelso/natural-earth-vector#291]
Bujumbura (ne_id 1159150427) is no longer official capital. Gitega (ne_id 1159146001) is now official capital. 
https://en.wikipedia.org/wiki/Gitega - https://www.wikidata.org/wiki/Special:EntityPage/Q167551
https://en.wikipedia.org/wiki/Bujumbura - https://www.wikidata.org/wiki/Special:EntityPage/Q3854

**Comment by nvkelso** [comment]
@justinelliotmeyers Thanks for these tips!

**Comment by nvkelso** [comment]
Fixed.
