### ISSUE TITLE
Rename Capital City for Kazakhstan

### ISSUE THREAD

**Issue by justinelliotmeyers** [nvkelso/natural-earth-vector#292]
Astana renamed to Nur-Sultan.
https://en.wikipedia.org/wiki/Nur-Sultan - https://www.wikidata.org/wiki/Special:EntityPage/Q1520

ne_id=1159150965

**Comment by nvkelso** [comment]
Fixed up the default feature name... and since it's the same Wikidata ID all the name translations fixed themselves up automatically :)
