### ISSUE TITLE
Update Palau Capital City

### ISSUE THREAD

**Issue by justinelliotmeyers** [nvkelso/natural-earth-vector#295]
Capital city is Ngerulmud, not Melekeok. 
https://en.wikipedia.org/wiki/Ngerulmud

**Comment by nvkelso** [comment]
Confirmed with CIA World Factbook and Wikipedia, since 2006. https://www.cia.gov/library/publications/the-world-factbook/geos/ps.html

**Comment by nvkelso** [comment]
Renamed the existing feature as there's not room for both.

New Wikidata ID is `Q515229`, new Geonames ID is `8063361`, and new WOF ID is `1108952603`.
