### ISSUE TITLE
City Add Suggestion

### ISSUE THREAD

**Issue by justinelliotmeyers** [nvkelso/natural-earth-vector#296]
https://en.wikipedia.org/wiki/Arta,_Djibouti

sixth largest city in Djibouti - would be the sixth total city in natural earth for Djibouti
Suggest lat/ long just south east of GNS location:

![image](https://user-images.githubusercontent.com/5324316/60463276-86ba9100-9c19-11e9-9868-574e29d6f151.png)

**Comment by nvkelso** [comment]
It's also an admin-1 capital and we aspire to including full set for each country. Good candidate to add.

GN: 225037
WD: Q705884
WOF: 1125818995
Population: 11043
