### ISSUE TITLE
Question regarding Kosovo's ADM0_A3

### ISSUE THREAD

**Issue by kg-currenxie** [nvkelso/natural-earth-vector#298]
XKX KOS or UNK? :P

I know you guys don't like wiki information. I'm sure you have better sources :) But here's what I found. 
- https://www.wikidata.org/wiki/Q1246 KOS only used for the Olympic committee? 
- https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3 UNK under "Codes currently agreed not to use"

Can anyone clarify why KOS is the current value?

**Comment by nvkelso** [comment]
This is a Natural Earth created value. See other columns for concordance values.

**Comment by kg-currenxie** [comment]
I see :) Thanks
