### ISSUE TITLE
Lakes Balkash and Tanganyika missing in 1:50m lakes dataset

### ISSUE THREAD

**Issue by vladgp** [nvkelso/natural-earth-vector#300]
They appear in both the 1:110m and the 1:10m lakes datasets

**Comment by MrGawsome** [comment]
Lake Tanganyika will be addressed with issue #422. 

I can confirm that Lake Balkash is missing on both the ne_50m_lakes and ne_50m_admin_0_countries shapefiles. ne_id 1159113111 needs to be added to the ne_50m_lakes shapefile with less detail than the 10m version and more detail than the 110m version. The lake's surrounding country needs to be edited to account for the lake shape on the ne_50m_admin_0_countries and ne_110m_admin_0_countries shapefiles as well. Specifically, the country of Kazakhstan (ne_id 1159320967) should be edited to exclude this lake's geometry. See below for screenshots of the missing data:

Missing in the ne_50m_lakes shapefile:
![image](https://user-images.githubusercontent.com/78829897/111397130-c0495f00-867d-11eb-879e-1e2842777ab5.png)

Missing in the ne_50m_admin_0_countries shapefile:
![image](https://user-images.githubusercontent.com/78829897/111397212-f850a200-867d-11eb-98d1-5a6f16378add.png)

Missing in the ne_110m_admin_0_countries shapefile: 
![image](https://user-images.githubusercontent.com/78829897/111397538-cc81ec00-867e-11eb-81d6-5ce059f25327.png)

**Comment by nvkelso** [comment]
For **Lake Balkash** the **min_zoom** = `1.0` so it _should_ be visible also in the 50m and 110m themes, and I agree it's missing from the 50m theme and should be added (with the same attributes as the 10m theme).

10m
![image](https://user-images.githubusercontent.com/853051/111414165-bbe06e80-869c-11eb-9129-3765ce1c1239.png)

110m
![image](https://user-images.githubusercontent.com/853051/111414295-f4804800-869c-11eb-98bb-4985987f3056.png)

**Comment by nvkelso** [comment]
Once this lake (and the other for Tanganyika) is added to the 50m lakes theme, there is a Makefile target to generate the ne_50m_admin_0_countries_lakes theme by erasing the big lakes from the basic 50m countries file automatically: 

> make build_b3_ne_50m_admin_0_countries

https://github.com/nvkelso/natural-earth-vector/blob/master/Makefile#L503-L514

**Comment by nvkelso** [comment]
I dug deeper on this one and these features can be restored from history:

- https://github.com/nvkelso/natural-earth-vector/issues/422#issuecomment-800790935

**Comment by nvkelso** [comment]
Completing via https://github.com/nvkelso/natural-earth-vector/issues/422 (same root cause).
