### ISSUE TITLE
Broken river in Alaska

### ISSUE THREAD

**Issue by pinakographos** [nvkelso/natural-earth-vector#308]
10m_rivers, FID 346: this river is discontinuous. The gaps align with the 10m lakes file, so I assume the lake centerlines just didn't get made.

![Discontinuity](https://user-images.githubusercontent.com/5448396/66222285-6d9d0280-e696-11e9-86f7-829297f8c12b.jpg)

I have attached here a shapefile with two polylines: one is the original river file, with slight topological corrections (the endpoints didn't align with the land or with the 10m lake edges), and the other line is a manually-drawn set of lake centerlines to complete the river line. I wasn't sure what to fill in for the NE_ID field, so you'll need to check that, but for the rest I have copied the attributes from the original. I also added in the river name: Alsek.

[Correction.zip](https://github.com/nvkelso/natural-earth-vector/files/3691363/Correction.zip)

**Comment by MrGawsome** [comment]
This is an older post so we'll have to copy or replicate these fixes onto the current data. ne_id 1159114515 is still missing these lake centerlines, for they aren't present on both the ne_10m_rivers_lake_centerlines and ne_10m_rivers_north_america shapefiles. We can create these lake centerlines on the ne_10m_rivers_lake_centerlines shapefile once the hydro PRs are merged.

**Comment by nvkelso** [comment]
Agree with proposed changes, and thanks @pinakographos for attaching some linework!

The work just needs to be done in one of the themes – just basic theme and not also the North American supplemental.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/525.

**Comment by nvkelso** [comment]
This was for **ne_id** = `1159114515`.
