### ISSUE TITLE
Naming of Russian lakes

### ISSUE THREAD

**Issue by maxmeles** [nvkelso/natural-earth-vector#31]
Most reservoirs are called reservoirs, but the Votkinskoe vodokhranilishche is still called so, should be renamed Votkinsk Reservoir.

Secondly, when zooming from the 50 version to the 10 scale shp the Samara Reservoir is named first Samara (Kuybyshev) res., then simply Samara Reservoir. It's not consequent.

**Comment by nvkelso** [comment]
I don't understand the issue with `Votkinskoe vodokhranilishche`, please explain and provide links.

Samara consistency was fixed awhile ago.

**Comment by maxmeles** [comment]
Like this: `vodokhranilishche` means `reservoir` in Russian. As labels are in English, it ought to be `Votkinsk reservoir` instead of `Votkinskoe vodokhranilishche`. 

That would also make things consistent with the naming of other Russian reservoirs in the dataset.

[Link](https://en.wikipedia.org/wiki/Votkinsk_Reservoir)

**Comment by nvkelso** [comment]
Awesome, that clarifies it for me. I'll include a fix for this in my active sprint (fixed some other hydro names already).

**Comment by nvkelso** [comment]
Changing the name would also be consistent with Natural Earth's naming policy here: http://www.naturalearthdata.com/about/map-update-committee/.

**Comment by nvkelso** [comment]
(There were ~6 other instances where the name was updated from `Vodokhranilishche` to `Reservoir `.)
