### ISSUE TITLE
Admin 1 Capital City Error

### ISSUE THREAD

**Issue by justinelliotmeyers** [nvkelso/natural-earth-vector#310]
Chinhoyi (ne_id 1159134845) is the admin 1 capital of Mashonaland West, Zimbabwe.

Currently Kariba (ne_id 1159134851) is flagged as the capital.

https://en.wikipedia.org/wiki/Mashonaland_West_Province

**Comment by nvkelso** [comment]
👍 Thanks for the tip, I agree.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
