### ISSUE TITLE
Built-up areas of Argentina not included in ne_10m_admin_0_countries

### ISSUE THREAD

**Issue by mcmventura** [nvkelso/natural-earth-vector#312]
Built-up areas not included in Argentinian territory but in the ocean due to country boundaries poorly defined in ne_10m_admin_0_countries/ne_50m_admin_0_countries (e.g. 40.56 S, 62.24 W and -47.75 S, 65.92 W)
[imprecise_country_borders_Argentina.pdf](https://github.com/nvkelso/natural-earth-vector/files/3841655/imprecise_country_borders_Argentina.pdf)

**Comment by nvkelso** [comment]
Hi @mcmventura! Thanks for your interest and report. I agree there are some miss-alignment issues here (and many other areas), but Natural Earth is meant for low- and mid-zoom only, and is not meant for city or street level mapping.

I kindly suggest using another datasource for high-zooms (large scale) like OpenStreetMap or your local national mapping agency data.
