### ISSUE TITLE
Barcelona is in Spain not Venezuela

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/natural-earth-vector#314]
From user report via email:

> I would like to submit a correction that Barcelona is listed as being
part of Venezuela in the 10m Populated Places data set.

I assume this is a bad lat/lng &/or country code problem. Or maybe there are more than one Barcelona in the world!

**Comment by migurski** [comment]
Population 620k: https://en.wikipedia.org/wiki/Barcelona,_Venezuela

**Comment by brylie** [comment]
When filtering the ne_10m_populated_places data by `name_en = "Barcelona"` there is only one row, which is Barcelona, Venezuela. What query should be used to return Barcelona, Spain?

**Comment by nvkelso** [comment]
Looks like the one in Spain is `"NE_ID" = 1159151261`, but I see it's name as `'Barcelona'` in my local file... which is v5.0.0-pre* so your mileage may vary. Suggest browsing the data in an app like QGIS :)

**Comment by brylie** [comment]
What do you see for `name_en`?

**Comment by brylie** [comment]
I am browsing the data in PostGIS.
