### ISSUE TITLE
Tanzania name mismatch between country and unit level

### ISSUE THREAD

**Issue by hyperknot** [nvkelso/natural-earth-vector#317]
I've checked all features in the 10m countries, units and subunits dataset and found one example where the name differs for the same ne_id value between sets.

ne_id: 1159321337
admin: Tanzania
unit: United Republic of Tanzania

**Comment by nvkelso** [comment]
Thanks for the feedback.

We don't make a promise about consistent names between admin and geounit – it's not consistent in other place (look at disputed territories. Closing as not-to-be-fixed.

If you tell me more about your use case and why this is important to you I'll consider reopening the issue.
