### ISSUE TITLE
Horten municipality missing from "Populated Places"

### ISSUE THREAD

**Issue by divinity76** [nvkelso/natural-earth-vector#318]
Horten is a populated municipality in Norway, there's a wikipedia article about it here: https://en.wikipedia.org/wiki/Horten

and it appears that Horten is missing from http://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-populated-places/

it also appears to be missing from the sqlite db at http://naciscdn.org/naturalearth/packages/natural_earth_vector.sqlite.zip

**Comment by nvkelso** [comment]
Closing.

This is a relatively small town and we already have good density of populated places in southern Norway at our maximum scale (with admittedly leaves out most cities).

**Comment by divinity76** [comment]
> Closing.
> 
> This is a relatively small town and we already have good density of populated places in southern Norway at our maximum scale (with admittedly leaves out most cities).

btw would a PR for horten be rejected because Horten is too small/unremarkable ?

**Comment by nvkelso** [comment]
Yes, PR would be rejected for Natural Earth's small list of cities.

But please check to see if it's in Who's On First! If it's not there, it should be :)

**Comment by divinity76** [comment]
gotcha, thanks

> But please check to see if it's in Who's On First! If it's not there, it should be :)

what's that?
