### ISSUE TITLE
Can't filter the country of Ecuador

### ISSUE THREAD

**Issue by pablocarreraest** [nvkelso/natural-earth-vector#320]
There is no Ecuador search by name

**Comment by nvkelso** [comment]
Please provide steps to reproduce this, please?

**Comment by pablocarreraest** [comment]
I follow this steps at MapBox at the link bellow:

[style a single country](https://docs.mapbox.com/help/tutorials/style-single-country/)

I'm sorry if I'm new but when a filter by name "Ecuador" just don't appear.

**Comment by pablocarreraest** [comment]
@nvkelso I learn that was my mistake. I will leave this here that was very useful for me
link [country levels](https://raw.githubusercontent.com/hyperknot/country-levels/master/export/iso2.json) 
Just to note that we need to work as a team to put the some names right.  🙂if ever you need some help for that I'm glad to help

**Comment by nvkelso** [comment]
Great to hear!

Can you share what you’re working on? Looks like admin-1 regions... which are always a work in progress :)

**Comment by pablocarreraest** [comment]
Sure I'm working on a covid-19 tracker want to make the map by provinces

I leave you the links of my work
[website](https://covid19ecuador.carreraestrada.com/)
[mapbox](https://api.mapbox.com/styles/v1/pablines/ck8jz82jy04ui1jpj1qwfbzap.html?fresh=true&title=view&access_token=pk.eyJ1IjoicGFibGluZXMiLCJhIjoiY2s4YmhudDl1MDh3YjNlb3dmbDNqOWZvNSJ9.DaOPna0o3vHPTwHVzgaQOg)

Want to achieve this: 
<img width="466" alt="Screen Shot 2020-04-02 at 5 36 06 PM" src="https://user-images.githubusercontent.com/4999086/78416510-c4a47580-75ee-11ea-97d5-1e3afebed25a.png">

**Comment by pablocarreraest** [comment]
@nvkelso is there a way tu put density on provinces at mapbox? to style across data condition...
