### ISSUE TITLE
City name "El Cayo" in Belize is obsolete

### ISSUE THREAD

**Issue by stefanfis** [nvkelso/natural-earth-vector#323]
The city in western Belize is named _El Cayo_ in the NE database, but according to Wikipedia and the OSM its correct name is _San Ignacio_.

https://en.wikipedia.org/wiki/San_Ignacio,_Belize
https://www.openstreetmap.org/node/297441760#map=14/17.1527/-89.0762

**Comment by mizmay** [comment]
Recommend removing the record for El Cayo and adding a new one for San Ignacio, as there is no wikidata ID for El Cayo.

Verified San Ignacio location is consistent across Open Street Map, Apple Maps, Google Maps

**Comment by nvkelso** [comment]
Please keep the NE record but update it's **name**. The name before was taken from the surrounding admin area, but as @stefanfis points out the city has it's own name of `San Ignacio`. Looks like the wikidata ID should be `Q724815` to pick up the localizations.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
