### ISSUE TITLE
1:50m Natural Earth I (With Shaded Relief) Download - HTTP 404

### ISSUE THREAD

**Issue by Vac1911** [nvkelso/natural-earth-vector#325]
On the [50m-natural-earth-1](https://www.naturalearthdata.com/downloads/50m-raster-data/50m-natural-earth-1/) page:
The first [download link](https://naciscdn.org/naturalearth/50m/raster/NE1_50m_SR.zip), returns a 404 error and does not start the download.

**Comment by nvkelso** [comment]
I can replicate this.

**Comment by nvkelso** [comment]
There's another issue that reports the same...
