### ISSUE TITLE
Populated places 10m: Request to add "Belushya Guba"

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#330]
Belushya Guba (pop. ~2000; https://en.wikipedia.org/wiki/Belushya_Guba) is the main settlement in Novaya Zemlya, an archipelago in the Arctic Ocean. Currently the 10m populated places layer contains three other, much smaller (by population) places on the archipelago.

Requesting to add a feature for Belushya Guba at or around 71.545556, 52.320278

**Comment by nvkelso** [comment]
Thanks for the tips!

**Comment by nvkelso** [comment]
Let's use **ne_id** = `1729769925 `.

**pop_min, pop_max, pop_other** should all be `1972` with **rank_max, rank_min** of `3`.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
