### ISSUE TITLE
Lake Tanganyika

### ISSUE THREAD

**Issue by carlocafaro** [nvkelso/natural-earth-vector#332]
Hello,
I am using Natural Earth Feature on python. I have realized that the lake Tanganyika is not showing up in the maps. 
Do you maybe know why and how to solve the issue?

Thanks.

**Comment by SpockFan02** [comment]
Lake Tanganyika is included in the lakes datasets, which are separate from others such as countries or administrative subdivisions.

**Comment by nvkelso** [comment]
You could switch to the countries without lakes theme, or manually compost the two theme to customize which lakes.
