### ISSUE TITLE
10m Populated Places: Request to change "Lansdowne House" to "Neskantaga"

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#333]
"Lansdowne House" in rural Ontario is a historical name for Neskantaga First Nation. If possible, the name for this feature in 10m populated places should be changed to "Neskantaga"

References:
- http://neskantaga.com/
- https://en.wikipedia.org/wiki/Neskantaga_First_Nation
- https://news.ontario.ca/mirr/en/2008/06/neskantaga-first-nation-opens-new-community-centre.html
- https://www.aadnc-aandc.gc.ca/eng/1357840942104/1360164388764

**Comment by nvkelso** [comment]
Thanks!

**Comment by mizmay** [comment]
Verified!
- Open Street Map https://www.openstreetmap.org/node/5973237383#map=12/52.2022/-87.9593
- Google Maps shows both places https://www.google.com/maps/place/Lansdowne+House,+ON,+Canada/@52.2483645,-88.0993757,11z/data=!4m13!1m7!3m6!1s0x4d648d5650eeb627:0xde6ce10634d3f6d9!2sNeskantaga+Indian+Reserve,+Kenora,+Unorganized,+ON,+Canada!3b1!8m2!3d52.2014143!4d-88.0321218!3m4!1s0x4d64ee515937655f:0x16f91e9874df973e!8m2!3d52.2193869!4d-87.8913116
- Apple Maps shows Neskantaga (see screenshot)

Recommendations:
- Remove record for Landsdowne House (No associated wikidata ID, closest is Q61038201, a meteorological station)
- Add record for Neskantaga? There is no wikidata ID for the town, just the sovereignty (see below)
- Cross-reference with territories/sovereignties polygons

Results:
1 	 Neskantaga First Nation (Q14875338) - Oji-Cree First Nation band government in Ontario, Canada 
2 	 Neskantaga Indian Reserve (Q22595647) 

<img width="868" alt="Screen Shot 2020-12-19 at 9 05 13 PM" src="https://user-images.githubusercontent.com/3074691/102705530-e8235500-423d-11eb-9ff1-3b3cd847d492.png">

**Comment by nvkelso** [comment]
Agree on keeping NE record `1159148901` but renaming it to `Neskantaga`, preserving old name in **namepar**, and looks like there is no appropriate Wikidata ID so NULL.

**Comment by nvkelso** [comment]
@mizmay can you add this one to your PR, please?

**Comment by mizmay** [comment]
I think Q14875338 is the right Wikidata ID for this. There are no localizations associated with it though so won't make a difference this round.

**Comment by mizmay** [comment]
This one Is resolved with 0d5d9b325a3c298edb0133f44f01839f1e58b76e
