### ISSUE TITLE
10m Populated Places: Request to update place name "Bol'sheretsk" to "Ust-Bolsheretsk"

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#334]
The name of the feature "Bol'sheretsk" in the 10m populated places dataset is outdated - its wikipedia page, albeit without sources, discusses the history of the town. https://en.wikipedia.org/wiki/Bolsheretsk

The place should be renamed to "Ust-Bolsheretsk" (https://en.wikipedia.org/wiki/Ust-Bolsheretsk) and moved to ~ 52.825, 156.285

Further references confirming spelling/existence of "Ust-Bolsheretsk":

Reuters News files their stories from Ust-Bolsheretsk: https://www.reuters.com/article/us-russia-kamchatka-poaching/poaching-feeds-and-bleeds-russian-kamchatka-idUSL2284689720070627

National Geographic recognizes the place also: https://webcache.googleusercontent.com/search?q=cache:vaGEdsz9TtQJ:https://www.nationalgeographic.com/magazine/2009/08/kamchatka-salmon/+&cd=33&hl=en&ct=clnk&gl=us

**Comment by mizmay** [comment]
Verified!
- Recommend removing Bol'sheretsk (Q16268949 - but there is no wikidata ID listed in the NE record)
- Recommend adding Ust-Bolsheretsk (Q2502620)

**Comment by nvkelso** [comment]
Move lat/lng, rename, update wikidata ID, done!

**Comment by nvkelso** [comment]
What a curious history.

**Comment by nvkelso** [comment]
So the current place with **ned_id** of `1159139297` has a long history, so another alternate is to mark it **featurecla** = `Historic place`. But it was added after v1.0 which indicates to me the intent was to capture `Ust-Bolsheretsk` instead, which is a larger active town north of there.

So I favor:

**name** to `Ust-Bolsheretsk`
**wikidataid** to `Q2502620`
Move it north to `52.825, 156.285` like @elliotap suggested, adjusting both the lat, lng properties and the geometry.

Else if that's too difficult, keep the existing feature but change the feature class and set populations to 0, and add **wikidataid** of `Q16268949`.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
