### ISSUE TITLE
10m populated places: request to update language-specific names for Kailua-Kona

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#335]
Many language-specific names for Kailua-Kona on the island of Hawai'i have a value of "Kailua" which is the name of another place on the island of O'ahu. Requesting that these language-specific name fields be updated to have a value of of "Kailua-Kona" or language equivalent.

https://en.wikipedia.org/wiki/Kailua,_Honolulu_County,_Hawaii
https://en.wikipedia.org/wiki/Kailua-Kona,_Hawaii

**Comment by nvkelso** [comment]
Is the wikidata ID incorrect?

**Comment by elliotap** [comment]
The wikidata ID for the feature matches this page, which has the correct location/territory information but an incorrect name https://www.wikidata.org/wiki/Q627970

**Comment by nvkelso** [comment]
@elliotap The fix here is to make sure Wikidata is corrected, then rerun the NE-WD update scripts.

**Comment by nvkelso** [comment]
For what it's worth, the other Kailua is not present in Natural Earth (Hilo is the only other locality included on the big island).

From Wikipedia: 

> **Kailua**, also known by its post office designation **Kailua-Kona**[1] (to differentiate it from **Kailua** located on the windward side of Oʻahu island, and sometimes referred to as **Kona** in everyday speech), is an unincorporated town (Census Designated Place) in Hawaiʻi County, Hawaii, United States, in the North Kona District of the Island of Hawaiʻi.[2] The population was 11,975 at the 2010 census,[3] up from 9,870 at the 2000 census. It is the center of commerce and of the tourist industry on West Hawaiʻi. **Kailua-Kona** is served by **Kona** International Airport, located just to the north in the adjacent Kalaoa CDP.[4] 

I'll keep this issue open but remove it from the milestone.

The fix is to update the names upstream, but that's out of scope here right now.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/713.
