### ISSUE TITLE
10m & 50m populated places: request to change name:en value for "Bandar Lampung", Indonesia

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#336]
In both 10m & 50m populated place sets, the name:en value for the city Bandar Lampung (https://en.wikipedia.org/wiki/Bandar_Lampung) is stylized as "Bandarlampung" which conflicts with most other name values for the feature as well as with how the city stylizes its name. Requesting a change from name:en value to "Bandar Lampung" 

See also city website: http://bandarlampungkota.go.id/

**Comment by mizmay** [comment]
See also #365

**Comment by nvkelso** [comment]
The Wikidata ID was shared between them, and English value at Wikidata has been corrected since last run, so rerun the name script.

The bad feature will be deleted via #365, thanks for linking them up!
