### ISSUE TITLE
10m populated places: Request for location changes

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#338]
Requesting location changes for the following places in the 10m populated places data:

Jacunda, Brazil (https://en.wikipedia.org/wiki/Jacund%C3%A1) to -4.450833, -49.115833
Peter I Island (https://en.wikipedia.org/wiki/Peter_I_Island) to -68.85, -90.583333
Dawwah, Oman (https://en.wikipedia.org/wiki/Masirah_Island) to 20.551305, 58.812826

**Comment by elliotap** [comment]
Jacunda, Brazil - Confirmed

Compare to Google: 
<img width="1792" alt="Screen Shot 2021-03-08 at 2 21 33 PM" src="https://user-images.githubusercontent.com/64806657/110389621-a1aded00-8019-11eb-80ac-b4950d17e4e1.png">

OpenStreetMap:
<img width="1792" alt="Screen Shot 2021-03-08 at 2 21 28 PM" src="https://user-images.githubusercontent.com/64806657/110389648-a83c6480-8019-11eb-82b4-4e10ee3634d6.png">

Proposed edits:
Move feature to -4.439458813239052, -49.11569304093503
Change Latitude to -4.439458813239052
Change Longitude to -49.11569304093503

**Comment by elliotap** [comment]
Peter I Island - Confirmed

Compare to Google:
<img width="1792" alt="Screen Shot 2021-03-08 at 2 23 29 PM" src="https://user-images.githubusercontent.com/64806657/110391268-184bea00-801c-11eb-986d-63b6f87b1e98.png">

OpenStreetMap:
<img width="1792" alt="Screen Shot 2021-03-08 at 2 23 34 PM" src="https://user-images.githubusercontent.com/64806657/110391284-1d109e00-801c-11eb-8ee0-2cdbf4754e14.png">

Proposed edits: Move point feature somewhat south
Move feature to -68.79516139740792, -90.58420304456733
Change Latitude to -68.79516139740792
Change Longitude to -90.58420304456733

**Comment by elliotap** [comment]
Dawwah, Oman - Not Confirmed, but location could be improved

Compare to Google: 
<img width="1792" alt="Screen Shot 2021-03-08 at 2 42 51 PM" src="https://user-images.githubusercontent.com/64806657/110391690-bb046880-801c-11eb-90e2-835c9c0d8d94.png">

OpenStreetMap:
<img width="1792" alt="Screen Shot 2021-03-08 at 2 42 56 PM" src="https://user-images.githubusercontent.com/64806657/110391713-c22b7680-801c-11eb-9833-0a3c6d04afbe.png">

Going to look for more resources here about the origin of "Dawwah" name as seen on wikipedia image map - right now it seems that the main settlement on the island may be named "Hilf"

**Comment by nvkelso** [comment]
@nvkelso to review and Dawwah is MIA / needs research.

**Comment by elliotap** [comment]
For Dawwah - some complication

Dawwah was confirmed on a few reference maps:

http://legacy.lib.utexas.edu/maps/tpc/txu-pclmaps-oclc-22834566_j-7b.jpg
<img width="1680" alt="Screen Shot 2021-03-25 at 2 51 36 PM" src="https://user-images.githubusercontent.com/64806657/112548588-b14b6680-8d79-11eb-9e39-fcaf26a76051.png">

http://legacy.lib.utexas.edu/maps/onc/txu-pclmaps-oclc-8322829_j_7.jpg
<img width="1680" alt="Screen Shot 2021-03-25 at 2 51 51 PM" src="https://user-images.githubusercontent.com/64806657/112548636-c3c5a000-8d79-11eb-9840-9627fdf6d5b8.png">

Further information about Dawwah was hard to find.

### The main settlement on Masirah Island is ``Hilf`` with ``wikidataid=Q26201456``

Compare to OSM:
<img width="1680" alt="Screen Shot 2021-03-25 at 3 03 05 PM" src="https://user-images.githubusercontent.com/64806657/112549567-3e42ef80-8d7b-11eb-8151-a5259a7affc0.png">

Google: 
<img width="1680" alt="Screen Shot 2021-03-25 at 3 03 47 PM" src="https://user-images.githubusercontent.com/64806657/112549620-53b81980-8d7b-11eb-9fa7-8769f5eb8706.png">

see "Raʾs-Ḥilf" in https://en.wikipedia.org/wiki/Masirah_Island
and https://ar.wikipedia.org/wiki/%D8%AD%D9%84%D9%81_(%D9%85%D8%B5%D9%8A%D8%B1%D8%A9)

From Lonely Planet guidebook (https://www.google.com/books/edition/Lonely_Planet_Oman_UAE_Arabian_Peninsula/RzWsDwAAQBAJ?hl=en&gbpv=1&dq=hilf,+masirah,+oman&pg=PT302&printsec=frontcover also https://www.lonelyplanet.com/oman/sharqiya-region/masirah/attractions/hilf/a/poi-sig/1613086/361120)
<img width="638" alt="Screen Shot 2021-03-25 at 2 50 07 PM" src="https://user-images.githubusercontent.com/64806657/112548696-d93aca00-8d79-11eb-8273-bb0e170b3b16.png">


Proposed edits:
Move feature to 20.656153298237268, 58.87676215573278
Latitude to 20.656153298237268
Longitude to 58.87676215573278
name to Hilf
namealt to Dawwah
nameascii to Hilf
wikidataid to Q26201456
POP_MAX to 8500 (from Arabic wikipedia)

**Comment by mizmay** [comment]
@elliotap @nvkelso shall I include this in https://github.com/nvkelso/natural-earth-vector/pull/508?

**Comment by nvkelso** [comment]
@elliotap Thanks for the further research on Hilf (Dawwah).

Yes, @mizmay this is ready for inclusion into #508, thanks! Note there are multiple changes to separate NE features in this issue.

**Comment by mizmay** [comment]
Changing POP_MAX to 8500. POP_MIN is currently set to 971. Does retaining this latter value make sense?

**Comment by nvkelso** [comment]
> Changing POP_MAX to `8500`. POP_MIN is currently set to 971. Does retaining this latter value make sense?

You can set POP_MIN to `8500` as well, good catch!

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
