### ISSUE TITLE
10m populated places: Request to change name of Gar, Tibet to Shiquanhe, Tibet

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#339]
Gar is a historical name for the town now known as Shiquanhe (among other names). Although Gar is not wrong as the name for the county seat, requesting an update to the current name of Shiquanhe. https://en.wikipedia.org/wiki/Shiquanhe

**Comment by mizmay** [comment]
Verified!
- OpenStreetMap https://www.openstreetmap.org/relation/7697594
- Google Maps https://www.google.com/maps/place/Shiquanhe,+Gar+County,+Ngari+Prefecture,+Tibet,+China/@31.3099264,78.5339123,6.69z/data=!4m5!3m4!1s0x39a977e3a81e8b39:0x296cc306cebdd08c!8m2!3d32.493989!4d80.101607
- Not present on Apple Maps

- Recommend removing the record for Gar (no corresponding wikidata ID in NE)
- Recommend adding Shiquanhe (Q2279283)

Shiquanhe is at the junction of two roads (G219, S301). Location of Ger/Gar is slightly different.

**Comment by nvkelso** [comment]
Recommend keeping existing feature, moving existing name to parenthetical, updating name, evaluating if it needs a lat/lng move, add wikidata_id.

**Comment by nvkelso** [comment]
**name** to `Shiquanhe`
**name_par** to `Gar`
**name_alt** of `Ger, Sênggêkanbab, Sênggêzangbo, Sengge Zangbo, Senge Zangbo, Senge Zangbu, Sengghe Tsangpo`
**wikidata_id** of `Q2279283`.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
