### ISSUE TITLE
10m lakes: Request to remove Kabalebo Dam

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#342]
Satellite imagery and written documents indicate that Kabalebo Dam and feature 1159116595, in the 10m lakes layer, do not yet exist. Requesting they be removed. 

Ref: https://en.wikipedia.org/wiki/Kabalebo#Economic_Development

**Comment by nvkelso** [comment]
@elliotap Thanks for all these issues! I'm curious, can you share a little more about the project you're working on?

**Comment by kevinventullo** [comment]
Hi Nathaniel. We're the team at Facebook building out an internal base map solution. We use Natural Earth for water, transit, admin labels, and a few other things at low zooms. Happy to answer any questions!

**Comment by nvkelso** [comment]
Rad! Let me know how I can best help. I work on Natural Earth in between other projects and family time but if there's a deadline I could shift stuff around.

**Comment by MrGawsome** [comment]
After some research, it seems like the dam still doesn’t exist. It doesn’t appear to be in any imagery in OSM, and wikipedia pages and the sources listed on them suggest the dam doesn’t exist yet and it is uncertain if it will come to fruition. OSM, Google, and Apple all don’t have the feature as well, further suggesting it doesn’t exist. 

My recommendation is to remove ne_id 1159125751 from the ne_10m_lakes shapefile. It is ok to proceed with this plan?

See below for more information:
https://en.wikipedia.org/wiki/Kabalebo#Economic_Development and some of the sources cited, such as page 52 of the dutch document http://www.nsi-ins.ca/wp-content/uploads/2013/03/West-Suriname-WAT-Betekent-Een-Geintegreerde-Aluminium-Industrie-Voor-De-Inheemse-Gemeenschappen.pdf that when translated, says that “the agreement has not been concluded,”  which references the dam construction plan.
https://en.wikipedia.org/wiki/Kabalebo_River and its source http://abyayala.nativeweb.org/suriname/suriname3.html , which suggests the dam hasn’t been constructed yet.

**Comment by nvkelso** [comment]
Sounds good, let's remove the feature. Just got to make sure the centerline goes to a `River` **featurecla** with the surrounding properties (name & etc).

**Comment by nvkelso** [comment]
Also there is an active PR for lakes and rivers so let's get that merged first before you open yours.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/525.
