### ISSUE TITLE
Were properties description (especially for abbreviations) can be found?

### ISSUE THREAD

**Issue by tbicr** [nvkelso/natural-earth-vector#344]
There are lot of properties in data, unfortunately some of them contains abbreviations that hard to understand what they means. So providing some description for them can really help.

**Comment by nvkelso** [comment]
Sorry about that. Largely it's an artifact of using Shapefiles to distribute the data and the DBF component can only have field names up to 10 characters long so they all get shortened.

Please see this other issue for some tips:

- https://github.com/nvkelso/natural-earth-vector/issues/153

If you need more information commit there and I'm happy to add more details.
