### ISSUE TITLE
World 1:50 dataset - countries missing

### ISSUE THREAD

**Issue by FrancescoMattion** [nvkelso/natural-earth-vector#345]
Hello,

I noticed that in the 1:50 World dataset some countries are missing, e.g. Malta, Singapore, Gibraltar, Curacao.

Would it be possible to have them?

Thanks!

**Comment by nvkelso** [comment]
Those are tiny (like 3 point polygons) at that scale, so instead they are point geometries in the tiny countries theme instead.

**Comment by SamAbdelbadie** [comment]
Vietname is also missing
