### ISSUE TITLE
Ñuble Region

### ISSUE THREAD

**Issue by SpockFan02** [nvkelso/natural-earth-vector#346]
The Ñuble Region of Chile was split off from Bío Bío in 2018, and it would be awesome if the admin 1 data included it.

**Comment by SpockFan02** [comment]
Would [this](https://www.bcn.cl/siit/mapas_vectoriales) be a suitable data source? The `Division regional: polígonos de las regiones de Chile` download has a shapefile with the current regions, and at the bottom of the page it says:

> Condiciones de uso:

> Los mapas vectoriales son puestos a disposición en virtud del principio de transparencia de la función pública. Las personas o instituciones pueden usar libremente esta información, señalando como fuente a la Biblioteca del Congreso Nacional de Chile. El material sólo posee carácter referencial, y bajo ninguna circunstancia debería ser utilizado para realizar trabajos que requieran precisión geodésica.

Translation: Conditions of use: The vector maps are given for use by virtue of the principle of public transparency. Persons or institutions may freely use this information, citing the Library of the National Congress of Chile as the source. The material is only of a reference character, and under no circumstances should it be used to undertake works that require geodesic precision.

I am not a legal or licensing expert, so I don't know if that qualifies it as public domain as required for this project, and I have also never contributed before, so given that warning I don't know if the shapefile would be considered accurate enough to base a contribution on.

For what it's worth, the UN Office for the Coordination of Humanitarian Affairs Regional Office for Latin America and the Caribbean have used the above data as a basis for [their own shapefiles](https://data.humdata.org/dataset/chile-administrative-level-0-country-1-region-region) which they say are licensed under [Creative Commons Attribution for Intergovernmental Organisations](https://data.humdata.org/about/license).

**Comment by elliotap** [comment]
Verified - https://en.wikipedia.org/wiki/%C3%91uble_Region

Compare to Apple (not yet updated):
<img width="1398" alt="Screen Shot 2021-03-18 at 11 55 14 AM" src="https://user-images.githubusercontent.com/64806657/111681922-04a14000-87e1-11eb-9f33-b820194f8df5.png">

Google:
<img width="1680" alt="Screen Shot 2021-03-18 at 11 56 28 AM" src="https://user-images.githubusercontent.com/64806657/111681938-0965f400-87e1-11eb-86a3-94c6270e0ee7.png">


OSM:
<img width="1680" alt="Screen Shot 2021-03-18 at 11 55 50 AM" src="https://user-images.githubusercontent.com/64806657/111681971-108d0200-87e1-11eb-9827-cb5c179c6954.png">

Proposed Edits:
Create new region in Chile for Ñuble Region, with wikidata_id=Q24076693
<img width="1680" alt="Screen Shot 2021-03-18 at 12 01 07 PM" src="https://user-images.githubusercontent.com/64806657/111682625-d5d79980-87e1-11eb-9d09-87817b0e3cb1.png">

For Chillán in 10m populated places, change featurecla from Populated place to Admin-1 capital and ADM1NAME from Bío-Bío to Ñuble (Also, is this ADM1NAME a derived value, or will it require manual edit for populated places within each new admin 1?)
https://en.wikipedia.org/wiki/Chill%C3%A1n

**Comment by nvkelso** [comment]
Agree with the change!

Yes, you need to manually update the Populated Places theme attribute as you propose. 

In the distant past they were based on a spatial join... but there have been spot edits since to reflect real world 1:10,000 accuracy instead of Natural Earth's geometry accuracy of 1:10,000,000.

**Comment by nvkelso** [comment]
Process detailed in https://github.com/nvkelso/natural-earth-vector/issues/396#issuecomment-789428141.

**Comment by nvkelso** [comment]
Now looks like after #520:

![image](https://user-images.githubusercontent.com/853051/115506812-281c3800-a230-11eb-9fcb-7de15f6441ac.png)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/520.
