### ISSUE TITLE
Outdated provincial boundaries - South Africa

### ISSUE THREAD

**Issue by mtb-za** [nvkelso/natural-earth-vector#347]
I noticed that the South African provincial boundaries are outdated, dating back to before the constitutional amendment in 2005.

https://en.wikipedia.org/wiki/Twelfth_Amendment_of_the_Constitution_of_South_Africa has some details (a similar change but less sweeping in scope happened in 2009 with the 16th Amendment).

The official text of the gazette is here: https://www.gov.za/sites/default/files/gcis_document/201409/const121.pdf

**Comment by MrGawsome** [comment]
It looks like Who’s On First has the recent regions of South Africa, including the boundary changes from South Africa’s 16th and 12th amendments. Maybe we can import these boundaries? 

Who’s On First South Africa regions: https://spelunker.whosonfirst.org/placetypes/region/?&iso=za
Who’s On First Gauteng region, which had the area of Merafong added in the west, which Who’s On First has: https://spelunker.whosonfirst.org/id/85688923/
16th amendment wiki, which includes a map: https://en.wikipedia.org/wiki/Sixteenth_Amendment_of_the_Constitution_of_South_Africa
Official 16th amendment text: https://www.gov.za/sites/default/files/gcis_document/201409/320653670.pdf
South Africa maps that seem updated:
https://www.ncbi.nlm.nih.gov/books/NBK481848/figure/chapter2.f1/
https://southafrica-info.com/land/nine-provinces-south-africa/
Also, see the map on the 12th amendment link that mob-za posted.

**Comment by mtb-za** [comment]
Just to add that OpenStreetMap seems to have the correct boundaries, although I am not sure of the source used for those. Possibly the municipal demarcation board's data can be used, although it is for Admin 3 and 4, rather than Admin 1. They can probably be aggregated though?

https://dataportal-mdb-sa.opendata.arcgis.com/search?tags=2018 has the most recent district-level (admin 3) boundaries, if those are helpful? Dissolving one of these by province should get the more up to date versions.

**Comment by nvkelso** [comment]
Process detailed in https://github.com/nvkelso/natural-earth-vector/issues/396#issuecomment-789428141.

@mtb-za thanks for the additional info and data link!

**Comment by nvkelso** [comment]
Fix via 2d66e1ece417b6e6b1b469fa3c87fa34f8e19bbf in the `v5-prequel` branch.

![image](https://user-images.githubusercontent.com/853051/116359761-08e35480-a7b4-11eb-8626-0d59073d7326.png)
