### ISSUE TITLE
new zealand admin 1 boundaries are off

### ISSUE THREAD

**Issue by justinelliotmeyers** [nvkelso/natural-earth-vector#352]
the https://datafinder.stats.govt.nz/layer/104253-regional-council-2020-clipped-generalised/ or you can dissolve the https://datafinder.stats.govt.nz/layer/104278-meshblock-higher-geographies-2020-high-definition/ data at the regional council (REGC2020) level for accurate admin 1s.

**Comment by elliotap** [comment]
@justinelliotmeyers hi Justin, are you requesting changes to specific boundaries, or increased precision of all boundaries?

**Comment by justinelliotmeyers** [comment]
@elliotap from what I recall, the NE data isn't accurate for several boundaries. I'd have to go back and dissolve the suggested data and look. If you need me to do that, let me know and I can be more specific.  Thanks

**Comment by elliotap** [comment]
@justinelliotmeyers thanks, i took a look at the boundaries as compared to the data you linked to and OSM as well. The regions look correct to me as far as number and location, but the geometry on the north island looks like it could be improved somewhat. please do let me know if there is anything else.

<img width="1792" alt="Screen Shot 2021-03-25 at 11 27 15 AM" src="https://user-images.githubusercontent.com/64806657/112524485-1fcdfb80-8d5d-11eb-84c7-0effd74705cd.png">

Proposed edit - realign highlighted boundaries here to improve the generalized shape such that the concave/convex parts better reflect ground truth 

<img width="1792" alt="Screen Shot 2021-03-25 at 11 23 42 AM" src="https://user-images.githubusercontent.com/64806657/112524507-23fa1900-8d5d-11eb-9580-4701b4172c66.png">

**Comment by justinelliotmeyers** [comment]
@elliotap just downloaded again to re-check - yes those are the main areas that would improve from this. Thanks for checking! Justin

**Comment by nvkelso** [comment]
Process detailed in https://github.com/nvkelso/natural-earth-vector/issues/396#issuecomment-789428141.

**Comment by nvkelso** [comment]
After #520 _(red lines new, blue lines old):_

![image](https://user-images.githubusercontent.com/853051/115507504-15eec980-a231-11eb-8e42-337c602fb802.png)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/520.
