### ISSUE TITLE
Missing Virginia part of Delmarva (Eastern Shore) in several datasets

### ISSUE THREAD

**Issue by creosotemaps** [nvkelso/natural-earth-vector#355]
Hello!

I have found a few datasets where the Virginia portion of Delmarva (the peninsula on the eastern shore of Chesapeake Bay in the eastern United States) is missing. You can see this at 75.7957558°W 37.6287514°N.

I see this region missing in ne_10m_admin_1_states_provinces and ne_10m_admin_1_states_provinces_lakes. It is present in ne_10m_admin_0_countries, however. I haven't looked at other shapefiles to see but you should check all of them!

**Comment by nvkelso** [comment]
In earlier version it looked like:

![image](https://user-images.githubusercontent.com/853051/107869472-60278900-6e43-11eb-89db-970414630bca.png)

Now in v5-pre it looks like:

![image](https://user-images.githubusercontent.com/853051/107869490-8cdba080-6e43-11eb-986e-1f4abf3395c5.png)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/446.
