### ISSUE TITLE
10m roads: unknown roads in Chile on water are "Ferry Route"

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#357]
In the 10m roads dataset, all road segments in Chile, south of the town of Castro, that seem to go through water, should have the value "Ferry Route" in the "type" attribute, not "unknown". I have found four such segments, the southernmost at Punta Arenas.

**Comment by elliotap** [comment]
1) Confirmed year-round ferry service for Punta Arenas - Porvenir: http://www.tabsa.cl/portal/index.php/en/services/54-punta-arenas-porvenir-crossing

2) Confirmed year-round ferry service for Quellón - Chacabuco & Quellón - Chaitén: https://www.contactchile.cl/en/travel/boat-trips-ferries/ferries-patagonia.html

3) Confirmed year-round ferry service for Puerto Yungay - Puerto Natales: https://www.contactchile.cl/en/travel/boat-trips-ferries/ferries-patagonia.html

<img width="1792" alt="Screen Shot 2021-03-04 at 1 27 37 PM" src="https://user-images.githubusercontent.com/64806657/110035031-ff77c780-7cef-11eb-8f7e-004ad53806b0.png">

Proposing attribute changes for highlighted features to featurecla=Ferry and type=Ferry Route

**Comment by nvkelso** [comment]
Agreed.

**Comment by nvkelso** [comment]
Fixed via #485.
