### ISSUE TITLE
10m populated places: Kandalaksha, Murmansk, Russia, has too high maxpop

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#359]
In the 10m populated places, Kandalaksha (Murmansk, Russia) has a marked maxpop value of over 100,000 inhabitants. However, no other source I consulted mentions any population over 50,000. Please consider correcting the maxpop value to 50,000.

**Comment by elliotap** [comment]
Verified - (https://www.gks.ru/free_doc/new_site/perepis2010/croc/Documents/Vol1/pub-01-11.pdf, p.500)
<img width="644" alt="Screen Shot 2021-03-11 at 1 04 40 PM" src="https://user-images.githubusercontent.com/64806657/110854886-7837d000-826a-11eb-90c4-2de7f5573074.png">

Proposed edits: reduce population values (which ones?)

**Comment by nvkelso** [comment]
For **ne_id** = `1159148085`, I agree the population of `Kandalaksha` (Murmansk, Russia) possibly should be adjusted down. 

From @elliotap's research it seems like it should either be `38,126` or `35,654`. Do we know the English translation on those values and the `2,482` which accounts for the difference?

The too large value comes from older vintage Landscan (see screenshot below) which is likely aggregating too much population from the rural county into the main city here (eg OSM relation [1029133](https://www.openstreetmap.org/relation/1029133)) ? Or there are possibly 3 little cities here and we need to find all 3 of their populations and sum them up. If it's just one feature than I'd set the min and max populations to the same value, and update the pop ranks (and ignore the pop_other).

![image](https://user-images.githubusercontent.com/853051/111260938-e66bf200-85de-11eb-9b26-a117900f83e9.png)

Same area in OSM though the adjacent "cities" are listed as suburb:

![image](https://user-images.githubusercontent.com/853051/111261094-26cb7000-85df-11eb-9986-5f8ba8ab3312.png)

Either way the population seems to be radically shrinking census to census!

**Comment by nvkelso** [comment]
I propose, with @elliotap to confirm, then move to @mizmay :

**pop_max** = `38126`
**pop_min** = `35654`

**Comment by elliotap** [comment]
verified - translation at https://translate.google.com/?sl=auto&tl=en&text=%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D1%81%D0%BA%D0%BE%D0%B5%20%D0%BF%D0%BE%D1%81%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%9A%D0%B0%D0%BD%D0%B4%D0%B0%D0%BB%D0%B0%D0%BA%D1%88%D0%B0%2038136%2017353%2020783%2045%2C5%2054%2C5%20&op=translate

adding @mizmay

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
