### ISSUE TITLE
10m places: Johannesburg, South Africa is not Admin-0 capital

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#364]
In the 10m places dataset, Johannesburg (South Africa) is now listed as Admin-0 capital. However, it is an Admin-1 capital. South Africa already has three Admin-0 capitals (Pretoria, Cape Town, Bloemfontein) and really doesn't need a fourth... ;-)

**Comment by nvkelso** [comment]
I disagree with this suggestion, closing.

Johannesburg is the seat of the [Constitutional Court](https://en.wikipedia.org/wiki/Constitutional_Court_of_South_Africa), the highest court in South Africa so under Natural Earth's peculiar system of measure, it's a capital but (like Valparaíso in Chile) should instead be marked `Admin-0 capital alt`.

This is in addition to the formal judicial capital at [https://en.wikipedia.org/wiki/Bloemfontein](Bloemfontein) which is HQ to [https://en.wikipedia.org/wiki/Supreme_Court_of_Appeal_(South_Africa)](Supreme_Court_of_Appeal_) which hears non-constitutional matters.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
