### ISSUE TITLE
10m places: Bandar Lampung (Sumatra, Indonesia) is listed twice

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#365]
In the 10m places dataset, Bandar Lampung (Sumatra, Indonesia) is listed twice: once as an Admin-1 capital (correctly), and once as a "Populated place" with the exact same population. The latter ought to be removed.

**Comment by nvkelso** [comment]
Good find! Looks like the location and other properties of the generic populated place is better than the Admin-1 capital, so I'd delete the capital `1159139819`, and update **featurecla** of `1159149817` to `Admin-1 capital`.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
