### ISSUE TITLE
10m places: misspelling of Akureyri (Iceland) 

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#366]
In the 10m places dataset, Iceland contains Akureyi; however, the correct spelling is Akureyri. https://en.wikipedia.org/wiki/Akureyri

**Comment by elliotap** [comment]
Confirmed: correct name is Akureyri

Compare to Google: 
<img width="1680" alt="Screen Shot 2021-03-05 at 9 54 59 AM" src="https://user-images.githubusercontent.com/64806657/110154323-fbec4b00-7d98-11eb-88ea-58c993c944c3.png">

Apple:
<img width="1398" alt="Screen Shot 2021-03-05 at 9 55 20 AM" src="https://user-images.githubusercontent.com/64806657/110154347-00b0ff00-7d99-11eb-87d2-9d84fda70b94.png">

OpenStreetMap:
<img width="1680" alt="Screen Shot 2021-03-05 at 9 55 41 AM" src="https://user-images.githubusercontent.com/64806657/110154361-060e4980-7d99-11eb-86a3-8178b00ea106.png">


Proposed Changes:
name from Akureyi to Akureyri
nameascii from Akureyi to Akureyri
ls_name from Akureyi to Akureyri

**Comment by nvkelso** [comment]
Landscan name is a data join unique ID to internal dataset (look in 10_cultural) so shouldn’t change.

Good on the rest!

**Comment by mizmay** [comment]
Same, same https://gist.github.com/mizmay/89f6eed0e571e5e324bb7e13005715fc :)

**Comment by nvkelso** [comment]
**name** = `Akureyri` (from `Akureyi`)
**nameascii** = `Akureyri` (from `Akureyi`)

**Comment by mizmay** [comment]
Verified LS_NAME is still "Akureyi". Full output after change:

|values             |ind        |
|:------------------|:----------|
|6                  |SCALERANK  |
|30                 |NATSCALE   |
|8                  |LABELRANK  |
|Admin-1 capital    |FEATURECLA |
|Akureyri           |NAME       |
|NA                 |NAMEPAR    |
|NA                 |NAMEALT    |
|Akureyri           |NAMEASCII  |
|0                  |ADM0CAP    |
|NA                 |CAPIN      |
|0                  |WORLDCITY  |
|0                  |MEGACITY   |
|Iceland            |SOV0NAME   |
|ISL                |SOV_A3     |
|Iceland            |ADM0NAME   |
|ISL                |ADM0_A3    |
|Akureyri           |ADM1NAME   |
|IS                 |ISO_A2     |
|NA                 |NOTE       |
|65.6665719         |LATITUDE   |
|-18.1000169        |LONGITUDE  |
|16563              |POP_MAX    |
|12945              |POP_MIN    |
|0                  |POP_OTHER  |
|6                  |RANK_MAX   |
|6                  |RANK_MIN   |
|NA                 |MEGANAME   |
|Akureyi            |LS_NAME    |
|12945              |MAX_POP10  |
|0                  |MAX_POP20  |
|0                  |MAX_POP50  |
|0                  |MAX_POP300 |
|0                  |MAX_POP310 |
|10                 |MAX_NATSCA |
|10                 |MIN_AREAKM |
|10                 |MAX_AREAKM |
|4                  |MIN_AREAMI |
|4                  |MAX_AREAMI |
|23                 |MIN_PERKM  |
|23                 |MAX_PERKM  |
|14                 |MIN_PERMI  |
|14                 |MAX_PERMI  |
|-18.15             |MIN_BBXMIN |
|-18.15             |MAX_BBXMIN |
|-18.075            |MIN_BBXMAX |
|-18.075            |MAX_BBXMAX |
|65.658333          |MIN_BBYMIN |
|65.658333          |MAX_BBYMIN |
|65.7               |MIN_BBYMAX |
|65.7               |MAX_BBYMAX |
|-18.108477         |MEAN_BBXC  |
|65.683477          |MEAN_BBYC  |
|Atlantic/Reykjavik |TIMEZONE   |
|0                  |UN_FID     |
|0                  |POP1950    |
|0                  |POP1955    |
|0                  |POP1960    |
|0                  |POP1965    |
|0                  |POP1970    |
|0                  |POP1975    |
|0                  |POP1980    |
|0                  |POP1985    |
|0                  |POP1990    |
|0                  |POP1995    |
|0                  |POP2000    |
|0                  |POP2005    |
|0                  |POP2010    |
|0                  |POP2015    |
|0                  |POP2020    |
|0                  |POP2025    |
|0                  |POP2050    |
|6                  |MIN_ZOOM   |
|Q29042             |WIKIDATAID |
|101751757          |WOF_ID     |
|0                  |CAPALT     |
|Akureyri           |NAME_EN    |
|Akureyri           |NAME_DE    |
|Akureyri           |NAME_ES    |
|Akureyri           |NAME_FR    |
|Akureyri           |NAME_PT    |
|Акюрейри           |NAME_RU    |
|阿克雷里           |NAME_ZH    |
|NA                 |LABEL      |
|NA                 |NAME_AR    |
|NA                 |NAME_BN    |
|NA                 |NAME_EL    |
|NA                 |NAME_HI    |
|NA                 |NAME_HU    |
|NA                 |NAME_ID    |
|NA                 |NAME_IT    |
|NA                 |NAME_JA    |
|NA                 |NAME_KO    |
|NA                 |NAME_NL    |
|NA                 |NAME_PL    |
|NA                 |NAME_SV    |
|NA                 |NAME_TR    |
|NA                 |NAME_VI    |
|1159147673         |NE_ID      |

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
