### ISSUE TITLE
10m places: Novi Sad (Vojvodina, Serbia) is Admin-1 capital

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#367]
In the 10m places dataset, Novi Sad (Vojvodina, Serbia, Europe) is listed as Admin-0 capital, but it is actually an Admin-1 capital. https://en.wikipedia.org/wiki/Vojvodina

**Comment by nvkelso** [comment]
Closing as not to be fixed.

The current **featurecla** of `Admin-0 region capital` reflects it's status as capital of the admin-0 region of `Autonomous Province of Vojvodina`, one of the two regions of Serbia that sit above the province level. Often region capitals are also province capitals, but the higher order wins for the single feature class status.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
