### ISSUE TITLE
10m places: Patra (Dytiki Ellada, Greece) is an Admin-1 capital

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#368]
In the 10m places dataset, Patra (Dytiki Ellada, Greece) is listed as "Ppopulated place"; however, it is the administrative capital of Dytiki Ellada, and should therefore be listed as "Admin-1 capital".

**Comment by nvkelso** [comment]
👍

**Comment by mizmay** [comment]
Resolved with #457
