### ISSUE TITLE
10m places: misspelling of Liupanshui, Guizhou, China

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#369]
In the 10m places dataset, the city of Liupanshui (Guizhou, China) is misspelled as Lupanshui. https://en.wikipedia.org/wiki/Liupanshui

**Comment by mizmay** [comment]
Verified on Apple Maps, Google Maps and OpenStreetMap https://www.openstreetmap.org/relation/2780191

<img width="338" alt="Screen Shot 2021-04-04 at 12 50 53 PM" src="https://user-images.githubusercontent.com/3074691/113519943-8a90eb00-9544-11eb-84b8-00fb8936e2ff.png">

**Comment by mizmay** [comment]
|values          |ind        |
|:---------------|:----------|
|4               |SCALERANK  |
|50              |NATSCALE   |
|1               |LABELRANK  |
|Populated place |FEATURECLA |
|Liupanshui      |NAME       |
|NA              |NAMEPAR    |
|NA              |NAMEALT    |
|Liupanshui      |NAMEASCII  |
|0               |ADM0CAP    |
|NA              |CAPIN      |
|0               |WORLDCITY  |
|0               |MEGACITY   |
|China           |SOV0NAME   |
|CHN             |SOV_A3     |
|China           |ADM0NAME   |
|CHN             |ADM0_A3    |
|Guizhou         |ADM1NAME   |
|CN              |ISO_A2     |
|NA              |NOTE       |
|26.5963807      |LATITUDE   |
|104.8313862     |LONGITUDE  |
|1221000         |POP_MAX    |
|551512          |POP_MIN    |
|538534          |POP_OTHER  |
|12              |RANK_MAX   |
|11              |RANK_MIN   |
|Liupanshui      |MEGANAME   |
|Lupanshui       |LS_NAME    |
|551512          |MAX_POP10  |
|551512          |MAX_POP20  |
|551512          |MAX_POP50  |
|0               |MAX_POP300 |
|0               |MAX_POP310 |
|50              |MAX_NATSCA |
|300             |MIN_AREAKM |
|300             |MAX_AREAKM |
|116             |MIN_AREAMI |
|116             |MAX_AREAMI |
|317             |MIN_PERKM  |
|317             |MAX_PERKM  |
|197             |MIN_PERMI  |
|197             |MAX_PERMI  |
|104.716667      |MIN_BBXMIN |
|104.716667      |MAX_BBXMIN |
|105.291667      |MIN_BBXMAX |
|105.291667      |MAX_BBXMAX |
|26.275          |MIN_BBYMIN |
|26.275          |MAX_BBYMIN |
|26.666667       |MIN_BBYMAX |
|26.666667       |MAX_BBYMAX |
|105.010838      |MEAN_BBXC  |
|26.506234       |MEAN_BBYC  |
|NA              |TIMEZONE   |
|78              |UN_FID     |
|405             |POP1950    |
|443             |POP1955    |
|484             |POP1960    |
|530             |POP1965    |
|579             |POP1970    |
|633             |POP1975    |
|692             |POP1980    |
|757             |POP1985    |
|827             |POP1990    |
|905             |POP1995    |
|989             |POP2000    |
|1149            |POP2005    |
|1221            |POP2010    |
|1329            |POP2015    |
|1493            |POP2020    |
|1632            |POP2025    |
|1745            |POP2050    |
|5.6             |MIN_ZOOM   |
|Q485918         |WIKIDATAID |
|1141909225      |WOF_ID     |
|0               |CAPALT     |
|Liupanshui      |NAME_EN    |
|Liupanshui      |NAME_DE    |
|Liupanshui      |NAME_ES    |
|Liupanshui      |NAME_FR    |
|Liupanshui      |NAME_PT    |
|Люпаньшуй       |NAME_RU    |
|六盘水          |NAME_ZH    |
|NA              |LABEL      |
|NA              |NAME_AR    |
|NA              |NAME_BN    |
|NA              |NAME_EL    |
|NA              |NAME_HI    |
|NA              |NAME_HU    |
|NA              |NAME_ID    |
|NA              |NAME_IT    |
|NA              |NAME_JA    |
|NA              |NAME_KO    |
|NA              |NAME_NL    |
|NA              |NAME_PL    |
|NA              |NAME_SV    |
|NA              |NAME_TR    |
|NA              |NAME_VI    |
|1159149787      |NE_ID      |

**Comment by nvkelso** [comment]
Works for me.

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
