### ISSUE TITLE
10m places: Macau and Hong Kong (China) are Admin-1 capital, not Admin-0

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#371]
In the 10m places dataset, although Macau and Hong Kong (China) are special administrative regions, they are both part of the People's republic of China. They are now listed as Admin-0 capital; however, they should be listed as Admin-1 capital.

https://en.wikipedia.org/wiki/Macau
https://en.wikipedia.org/wiki/Hong_Kong

**Comment by nvkelso** [comment]
No, in Natural Earth they are both still listed 3 different countries but under the same sovereignty (China). You can argue https://en.wikipedia.org/wiki/One_country,_two_systems is no longer in force with recent events the last 12 months. But until Natural Earth changes w/r/t the countries, they should stay admin-0 capitals.
