### ISSUE TITLE
Unable to Download

### ISSUE THREAD

**Issue by andydamico** [nvkelso/natural-earth-vector#372]
I am unable to download any of the 1:10m physical vectors, specifically: http://naciscdn.org/naturalearth/10m/physical/10m_physical.zip

**Comment by mackenziejewell** [comment]
I am currently having this same issue.

**Comment by stragu** [comment]
Same here, downloads fail, with status "Couldn't connect to server". The top domain where the files are hosted can't be reached, it times out: http://naciscdn.org

**Comment by rrbuchholz** [comment]
I am also having the same issue with the 110m. It fails either via cartopy or any via https://www.naturalearthdata.com/

**Comment by nvkelso** [comment]
The files can be downloaded directly from this GitHub repo.

I’ll investigate why the website downloads aren’t working...

**Comment by stragu** [comment]
I've notified nacis.org about it a few hours ago, they replied saying they would look into it.

**Comment by conorsy** [comment]
same problem here
