### ISSUE TITLE
10m places: misspelling of Amundsen-Scott South Pole Station

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#374]
In the 10m places dataset, in Antarctica, Amundsen-Scott South Pole Station is misspelled as AmundseniScott South Pole Station.
https://en.wikipedia.org/wiki/Amundsen%E2%80%93Scott_South_Pole_Station

**Comment by nvkelso** [comment]
@mizmay can you add this one to your PR, please?

**Comment by mizmay** [comment]
Resolved with #457
