### ISSUE TITLE
10m region points: misspelling of Cabo de Sao Vicente, Portugal

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#376]
In the 10m region points dataset, Cabo de Sao Vicente (southwestern Portugal) is misspelled as Cabo de Sao Vicentete.
https://en.wikipedia.org/wiki/Cape_St._Vincent

**Comment by elliotap** [comment]
Verified

Compare to Google:
<img width="1680" alt="Screen Shot 2021-03-10 at 12 35 27 PM" src="https://user-images.githubusercontent.com/64806657/110694162-22e1bd00-819d-11eb-9400-625499375f26.png">
Apple:
<img width="1398" alt="Screen Shot 2021-03-10 at 12 34 22 PM" src="https://user-images.githubusercontent.com/64806657/110694173-26754400-819d-11eb-86b9-418fd141360f.png">
OpenStreetMap:
<img width="1680" alt="Screen Shot 2021-03-10 at 12 35 08 PM" src="https://user-images.githubusercontent.com/64806657/110694186-2b39f800-819d-11eb-9efa-3bff55f71576.png">

Proposed edits:
change name from Cabo de São Vicentete to Cabo de São Vicente
change label from Cabo de São Vicentete to Cabo de São Vicente

**Comment by nvkelso** [comment]
LGTM

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/497.
