### ISSUE TITLE
10m places: Makkah (Saudi Arabia) should be Admin-1 capital

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#377]
In the 10m places dataset, Makkah (Mecca, Saudi Arabia) is listed as a "Populated place"; however, it is the Admin-1 capital of Makkah region:
https://en.wikipedia.org/wiki/Mecca_Region

**Comment by nvkelso** [comment]
I agree with this.

For reference, the city Wikipedia page is https://en.wikipedia.org/wiki/Mecca.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
