### ISSUE TITLE
10m places: misspelling of Sevastopol, Crimea, Russia/Ukraine

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#380]
In the 10m places dataset, the Admin-1 capital of Sevastopol is misspelled as Sevastapol.
https://en.wikipedia.org/wiki/Sevastopol

**Comment by nvkelso** [comment]
@mizmay can you add this one to your PR, please?

**Comment by jwva** [comment]
Great to see all the update activity. Thank you. Much appreciated. Looking forward to the new release!

**Comment by mizmay** [comment]
Resolved with #457
