### ISSUE TITLE
10m places: Yangon, Myanmar, should be Admin-1 capital, not Admin-0

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#381]
In the 10m places data set, Rangoon (I would suggest to rename it to Yangon, the official name) is listed as one of the Admin-0 capitals of Myanmar. However, it lost that title in 2006. It is now an Admin-1 capital.
https://en.wikipedia.org/wiki/Yangon

**Comment by nvkelso** [comment]
Let's go a little slower here. While most administrative functions _have_ moved to the new capital, many of the ministry's functions still happen in the old capital and many foreign embassies are still in the old capital. 

For **ne_id** `1159151477`, **FEATURECLA** to 'Admin-1 capital alt', the default **name** value should change to `Yangon` and **name_alt** to `Rangoon` to preserve the earlier value, and **nameascii** value should change to `Yangon`.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
