### ISSUE TITLE
10m regional (elevation) geographic points: misspelling of Pico Cristóbal Colón, Colombia

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#382]
In the 10m regional geographic points, the mountain called Pico Cristóbal Colón in northern Colombia is misspelled as Pico Cristobol Colón.
https://en.wikipedia.org/wiki/Pico_Crist%C3%B3bal_Col%C3%B3n

**Comment by elliotap** [comment]
Confirmed

Compare to Apple:
<img width="1398" alt="Screen Shot 2021-03-10 at 10 01 31 AM" src="https://user-images.githubusercontent.com/64806657/110675379-aabccc80-8187-11eb-810e-9d13275af128.png">

Google:
<img width="1680" alt="Screen Shot 2021-03-10 at 10 00 49 AM" src="https://user-images.githubusercontent.com/64806657/110675394-ae505380-8187-11eb-8426-d295b82e3a68.png">

2008 Shaded Relief from Perry-Castañeda Library Map Collection (https://legacy.lib.utexas.edu/maps/colombia.html)
![txu-oclc-192062534-columbia_rel_2008](https://user-images.githubusercontent.com/64806657/110676621-03d93000-8189-11eb-831f-9273a5fa04a6.jpg)

Also, very neat photo series of the place in this trip report by a mountain climber: http://www.ii.uib.no/~petter/mountains/5000mtn/Cristobal/Trip-report.html

Proposed Changes:
same as jwva's proposal
change name value from Pico Cristóbol Colón to Pico Cristóbal Colón

**Comment by nvkelso** [comment]
Sounds good to me!

Fun photos, thanks for sharing :)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/497.
