### ISSUE TITLE
10m places: Shijiazhuang, China, should be Admin-1 capital

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#383]
In the 10m places dataset, Shijiazhuang is listed as type "Populated place". However, it is the capital of the Hebei province, and therefore should be listed as Admin-1 capital.
https://en.wikipedia.org/wiki/Shijiazhuang

**Comment by mizmay** [comment]
As described in #430 there is a discrepancy between the spelling in Natural Earth NAME field ("Shijianzhuang") and Wikidata ("Shijiazhuang").

**Comment by nvkelso** [comment]
Agree the fix is to update the **featurecla** value to `Admin-1 capital`.

Let's use the other issue to track the name change still. Both changes can be made together in the same PR.

**Comment by nvkelso** [comment]
For **ne_id** `1159149907 ` , the default **name** value should change to `Shijiazhuang` and **name_alt** to `Shimen, Shihkiachwang` to preserve the earlier value, and **nameascii** value should change to `Shijiazhuang`.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
