### ISSUE TITLE
10m places: Zhengzhou, China, should be Admin-1 capital

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#384]
In the 10m places dataset, Zhengzhou (China) is listed as type "Populated place". However, it is the capital of the Henan province of China. It should therefore be listed as "Admin-1 capital". Also, its population is now over 5 million people.
https://en.wikipedia.org/wiki/Zhengzhou

**Comment by nvkelso** [comment]
I agree with this fclass change.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
