### ISSUE TITLE
10m places: Lagos, Nigeria, Africa should not be an Admin-0 capital

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#385]
In the 10m places dataset, Lagos (Nigeria, Africa) is listed as Admin-0 capital. However, the capital of Nigeria is Abuja. It is the capital of Lagos State within Nigeria. It should therefore be listed as Admin-1 capital.

**Comment by nvkelso** [comment]
Huh, Is there note in the admin cap notes field about why it might have been marked thus? Agree with change.

**Comment by jwva** [comment]
Hi,

 

Unfortunately not. The available filled-in note text says “Location adjusted. Changed scale rank.”

 

Btw great to experience you back again. I hope things are quieting down a bit for you.

 

Regards,

JWvA

**Comment by nvkelso** [comment]
I agree with this change. It has all 3 branches of gov't now.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
