### ISSUE TITLE
10m places: Tomakomai (Hokkadio, Japan) is not an Admin-1 capital

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#387]
In the 10m places dataset, both Sapporo and Tomakomai are listed as Admin-1 capital of the Hokkaido Prefecture in Japan. However, Sapporo is the Admin-1 capital. Tomakomai should therefore be listed as "Populated place". 
https://en.wikipedia.org/wiki/Tomakomai,_Hokkaido

**Comment by nvkelso** [comment]
Agree with this.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
