### ISSUE TITLE
10m places: Kyoto (Japan) is not the Admin-0 capital

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#388]
In the 10m places dataset, Kyoto (Japan) is listed as an Admin-0 capital, as is Tokyo. However, although Kyoto is considered to be the cultural capital of Japan, Tokyo is the only administrative country capital. As Kyoto is the capital of the Kyoto prefecture, it should be listed as Admin-1 capital.
https://en.wikipedia.org/wiki/Kyoto

**Comment by nvkelso** [comment]
I suppose we can make all the **FCLASS** variants `Admin-1 capital`... but in Natural Earth-isms the default **FEATURELCA** should not be changed from `Admin-0 capital alt`.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
