### ISSUE TITLE
10m places: Dar es Salaam (Tanzania) is not the Admin-0 capital

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#389]
In the 10m places dataset, both Dar es Salaam and Dodoma are listed as Admin-0 capital of Tanzania, with Dar es Salaam as the "de facto" capital. However, according to Wikipedia, Dodoma is the sole Admin-0 capital of Tanzania. Therefore, Dar es Salaam should be listed as Admin-1 capital.
https://en.wikipedia.org/wiki/Dar_es_Salaam

**Comment by nvkelso** [comment]
I disagree with this.

Instead the **FEATURECLA** should be `Admin-0 capital alt`. There are still national gov't operations here.

But it must be paired with **ne_id** of `1159149731` to **FEATURECLA** of `Admin-0 capital`. The official capital has been moving here from the 1970s... but it's been slow going but seems mostly completed.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
