### ISSUE TITLE
2019 reorganization of Indian states and union territories

### ISSUE THREAD

**Issue by Nate-Wessel** [nvkelso/natural-earth-vector#393]
These two Indian union territories 
* [Dadra and Nagar Haveli](https://en.wikipedia.org/wiki/Dadra_and_Nagar_Haveli)
* [Daman and Diu](https://en.wikipedia.org/wiki/Daman_and_Diu)

were merged in 2019 to create a single entity called [Dadra and Nagar Haveli and Daman and Diu](https://en.wikipedia.org/wiki/Dadra_and_Nagar_Haveli_and_Daman_and_Diu)

Also in 2019, the state of Jammu and Kashmir was split into two union territories:
* [Jammu and Kashmir](https://en.wikipedia.org/wiki/Jammu_and_Kashmir_(union_territory))
* [Ladakh](https://en.wikipedia.org/wiki/Ladakh)

See https://en.wikipedia.org/wiki/Jammu_and_Kashmir_Reorganisation_Act,_2019

**Comment by elliotap** [comment]
Ladakh - Verified, see https://ladakh.nic.in/

Compare to Google:
<img width="1680" alt="Screen Shot 2021-03-23 at 12 39 55 PM" src="https://user-images.githubusercontent.com/64806657/112216020-47e32080-8bde-11eb-84d5-d01a21faba27.png">

OSM:
<img width="1680" alt="Screen Shot 2021-03-23 at 12 39 29 PM" src="https://user-images.githubusercontent.com/64806657/112216042-4ca7d480-8bde-11eb-9107-2c0d70022340.png">

Create new admin-1 feature for Ladakh, wikidataid=Q200667

Create new admin-1 capital feature in populated places for Leh (https://en.wikipedia.org/wiki/Leh) at 34.16466,77.58355, with wikidataid=Q230818
Ladakh has two seats, Leh is the larger of the two (30k population vs 16k for Kargil)

<img width="1792" alt="Screen Shot 2021-03-23 at 12 42 25 PM" src="https://user-images.githubusercontent.com/64806657/112216085-57626980-8bde-11eb-9c05-59584f35b4a3.png">

**Comment by nvkelso** [comment]
Process detailed in https://github.com/nvkelso/natural-earth-vector/issues/396#issuecomment-789428141.

**Comment by nvkelso** [comment]
The line and polygon work was completed in https://github.com/nvkelso/natural-earth-vector/pull/524.

But the new capital still needs to be added for Ladakh so keeping this open.

**Comment by nvkelso** [comment]
Added **Leh** (new capital of Ladakh) via 10daca906f6dbc90eee990d6cd9f74f4c69ad5b9.

![image](https://user-images.githubusercontent.com/853051/116350336-9fa91480-a7a6-11eb-9de0-5abdab4c47f7.png)
