### ISSUE TITLE
Rename Indian state Orissa -> Odisha

### ISSUE THREAD

**Issue by Nate-Wessel** [nvkelso/natural-earth-vector#394]
This was changed by the legislature in 2010. See: https://en.wikipedia.org/wiki/Odisha#Etymology

**Comment by elliotap** [comment]
Verified -  https://www.indiacode.nic.in/bitstream/123456789/2108/1/A2011-15.pdf

Compare to Apple:
<img width="1398" alt="Screen Shot 2021-03-18 at 3 32 14 PM" src="https://user-images.githubusercontent.com/64806657/111706274-3cb77b80-87ff-11eb-9ca7-8631874e7bec.png">

Google:
<img width="1680" alt="Screen Shot 2021-03-18 at 3 32 56 PM" src="https://user-images.githubusercontent.com/64806657/111706276-3f19d580-87ff-11eb-8084-ce1d89d10df5.png">

OSM:
<img width="1680" alt="Screen Shot 2021-03-18 at 3 32 41 PM" src="https://user-images.githubusercontent.com/64806657/111706285-4214c600-87ff-11eb-9ca2-b0b0d314b23d.png">

Proposed edits
for feature with ne_id=1159311885 :
Change name from Orissa to Odisha
Change namealt from Odisha to Orissa

**Comment by nvkelso** [comment]
Sounds good to me, thanks!

**Comment by nvkelso** [comment]
Process is detailed in https://github.com/nvkelso/natural-earth-vector/issues/396#issuecomment-789428141.

**Comment by nvkelso** [comment]
![image](https://user-images.githubusercontent.com/853051/115822380-50836e00-a3b9-11eb-9861-d75843f3bc0f.png)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/522.
