### ISSUE TITLE
Rename Indian state Uttaranchal -> Uttarakhand

### ISSUE THREAD

**Issue by Nate-Wessel** [nvkelso/natural-earth-vector#395]
Officially renamed in 2006. See https://en.wikipedia.org/wiki/Uttarakhand#Etymology

**Comment by elliotap** [comment]
Verified - see https://legislative.gov.in/sites/default/files/A2006-52.pdf

Compare to Google:
<img width="1680" alt="Screen Shot 2021-03-18 at 2 44 50 PM" src="https://user-images.githubusercontent.com/64806657/111701861-aa13de00-87f8-11eb-9f0f-47bda52dc7ea.png">

Apple:
<img width="1398" alt="Screen Shot 2021-03-18 at 2 46 21 PM" src="https://user-images.githubusercontent.com/64806657/111701896-b861fa00-87f8-11eb-95a1-03dcf1dd9a09.png">

OSM:
<img width="1680" alt="Screen Shot 2021-03-18 at 2 45 20 PM" src="https://user-images.githubusercontent.com/64806657/111701904-bbf58100-87f8-11eb-9284-6f2855765bd8.png">

Proposed edits:
for feature with ne_id=1159314161
change name from Uttaranchal to Uttarakhand
change namealt from Uttarakhand to Uttaranchal

**Comment by nvkelso** [comment]
Works for me, thanks!

**Comment by nvkelso** [comment]
This will be a change to the housekeeping admin-1-details DBF, then a mapshaper Make command to regenerate the labeled admin-1 polygons.

**Comment by nvkelso** [comment]
![image](https://user-images.githubusercontent.com/853051/115822493-7ad52b80-a3b9-11eb-881c-20ad6123a072.png)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/522.
