### ISSUE TITLE
Misspelling of island polygon feature "Ryükyü Islands"

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#397]
The island polygon feature of "Ryükyü Islands" southwest of Japan is misspelled as "Ryükyü Isands" in the data.

**Comment by elliotap** [comment]
Verified - https://en.wikipedia.org/wiki/Ryukyu_Islands

compare to OSM:
<img width="1680" alt="Screen Shot 2021-03-18 at 12 39 10 PM" src="https://user-images.githubusercontent.com/64806657/111686990-ffdf8a80-87e6-11eb-8b8f-3479af75b6a8.png">


Proposed edits:
For feature with ne_id=1159103819 in ne_10m_geography_regions_polys:
change name from RYÜKYÜ ISANDS to Ryükyü Islands
change label from RYÜKYÜ ISANDS to Ryükyü Islands
add namealt of Nansei Islands (https://en.wikipedia.org/wiki/Ryukyu_Islands#Names_and_extents | https://ja.wikipedia.org/wiki/%E5%8D%97%E8%A5%BF%E8%AB%B8%E5%B3%B6)

**Comment by nvkelso** [comment]
Adding the missing `L` sounds good to me, as well as the **namealt**. But let's keep the CASING the same to match other features. Maybe they should all be Title Case... but they were optimized for labeling on maps so let's keep the consistency for now.

For feature with **ne_id**=`1159103819` in _ne_10m_geography_regions_polys_ theme:

- **name** to `RYÜKYÜ ISLANDS` (from `RYÜKYÜ ISANDS`)
- **label** to `RYÜKYÜ ISLANDS` (from `RYÜKYÜ ISANDS`)
- **namealt** to `Nansei Islands`

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/505.
