### ISSUE TITLE
Places: Ujungpandang, Indonesia, is now Makassar

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#398]
In the Places table, the populated place of Ujungpandang (Sulawesi, Indonesia) is officially called Makassar since 1999. In addition, it is not only a "Populated place", it is the "Admin-1 capital" of South Sulawesi.
https://en.wikipedia.org/wiki/Makassar

**Comment by elliotap** [comment]
Verified - wikipedia indicates name was changed to Makassar in 1999
Indonesian name is Kota Makassar (https://id.wikipedia.org/wiki/Kota_Makassar)

Compare to Google:
<img width="1680" alt="Screen Shot 2021-03-04 at 3 59 13 PM" src="https://user-images.githubusercontent.com/64806657/110047350-951c5280-7d02-11eb-849a-ba66ad58acdb.png">

Apple:
<img width="1398" alt="Screen Shot 2021-03-04 at 4 00 45 PM" src="https://user-images.githubusercontent.com/64806657/110047469-cbf26880-7d02-11eb-8059-1305e99e742d.png">

OpenStreetMap:
<img width="1680" alt="Screen Shot 2021-03-04 at 4 01 16 PM" src="https://user-images.githubusercontent.com/64806657/110047514-df053880-7d02-11eb-998e-57283d058c3b.png">

Proposed edits:
featurecla from Populated place to Admin-1 capital
name from Ujungpandang to Makassar
namealt from Ujung Pandang to Kota Makassar
nameascii from Ujungpandang to Makassar
meganame from Ujung Pandang to Makassar
ls_name from Ujungpandang to Makassar

edits in 10m & 50m populated places

**Comment by mizmay** [comment]
Happy to pick this one up too @elliotap!

**Comment by nvkelso** [comment]
Only the 10m file needs to be updated as follows (with my modifications):

- **featurecla** to `Admin-1 capital` (from `Populated place`)
- **name** to `Makassar` (from `Ujungpandang`)
- **namealt** to `Kota Makassar|Ujung Pandang`
- **nameascii** to `Makassar` (from `Ujungpandang`)

Please don't change 

- **meganame**
- **ls_name**

**Comment by mizmay** [comment]
|values                           |ind        |
|:--------------------------------|:----------|
|3                                |SCALERANK  |
|110                              |NATSCALE   |
|1                                |LABELRANK  |
|Admin-1 capital                  |FEATURECLA |
|Makassar                         |NAME       |
|NA                               |NAMEPAR    |
|Kota Makassar&#124;Ujung Pandang |NAMEALT    |
|Makassar                         |NAMEASCII  |
|0                                |ADM0CAP    |
|NA                               |CAPIN      |
|0                                |WORLDCITY  |
|1                                |MEGACITY   |
|Indonesia                        |SOV0NAME   |
|IDN                              |SOV_A3     |
|Indonesia                        |ADM0NAME   |
|IDN                              |ADM0_A3    |
|Sulawesi Selatan                 |ADM1NAME   |
|ID                               |ISO_A2     |
|NA                               |NOTE       |
|-5.138013                        |LATITUDE   |
|119.4300817                      |LONGITUDE  |
|1262000                          |POP_MAX    |
|1262000                          |POP_MIN    |
|2085674                          |POP_OTHER  |
|12                               |RANK_MAX   |
|12                               |RANK_MIN   |
|Ujung Pandang                    |MEGANAME   |
|Ujungpandang                     |LS_NAME    |
|2133664                          |MAX_POP10  |
|2137598                          |MAX_POP20  |
|2134816                          |MAX_POP50  |
|2136185                          |MAX_POP300 |
|0                                |MAX_POP310 |
|100                              |MAX_NATSCA |
|1604                             |MIN_AREAKM |
|1686                             |MAX_AREAKM |
|619                              |MIN_AREAMI |
|651                              |MAX_AREAMI |
|1282                             |MIN_PERKM  |
|1312                             |MAX_PERKM  |
|797                              |MIN_PERMI  |
|815                              |MAX_PERMI  |
|119.358333                       |MIN_BBXMIN |
|119.358333                       |MAX_BBXMIN |
|119.908333                       |MIN_BBXMAX |
|119.908333                       |MAX_BBXMAX |
|-5.7                             |MIN_BBYMIN |
|-5.7                             |MAX_BBYMIN |
|-4.933333                        |MIN_BBYMAX |
|-4.933333                        |MAX_BBYMAX |
|119.595958                       |MEAN_BBXC  |
|-5.378118                        |MEAN_BBYC  |
|Asia/Makassar                    |TIMEZONE   |
|288                              |UN_FID     |
|223                              |POP1950    |
|283                              |POP1955    |
|361                              |POP1960    |
|399                              |POP1965    |
|418                              |POP1970    |
|502                              |POP1975    |
|629                              |POP1980    |
|719                              |POP1985    |
|816                              |POP1990    |
|926                              |POP1995    |
|1051                             |POP2000    |
|1194                             |POP2005    |
|1262                             |POP2010    |
|1374                             |POP2015    |
|1559                             |POP2020    |
|1713                             |POP2025    |
|1837                             |POP2050    |
|5                                |MIN_ZOOM   |
|Q14634                           |WIKIDATAID |
|102018665                        |WOF_ID     |
|0                                |CAPALT     |
|Makassar                         |NAME_EN    |
|Makassar                         |NAME_DE    |
|Macasar                          |NAME_ES    |
|Makassar                         |NAME_FR    |
|Macáçar                          |NAME_PT    |
|Макасар                          |NAME_RU    |
|望加錫                           |NAME_ZH    |
|NA                               |LABEL      |
|NA                               |NAME_AR    |
|NA                               |NAME_BN    |
|NA                               |NAME_EL    |
|NA                               |NAME_HI    |
|NA                               |NAME_HU    |
|NA                               |NAME_ID    |
|NA                               |NAME_IT    |
|NA                               |NAME_JA    |
|NA                               |NAME_KO    |
|NA                               |NAME_NL    |
|NA                               |NAME_PL    |
|NA                               |NAME_SV    |
|NA                               |NAME_TR    |
|NA                               |NAME_VI    |
|1159150843                       |NE_ID      |

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
