### ISSUE TITLE
Wrong name_en value for Puebla, Mexico

### ISSUE THREAD

**Issue by almccon** [nvkelso/natural-earth-vector#399]
For the city of Puebla, the `name_en` field has "Puebla Garcia" but I can find no other references to this being the preferred name of the city in English, nor any references to that as an alternate name. Neither Wikipedia nor OpenStreetMap show "Puebla Garcia" as an alternate name for Puebla.

![Screen Shot 2020-08-18 at 4 41 12 PM](https://user-images.githubusercontent.com/1212178/90565100-582cac00-e174-11ea-831e-9e15610e112a.png)

**Comment by nvkelso** [comment]
This is pulled from Wikidata. Once it's fixed there, the next script run & Natural Earth release would pick it up.

**Comment by almccon** [comment]
Ok, great. It looks like it was fixed in Wikidata on 15 October 2018: https://www.wikidata.org/w/index.php?title=Q125293&type=revision&diff=764573387

And the error was introduced by an anonymous editor on 21 April 2018: https://www.wikidata.org/w/index.php?title=Q125293&type=revision&diff=667550857

**Comment by nvkelso** [comment]
It'll say `Puebla City` per latest Wikidata run:

![image](https://user-images.githubusercontent.com/853051/126100593-6dc1684a-af76-47a3-b5f2-ecc02983b085.png)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/446.

@almccon note that the last commits in that PR sideloads translations for 100% coverage of populated places and admin-0 features (beyond what's in Wikidata).
