### ISSUE TITLE
Not able to find United States of America in the 10m Countries and State maps

### ISSUE THREAD

**Issue by rajmohan006** [nvkelso/natural-earth-vector#400]
Not able to find United States of America in the 10m Countries and State maps

**Comment by nvkelso** [comment]
What webpage and/or file are you looking for the USA in?

**Comment by rajmohan006** [comment]
I downloaded the "ne_10m_admin_0_countries.zip" file and then trying to create a map for US only in the mapbox website. If i go to the filter to create a filter on the country name, i do not find USA or Canada in the list.

**Comment by nvkelso** [comment]
I'm still not following. Can you include screenshot and reproduction steps, please?

**Comment by rajmohan006** [comment]
![image](https://user-images.githubusercontent.com/48454634/90821772-10835d00-e2f9-11ea-85dd-f544c53b3e41.png)

Please see the enclosed image where i am trying to add filter for United States but it does not show it in the list of available options.

**Comment by nvkelso** [comment]
The feature is there in the preview map. Please followup directly with Mapbox Support, sounds like oddness in their software.
