### ISSUE TITLE
Improper map of Ukraine

### ISSUE THREAD

**Issue by rshopa** [nvkelso/natural-earth-vector#401]
I redirect the [issue](https://github.com/Nowosad/spData/issues/50) about Crimea being treated not as a part of Ukraine, but Russia. This is [not recognised by UN](https://undocs.org/en/A/RES/68/262) and the peninsula is officially considered Ukrainian [by the US govermnent](https://www.state.gov/crimea-is-ukraine-3/) as well, thus ought to be corrected here. 

Since most of Map Update Committee reside in the US, I hope there will be no obstacles when it comes to the correction.

**Comment by matkoniecz** [comment]
Sadly, Crimea was successfully invaded and taken over by Russia.

See https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-details/

> Disclaimer

> Natural Earth Vector draws boundaries of sovereign states according to defacto status. We show who actually controls the situation on the ground. For instance, we show China and Taiwan as two separate states. But we show Palestine as part of Israel. Please feel free to mashup our countries and disputed areas themes to match your particular political outlook.

**Comment by nvkelso** [comment]
Addressed via https://github.com/nvkelso/natural-earth-vector/pull/446, via point-of-view options.
