### ISSUE TITLE
India-Pakistan frontier issue

### ISSUE THREAD

**Issue by databayou** [nvkelso/natural-earth-vector#403]
I used ne_10m_admin_0_countries shapefiles to make the following map on tiger habitat: https://databayou.com/tiger/habitat.html. I got a response from a user saying "Indian territory of Jammu & Kashmir, Ladkah regions are shown as part of Pakistan, Which is incorrect." I trust your data, but how can I support this political boundary? I appreciate your help!

**Comment by nvkelso** [comment]
You can selectively load and filter boundaries and disputed boundaries by adding the “disputed” admin-0 boundaries theme as well.

**Comment by databayou** [comment]
Thank you!
