### ISSUE TITLE
10m populated places: Bose matched incorrectly to wikidata

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#406]
Bose (also known as Baise) (ID:1159149783) is matched incorrectly to wikidata, causing discrepancies in name values.

Currently the record is matched to https://www.wikidata.org/wiki/Q92381 - the correct match is to https://www.wikidata.org/wiki/Q571949

**Comment by nvkelso** [comment]
For **ne_id** `1159149783` , the default **name** value should change to `Baise` and **name_alt** to `Bose` to preserve the earlier value, and **nameascii** value should change to `Baise`.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
