### ISSUE TITLE
10m populated places: large city Nnewi missing from data set

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#407]
Nnewi, Nigeria (population ~390k) is not present in 10m populated places dataset. Requesting it be considered for inclusion at 6.016667, 6.916667

https://en.wikipedia.org/wiki/Nnewi

**Comment by nvkelso** [comment]
Wikipedia says: `Settled in 1477`! Agree it should be included.

**Comment by mizmay** [comment]
@nvkelso notes in #457 that this is only partially resolved by adding the wikidataid - need to set NAME and NAMEASCII

**Comment by nvkelso** [comment]
Fixed via #457.

**Comment by nvkelso** [comment]
And later commit ed1af2bee0c5c54a4eacae8592bb2dd70aa1a717 addresses the NAME and NAMEASCII and other properties.
