### ISSUE TITLE
10m populated places: request for location adjustments

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#409]
Requesting adjustment to point location for several populated places:

Tizi Ouzou (ID:1159120991) - closer to 36.716667, 4.05 (https://en.wikipedia.org/wiki/Tizi_Ouzou)
Bordj Bou Arréridj (ID:1159121009) - closer to 36.066667, 4.766667 (https://en.wikipedia.org/wiki/Bordj_Bou_Arr%C3%A9ridj)
Paro (ID:1159121163) - closer to 27.433333, 89.416667 (https://en.wikipedia.org/wiki/Paro,_Bhutan)
Punakha (ID:1159121181) - closer to 27.58405,89.85888 (https://en.wikipedia.org/wiki/Punakha - wikipedia lat/long is incorrect but describes location at confluence of rivers)

**Comment by elliotap** [comment]
Tizi Ouzou - Confirmed

Compare to Google:
<img width="1150" alt="Screen Shot 2021-03-05 at 11 37 14 AM" src="https://user-images.githubusercontent.com/64806657/110165092-3c52c580-7da7-11eb-86c2-6b458e9e0b6b.png">

OpenStreetMap:
<img width="1149" alt="Screen Shot 2021-03-05 at 11 37 27 AM" src="https://user-images.githubusercontent.com/64806657/110165118-470d5a80-7da7-11eb-9a59-0f38c582b79e.png">

Proposed Edits:
Move feature geometry to 36.71171010419398, 4.046144384832763
Update latitude field to 36.71171010419398
Update longitude field to 4.046144384832763

edits in 10m populated places

**Comment by elliotap** [comment]
Bordj Bou Arréridj - Confirmed

Compare to Google:
<img width="1146" alt="Screen Shot 2021-03-05 at 10 46 45 AM" src="https://user-images.githubusercontent.com/64806657/110165345-a9665b00-7da7-11eb-9580-2564eb73090e.png">

OpenStreetMap:
<img width="1149" alt="Screen Shot 2021-03-05 at 10 46 31 AM" src="https://user-images.githubusercontent.com/64806657/110165371-b125ff80-7da7-11eb-85bd-c88f902c0c1b.png">

Proposed Edits:
Move feature geometry to 36.0777087709298, 4.764662418424167
Update latitude field to 36.0777087709298
Update longitude field to 4.764662418424167

edits in 10m populated places

**Comment by elliotap** [comment]
Paro - Confirmed

Compare to Google:
<img width="1143" alt="Screen Shot 2021-03-05 at 11 44 43 AM" src="https://user-images.githubusercontent.com/64806657/110165767-3d382700-7da8-11eb-90fd-14507c90cc59.png">

OpenStreetMap:
<img width="1147" alt="Screen Shot 2021-03-05 at 11 45 02 AM" src="https://user-images.githubusercontent.com/64806657/110165790-46c18f00-7da8-11eb-884f-374be579c7d2.png">

Proposed Edits:
Move feature geometry to 27.429370409026664, 89.41677727346396
Update latitude field to 27.429370409026664
Update longitude field to 89.41677727346396

edits in 10m populated places

**Comment by nvkelso** [comment]
LGTM

**Comment by elliotap** [comment]
Punakha - Confirmed

Compare to Google:
<img width="1142" alt="Screen Shot 2021-03-05 at 11 53 17 AM" src="https://user-images.githubusercontent.com/64806657/110166570-6c9b6380-7da9-11eb-8585-3bcc11f3708a.png">

OpenStreetMap (see also https://www.openstreetmap.org/way/424947269#map=14/27.5917/89.8632):
<img width="1148" alt="Screen Shot 2021-03-05 at 11 53 28 AM" src="https://user-images.githubusercontent.com/64806657/110166597-745b0800-7da9-11eb-97c9-b747b65ab42e.png">

Proposed Edits:
Move feature geometry to 27.584154007007985, 89.86413465881778
Update latitude field to 27.584154007007985
Update longitude field to 89.86413465881778

edits in 10m populated places

**Comment by nvkelso** [comment]
Research complete, over @mizmay for PR making...

**Comment by mizmay** [comment]
| SCALERANK| NATSCALE| LABELRANK|FEATURECLA      |NAME               |NAMEPAR |NAMEALT |NAMEASCII          | ADM0CAP|CAPIN | WORLDCITY| MEGACITY|SOV0NAME |SOV_A3 |ADM0NAME |ADM0_A3 |ADM1NAME           |ISO_A2 |NOTE | LATITUDE| LONGITUDE| POP_MAX| POP_MIN| POP_OTHER| RANK_MAX| RANK_MIN|MEGANAME |LS_NAME | MAX_POP10| MAX_POP20| MAX_POP50| MAX_POP300| MAX_POP310| MAX_NATSCA| MIN_AREAKM| MAX_AREAKM| MIN_AREAMI| MAX_AREAMI| MIN_PERKM| MAX_PERKM| MIN_PERMI| MAX_PERMI| MIN_BBXMIN| MAX_BBXMIN| MIN_BBXMAX| MAX_BBXMAX| MIN_BBYMIN| MAX_BBYMIN| MIN_BBYMAX| MAX_BBYMAX| MEAN_BBXC| MEAN_BBYC|TIMEZONE | UN_FID| POP1950| POP1955| POP1960| POP1965| POP1970| POP1975| POP1980| POP1985| POP1990| POP1995| POP2000| POP2005| POP2010| POP2015| POP2020| POP2025| POP2050| MIN_ZOOM|WIKIDATAID |     WOF_ID| CAPALT|NAME_EN            |NAME_DE            |NAME_ES            |NAME_FR            |NAME_PT            |NAME_RU           |NAME_ZH      |LABEL |NAME_AR |NAME_BN |NAME_EL |NAME_HI |NAME_HU |NAME_ID |NAME_IT |NAME_JA |NAME_KO |NAME_NL |NAME_PL |NAME_SV |NAME_TR |NAME_VI |      NE_ID|
|---------:|--------:|---------:|:---------------|:------------------|:-------|:-------|:------------------|-------:|:-----|---------:|--------:|:--------|:------|:--------|:-------|:------------------|:------|:----|--------:|---------:|-------:|-------:|---------:|--------:|--------:|:--------|:-------|---------:|---------:|---------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|---------:|---------:|:--------|------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|--------:|:----------|----------:|------:|:------------------|:------------------|:------------------|:------------------|:------------------|:-----------------|:------------|:-----|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|----------:|
|        10|        1|         5|Admin-1 capital |Tizi-Ouzou         |NA      |NA      |Tizi-Ouzou         |       0|NA    |         0|        0|Algeria  |DZA    |Algeria  |DZA     |Tizi Ouzou         |DZ     |NA   | 36.71171|  4.046144|  144000|  144000|         0|        9|        9|NA       |NA      |         0|         0|         0|          0|          0|          0|          0|          0|          0|          0|         0|         0|         0|         0|          0|          0|          0|          0|          0|          0|          0|          0|         0|         0|NA       |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|        7|Q277201    | 1141906187|      0|Tizi Ouzou         |Tizi Ouzou         |Tizi Ouzou         |Tizi Ouzou         |Tizi-Ouzou         |Тизи-Узу          |提济乌祖     |NA    |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159120991|
|        10|        1|         5|Admin-1 capital |Bordj Bou Arréridj |NA      |NA      |Bordj Bou Arreridj |       0|NA    |         0|        0|Algeria  |DZA    |Algeria  |DZA     |Bordj Bou Arreridj |DZ     |NA   | 36.07771|  4.764662|  140000|  129000|         0|        9|        9|NA       |NA      |         0|         0|         0|          0|          0|          0|          0|          0|          0|          0|         0|         0|         0|         0|          0|          0|          0|          0|          0|          0|          0|          0|         0|         0|NA       |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|        7|Q544733    | 1141906189|      0|Bordj Bou Arréridj |Bordj Bou Arreridj |Bordj Bou Arréridj |Bordj Bou Arreridj |Bordj Bou Arreridj |Бордж-Бу-Арреридж |布阿拉里季堡 |NA    |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159121009|
|        10|        1|         8|Admin-1 capital |Paro               |NA      |NA      |Paro               |       0|NA    |         0|        0|Bhutan   |BTN    |Bhutan   |BTN     |Thimphu            |BT     |NA   | 27.42937| 89.416777|   15000|   15000|         0|        6|        6|NA       |NA      |         0|         0|         0|          0|          0|          0|          0|          0|          0|          0|         0|         0|         0|         0|          0|          0|          0|          0|          0|          0|          0|          0|         0|         0|NA       |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|        9|Q862041    | 1141906197|      0|Paro               |Paro               |Paro               |Paro               |Paro               |Паро              |帕羅         |NA    |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159121163|
|        10|        1|         8|Admin-1 capital |Punakha            |NA      |NA      |Punakha            |       0|NA    |         0|        0|Bhutan   |BTN    |Bhutan   |BTN     |Punakha            |BT     |NA   | 27.58415| 89.864135|    5000|    5000|         0|        4|        4|NA       |NA      |         0|         0|         0|          0|          0|          0|          0|          0|          0|          0|         0|         0|         0|         0|          0|          0|          0|          0|          0|          0|          0|          0|         0|         0|NA       |      0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|       0|        7|Q826112    | 1141906199|      0|Punakha            |Punakha            |Punakha            |Punakha            |Punakha            |Пунакха           |普那卡       |NA    |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159121181|

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
