### ISSUE TITLE
Swaziland has changed there country name to - Eswatini

### ISSUE THREAD

**Issue by michaeldssnts** [nvkelso/natural-earth-vector#410]
Could you please update your dataset to reflect the latest country name for Swaziland-  It is now called Eswatini

https://www.google.com/search?gs_ssp=eJzj4tDP1TcwKzM2M2D04kgtLk8syczLBAA4cAYK&q=eswatini&oq=eswatini&aqs=chrome.1.69i57j46j69i59l2j0j69i60l2j69i61.3423j0j4&sourceid=chrome&ie=UTF-8

**Comment by nvkelso** [comment]
What version are you using, and what file?

**Comment by nvkelso** [comment]
The basic name columns needed an update, even though the translated name_* columns had (mostly) already gotten the update.

**Comment by nvkelso** [comment]
Partially addressed in 57c3d2f8a53c0ce332b1e2b26f3c442503b308ea, but needs an DBF export and Mapshaper rebuild.

**Comment by nvkelso** [comment]
![image](https://user-images.githubusercontent.com/853051/120270996-55142f80-c25f-11eb-9c84-0d679cd175a2.png)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/446.
