### ISSUE TITLE
10m places: Jinxi (Lianoning, China) is now called Huludao

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#411]
In the 10m populated places set, Jinxi (in Liaoning, China) is officially known as Huludao since 1994:
https://en.wikipedia.org/wiki/Huludao

**Comment by mizmay** [comment]
Verified!
- Comment on provenance from NE record: "Asia/Harbin Geonames ascii name + lat.d + long.d matching."
- Open Street Map https://www.openstreetmap.org/relation/2769902
- Google Maps https://www.google.com/maps/place/Huludao,+Liaoning,+China/@40.7524541,120.7084938,11z/data=!3m1!4b1!4m5!3m4!1s0x358a1fb35c71a037:0x861f2c8c205a3b70!8m2!3d40.71104!4d120.83694
- Apple Maps has both (see screenshot)

Recommendations:
- Remove record for Jinxi (there is a wikidata ID for a town in China called Jinxi, but it is in a different province Q4397942)
- Add record for Huludao (Q75379)

<img width="868" alt="Screen Shot 2020-12-19 at 9 25 20 PM" src="https://user-images.githubusercontent.com/3074691/102705844-bb247180-4240-11eb-971a-c9c38ddc2248.png">

**Comment by nvkelso** [comment]
This is for NE feature **ne_id**: `1159149137`. 
It's currently default name of `Jinxi` with localized name_en of `Lianshan`. Both are wrong.

I think keep the existing NE feature, but update the default name as recommended to `Huludao` and set Wikidata ID to `Q75379`. The next run of the wikidata name script will pick up the localizations. 

Thanks!

**Comment by mizmay** [comment]
Sounds good.

See https://github.com/nvkelso/natural-earth-vector/pull/457

Added to the list of issues that require population updates here: https://gist.github.com/mizmay/89f6eed0e571e5e324bb7e13005715fc

**Comment by nvkelso** [comment]
For **ne_id** `1159149137` , the default **name** value should change to `Huludao ` and **name_alt** to `Jinxi` to preserve the earlier value, and **nameascii** value should change to `Huludao`. The **pop_max** is `724800` and the new **pop_rank** is `11`.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
