### ISSUE TITLE
10m places: Astana (capital of Kazakhstan) is now called Nur-Sultan

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#413]
As of 2020, the name of the capital of Kazakhstan has been changed from "Astana" to "Nur-Sultan":
https://en.wikipedia.org/wiki/Nur-Sultan

**Comment by nvkelso** [comment]
@mizmay can you add this one to your PR, please?

**Comment by mizmay** [comment]
Resolved with #457

**Comment by nvkelso** [comment]
Fixed via #457.
