### ISSUE TITLE
10m places: Max_pop of Newcastle, Australia, is too high

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#414]
In the 10m places data set, Newcastle (New South Wales, Australia) is listed as having a pop_max of 1,134,616 people. However, the greater Newcastle metropolitan area only reaches 540,796, whereas the urban area proper only reaches 322,278 (2016). Please correct.
https://en.wikipedia.org/wiki/Newcastle,_New_South_Wales

**Comment by elliotap** [comment]
Verified - see: https://quickstats.censusdata.abs.gov.au/census_services/getproduct/census/2016/quickstat/UCL102004?opendocument

Not sure what attributes to change here: how have the POP_ and MAX_POP values been determined in the past?

**Comment by nvkelso** [comment]
I documented that in a comment buried in @mizmay's PR, let me make it more findable in https://github.com/nvkelso/natural-earth-vector/issues/494.

**Comment by nvkelso** [comment]
> POP_MAX - these are needed to set townspot size and label text size, for "metro area"
> POP_MIN - these are needed to set townspot size and label text size, for "incorporated area"

**Comment by nvkelso** [comment]
**POP_MAX**  = `540,796`
**POP_MIN**  = `322,278`

**Comment by mizmay** [comment]
|values           |ind        |
|:----------------|:----------|
|3                |SCALERANK  |
|110              |NATSCALE   |
|3                |LABELRANK  |
|Populated place  |FEATURECLA |
|Newcastle        |NAME       |
|NA               |NAMEPAR    |
|NA               |NAMEALT    |
|Newcastle        |NAMEASCII  |
|0                |ADM0CAP    |
|NA               |CAPIN      |
|0                |WORLDCITY  |
|0                |MEGACITY   |
|Australia        |SOV0NAME   |
|AUS              |SOV_A3     |
|Australia        |ADM0NAME   |
|AUS              |ADM0_A3    |
|New South Wales  |ADM1NAME   |
|AU               |ISO_A2     |
|NA               |NOTE       |
|-32.8453479      |LATITUDE   |
|151.8150122      |LONGITUDE  |
|540796           |POP_MAX    |
|322278           |POP_MIN    |
|0                |POP_OTHER  |
|12               |RANK_MAX   |
|10               |RANK_MIN   |
|NA               |MEGANAME   |
|Newcastle        |LS_NAME    |
|717948           |MAX_POP10  |
|1134616          |MAX_POP20  |
|273848           |MAX_POP50  |
|273848           |MAX_POP300 |
|0                |MAX_POP310 |
|100              |MAX_NATSCA |
|179              |MIN_AREAKM |
|479              |MAX_AREAKM |
|69               |MIN_AREAMI |
|185              |MAX_AREAMI |
|188              |MIN_PERKM  |
|374              |MAX_PERKM  |
|117              |MIN_PERMI  |
|233              |MAX_PERMI  |
|-1.8             |MIN_BBXMIN |
|151.566667       |MAX_BBXMIN |
|-1.451249        |MIN_BBXMAX |
|151.791667       |MAX_BBXMAX |
|-33.041667       |MIN_BBYMIN |
|54.841667        |MAX_BBYMIN |
|-32.866667       |MIN_BBYMAX |
|55.108333        |MAX_BBYMAX |
|75.048749        |MEAN_BBXC  |
|11.007107        |MEAN_BBYC  |
|Australia/Sydney |TIMEZONE   |
|0                |UN_FID     |
|0                |POP1950    |
|0                |POP1955    |
|0                |POP1960    |
|0                |POP1965    |
|0                |POP1970    |
|0                |POP1975    |
|0                |POP1980    |
|0                |POP1985    |
|0                |POP1990    |
|0                |POP1995    |
|0                |POP2000    |
|0                |POP2005    |
|0                |POP2010    |
|0                |POP2015    |
|0                |POP2020    |
|0                |POP2025    |
|0                |POP2050    |
|5                |MIN_ZOOM   |
|Q57278           |WIKIDATAID |
|101931395        |WOF_ID     |
|0                |CAPALT     |
|Newcastle        |NAME_EN    |
|Newcastle        |NAME_DE    |
|Newcastle        |NAME_ES    |
|Newcastle        |NAME_FR    |
|Newcastle        |NAME_PT    |
|Ньюкасл          |NAME_RU    |
|纽卡斯尔         |NAME_ZH    |
|NA               |LABEL      |
|NA               |NAME_AR    |
|NA               |NAME_BN    |
|NA               |NAME_EL    |
|NA               |NAME_HI    |
|NA               |NAME_HU    |
|NA               |NAME_ID    |
|NA               |NAME_IT    |
|NA               |NAME_JA    |
|NA               |NAME_KO    |
|NA               |NAME_NL    |
|NA               |NAME_PL    |
|NA               |NAME_SV    |
|NA               |NAME_TR    |
|NA               |NAME_VI    |
|1159151163       |NE_ID      |

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
