### ISSUE TITLE
natural earth zip files not downloading

### ISSUE THREAD

**Issue by jimbomcfly1998** [nvkelso/natural-earth-vector#417]
Hello, just a heads up that nothing can seem to be downloadable...

**Comment by nvkelso** [comment]
Downloads are working for me again. Can you confirm the problem has resolved for you, please?

**Comment by ianthetechie** [comment]
Still not working for me (same issue as in #416). The NACIS CDN still seems unresponsive. http://naciscdn.org/naturalearth/packages/natural_earth_vector.zip

**Comment by clkruse** [comment]
naciscdn is down for me as well. I tried yesterday and today, but with no success
