### ISSUE TITLE
10m places: Chicoutimi, Quebec, is now part of Saguenay

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#419]
In the 10m places dataset, Chicoutimi is mentioned as a Populated Place. However, this town has been incorporated in Saguenay since 2002. Its population is slightly higher than 100,000.
https://en.wikipedia.org/wiki/Saguenay,_Quebec

**Comment by mizmay** [comment]
Seems like the main issue to correct here is that Saguenay is not in the 10m places dataset.

**Comment by nvkelso** [comment]
For **ne_id** feature `1159148923`, I think rename the existing **name** (and nameascii) field to `Saguenay` as this is the center of population for the amalgamated locality and forms one of the 3 boroughs. 

No need to create a new feature.

Sounds like the population and population rank should also be updated, `144746` and then whatever the new rank would then be.

For the localized names we'd need to update the **wd_id** to `Q139229`. Then wait for new run of the script.

**Comment by nvkelso** [comment]
Looks like pop rank should be `9`, from formula here: https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-populated-places/

**Comment by mizmay** [comment]
See https://github.com/nvkelso/natural-earth-vector/pull/457

**Comment by nvkelso** [comment]
For **ne_id** `1159148923` , the default **name** value should change to `Saguenay` and **name_alt** to `Chicoutimi` to preserve the earlier value, and **nameascii** value should change to `Saguenay`. The GeoNames ID is good as-is. The **pop_max** is `144746` and the new **pop_rank** is `9`.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
