### ISSUE TITLE
10m lakes: Takijuq Lake/Napaktulik Lake

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#426]
Takijuq Lake, present in ne 10m lakes as feature 1159109029, is an outdated name for Napaktulik Lake. Requesting update to feature name.

Reference:
http://www4.rncan.gc.ca/search-place-names/unique/ea7c9b85d05211d892e2080020a0f4c9

**Comment by MrGawsome** [comment]
After doing more research, I suggest to change the name of this lake as requested. In the ne_10m_lakes shapefile, we can change the name of ne_id 1159109029 from Takijuq Lake to Napaktulik Lake and add Wikidata Q1546823 (see https://www.wikidata.org/wiki/Q1546823).  This lake isn’t in ne_50m_lakes, so no change is necessary there. This new name is supported by the below sources, and is the name used in Wikidata and OSM, further suggesting this name change is valid: 

Official lake name source: http://www4.rncan.gc.ca/search-place-names/unique/OALIK
Previously official lake source suggesting the old name is outdated: http://www4.rncan.gc.ca/search-place-names/unique/OAQCA
Canadian Encyclopedia which lists the lake’s history: https://www.thecanadianencyclopedia.ca/en/article/napaktulik-lake
Wikipedia: https://en.wikipedia.org/wiki/Napaktulik_Lake
OSM: https://www.openstreetmap.org/relation/4562442

After PRs using the ne_10m_lakes shapefile are merged, is it okay to proceed with this name change and adding Wikidata Q1546823 as described above?

**Comment by nvkelso** [comment]
For **ne_id** = `1159109029`:

- **name** = `Napaktulik`
- **name_alt** = `Takijuq|Takiyuak`
- **wikidataid** = `Q1546823`

Note removing "Lake" from all the proposed names, per Natural Earth convention for lakes and rivers. And supporting both the earlier name alts. It's not a major feature, so skip setting a parenthetical name.

Yes, let's hold editing this until the active PR on lakes is merged.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/507.
