### ISSUE TITLE
US County feature

### ISSUE THREAD

**Issue by adiku** [nvkelso/natural-earth-vector#427]
I am trying to render a population density for US at county level.

Is there a feature I can use to render US County borders and color them based on population density?

I have population & density data from US Census website www.census.gov. I tried rendering these with shapefile & giving colors for each county, but it is taking too long to render.

**Comment by nvkelso** [comment]
This data has been contributed but needs to be integrated.

**Comment by adiku** [comment]
Thanks, keep us posted on when integration is done.

**Comment by nvkelso** [comment]
Tracking this with original issue https://github.com/nvkelso/natural-earth-vector/issues/175.
