### ISSUE TITLE
Sovetskaya Gavan misspelled

### ISSUE THREAD

**Issue by Maxszik** [nvkelso/natural-earth-vector#428]
In the Populated Places datasets:

It should be Sovetskaya Gavan - not Savetskaya Gavan

**Comment by elliotap** [comment]
"Sovetskaya Gavan" consistent with wikipedia: https://en.wikipedia.org/wiki/Sovetskaya_Gavan

Google: 
<img width="1680" alt="Screen Shot 2021-03-04 at 3 10 52 PM" src="https://user-images.githubusercontent.com/64806657/110043216-e07f3280-7cfb-11eb-8b84-de6b82b8e2ae.png">

Apple:
<img width="1748" alt="Screen Shot 2021-03-04 at 3 11 48 PM" src="https://user-images.githubusercontent.com/64806657/110043270-f55bc600-7cfb-11eb-93de-221187e3b8d4.png">

OpenStreetMap:
<img width="1680" alt="Screen Shot 2021-03-04 at 3 12 31 PM" src="https://user-images.githubusercontent.com/64806657/110043336-10c6d100-7cfc-11eb-8aa4-25a677085af1.png">

Proposed edits:
- name from Savetskaya Gavan to Sovetskaya Gavan
- nameascii from Savetskaya Gavan to Sovetskaya Gavan
- ls_name from Savetskaya Gavan to Sovetskaya Gavan

edits in 10m populated places file

**Comment by mizmay** [comment]
I've looked at this one previously (before I had the ability to assign myself tasks). Recommendation matches the Wikidata, which is why I didn't correct it in the first round of edits (my initial goal was just to fix `wikidataid` if it was wrong).

More on that research: https://gist.github.com/mizmay/89f6eed0e571e5e324bb7e13005715fc

Full list of issues like this: https://github.com/mizmay/natural-earth-vector/blob/master/10m_cultural/ne_names_issues_compare_wikidata.csv

Happy to pick it up with other batch edits @elliotap , or if you want to trade!

**Comment by elliotap** [comment]
@mizmay Thank you! Chris and I have been focusing on the issues in the 5.1.0 milestone - I think I've looked at about a half dozen populated places issues so far, and was planning to clean them up in QGIS when the time was right per Nathaniel's comment in #483 - if it would be easier to fix them with your process that would be awesome!

**Comment by nvkelso** [comment]
I have no strong opinions, thanks for coordinating!

**Comment by nvkelso** [comment]
Name change proposal LGTM, except please don't change LS_NAME... that's an artifact used to link with the landscan theme.

**Comment by mizmay** [comment]
|values           |ind        |
|:----------------|:----------|
|6                |SCALERANK  |
|30               |NATSCALE   |
|2                |LABELRANK  |
|Populated place  |FEATURECLA |
|Sovetskaya Gavan |NAME       |
|NA               |NAMEPAR    |
|NA               |NAMEALT    |
|Sovetskaya Gavan |NAMEASCII  |
|0                |ADM0CAP    |
|NA               |CAPIN      |
|0                |WORLDCITY  |
|0                |MEGACITY   |
|Russia           |SOV0NAME   |
|RUS              |SOV_A3     |
|Russia           |ADM0NAME   |
|RUS              |ADM0_A3    |
|Khabarovsk       |ADM1NAME   |
|RU               |ISO_A2     |
|NA               |NOTE       |
|48.9698908       |LATITUDE   |
|140.2748897      |LONGITUDE  |
|29740            |POP_MAX    |
|26024            |POP_MIN    |
|0                |POP_OTHER  |
|7                |RANK_MAX   |
|7                |RANK_MIN   |
|NA               |MEGANAME   |
|Savetskaya Gavan |LS_NAME    |
|26024            |MAX_POP10  |
|26024            |MAX_POP20  |
|0                |MAX_POP50  |
|0                |MAX_POP300 |
|0                |MAX_POP310 |
|20               |MAX_NATSCA |
|7                |MIN_AREAKM |
|7                |MAX_AREAKM |
|3                |MIN_AREAMI |
|3                |MAX_AREAMI |
|12               |MIN_PERKM  |
|12               |MAX_PERKM  |
|8                |MIN_PERMI  |
|8                |MAX_PERMI  |
|140.275          |MIN_BBXMIN |
|140.275          |MAX_BBXMIN |
|140.308333       |MIN_BBXMAX |
|140.308333       |MAX_BBXMAX |
|48.95            |MIN_BBYMIN |
|48.95            |MAX_BBYMIN |
|48.983333        |MIN_BBYMAX |
|48.983333        |MAX_BBYMAX |
|140.292628       |MEAN_BBXC  |
|48.965705        |MEAN_BBYC  |
|Asia/Vladivostok |TIMEZONE   |
|0                |UN_FID     |
|0                |POP1950    |
|0                |POP1955    |
|0                |POP1960    |
|0                |POP1965    |
|0                |POP1970    |
|0                |POP1975    |
|0                |POP1980    |
|0                |POP1985    |
|0                |POP1990    |
|0                |POP1995    |
|0                |POP2000    |
|0                |POP2005    |
|0                |POP2010    |
|0                |POP2015    |
|0                |POP2020    |
|0                |POP2025    |
|0                |POP2050    |
|6                |MIN_ZOOM   |
|Q196374          |WIKIDATAID |
|102001543        |WOF_ID     |
|0                |CAPALT     |
|Sovetskaya Gavan |NAME_EN    |
|Sowetskaja Gawan |NAME_DE    |
|NA               |NAME_ES    |
|Sovetskaïa Gavan |NAME_FR    |
|NA               |NAME_PT    |
|Советская Гавань |NAME_RU    |
|苏维埃港         |NAME_ZH    |
|NA               |LABEL      |
|NA               |NAME_AR    |
|NA               |NAME_BN    |
|NA               |NAME_EL    |
|NA               |NAME_HI    |
|NA               |NAME_HU    |
|NA               |NAME_ID    |
|NA               |NAME_IT    |
|NA               |NAME_JA    |
|NA               |NAME_KO    |
|NA               |NAME_NL    |
|NA               |NAME_PL    |
|NA               |NAME_SV    |
|NA               |NAME_TR    |
|NA               |NAME_VI    |
|1159146767       |NE_ID      |

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
