### ISSUE TITLE
Populated_Places: Wrong Chinese names

### ISSUE THREAD

**Issue by KennethSui** [nvkelso/natural-earth-vector#430]
Shijianzhuang --> Shijiazhuang
Xiangfan --> Xiangyang

**Comment by mizmay** [comment]
The suggested correction matches the Natural Earth fields (presumably) derived from Wikidata, but not NAME or others (presumably) derived from Geonames.

**Comment by nvkelso** [comment]
Fix is to update value the default **name** field to the correct values.

**Comment by mizmay** [comment]
BEFORE:

|NAME          |NAMEPAR |NAMEALT         |NAMEASCII     |SOV0NAME |ADM0NAME |ADM1NAME |MEGANAME        |LS_NAME       |NAME_EN      |NAME_DE      |NAME_ES      |NAME_FR      |NAME_PT      |NAME_RU    |NAME_ZH |NAME_AR |NAME_BN |NAME_EL |NAME_HI |NAME_HU |NAME_ID |NAME_IT |NAME_JA |NAME_KO |NAME_NL |NAME_PL |NAME_SV |NAME_TR |NAME_VI |
|:-------------|:-------|:---------------|:-------------|:--------|:--------|:--------|:---------------|:-------------|:------------|:------------|:------------|:------------|:------------|:----------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|
|Xiangfan      |NA      |Xiangfan, Hubei |Xiangfan      |China    |China    |Hubei    |Xiangfan, Hubei |Xiangfan      |Xiangyang    |Xiangyang    |Xiangyang    |Xiangfan     |Xiangyang    |Сянъян     |襄阳    |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
|Shijianzhuang |NA      |Shijiazhuang    |Shijianzhuang |China    |China    |Hebei    |Shijiazhuang    |Shijianzhuang |Shijiazhuang |Shijiazhuang |Shijiazhuang |Shijiazhuang |Shijiazhuang |Шицзячжуан |石家庄  |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |

**Comment by mizmay** [comment]
AFTER (all fields):

| SCALERANK| NATSCALE| LABELRANK|FEATURECLA      |NAME         |NAMEPAR |NAMEALT       |NAMEASCII    | ADM0CAP|CAPIN | WORLDCITY| MEGACITY|SOV0NAME |SOV_A3 |ADM0NAME |ADM0_A3 |ADM1NAME |ISO_A2 |NOTE | LATITUDE| LONGITUDE| POP_MAX| POP_MIN| POP_OTHER| RANK_MAX| RANK_MIN|MEGANAME        |LS_NAME       | MAX_POP10| MAX_POP20| MAX_POP50| MAX_POP300| MAX_POP310| MAX_NATSCA| MIN_AREAKM| MAX_AREAKM| MIN_AREAMI| MAX_AREAMI| MIN_PERKM| MAX_PERKM| MIN_PERMI| MAX_PERMI| MIN_BBXMIN| MAX_BBXMIN| MIN_BBXMAX| MAX_BBXMAX| MIN_BBYMIN| MAX_BBYMIN| MIN_BBYMAX| MAX_BBYMAX| MEAN_BBXC| MEAN_BBYC|TIMEZONE       | UN_FID| POP1950| POP1955| POP1960| POP1965| POP1970| POP1975| POP1980| POP1985| POP1990| POP1995| POP2000| POP2005| POP2010| POP2015| POP2020| POP2025| POP2050| MIN_ZOOM|WIKIDATAID |    WOF_ID| CAPALT|NAME_EN      |NAME_DE      |NAME_ES      |NAME_FR      |NAME_PT      |NAME_RU    |NAME_ZH |LABEL |NAME_AR |NAME_BN |NAME_EL |NAME_HI |NAME_HU |NAME_ID |NAME_IT |NAME_JA |NAME_KO |NAME_NL |NAME_PL |NAME_SV |NAME_TR |NAME_VI |      NE_ID|
|---------:|--------:|---------:|:---------------|:------------|:-------|:-------------|:------------|-------:|:-----|---------:|--------:|:--------|:------|:--------|:-------|:--------|:------|:----|--------:|---------:|-------:|-------:|---------:|--------:|--------:|:---------------|:-------------|---------:|---------:|---------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|---------:|---------:|:--------------|------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|--------:|:----------|---------:|------:|:------------|:------------|:------------|:------------|:------------|:----------|:-------|:-----|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|----------:|
|         6|       30|         1|Populated place |Xiangyang    |NA      |Xiangfan      |Xiangyang    |       0|NA    |         0|        1|China    |CHN    |China    |CHN     |Hubei    |CN     |NA   | 32.02194|  112.1281| 1069000|  462956|   1710854|       12|       10|Xiangfan, Hubei |Xiangfan      |   2212780|   2251030|  10181949|          0|          0|         50|       1631|      11078|        630|       4277|      1889|      9853|      1174|      6123|   111.4417|   111.7462|   112.9667|   113.7250|   31.88333|   31.88333|   32.37678|   33.45833|  112.3745|  32.34100|Asia/Chongqing |    126|     104|     124|     147|     175|     208|     248|     295|     373|     492|     649|     855|    1006|    1069|    1164|    1309|    1431|    1533|      6.0|Q71284     | 102027039|      0|Xiangyang    |Xiangyang    |Xiangyang    |Xiangfan     |Xiangyang    |Сянъян     |襄阳    |NA    |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159148459|
|         4|       50|         1|Admin-1 capital |Shijiazhuang |NA      |Shijianzhuang |Shijiazhuang |       0|NA    |         0|        1|China    |CHN    |China    |CHN     |Hebei    |CN     |NA   | 38.05196|  114.4780| 2417000| 1992474|   5330611|       12|       12|Shijiazhuang    |Shijianzhuang |   5758891|   5764207|  15632167|          0|          0|         50|       3722|      12080|       1437|       4664|      2746|     10479|      1706|      6511|   113.9083|   113.9627|   114.9917|   116.0544|   37.31501|   37.54653|   38.61667|   39.05833|  114.7109|  38.09557|Asia/Shanghai  |    104|     335|     402|     481|     577|     691|     828|     992|    1172|    1372|    1634|    1947|    2275|    2417|    2628|    2941|    3198|    3405|      5.6|Q58401     | 102027161|      0|Shijiazhuang |Shijiazhuang |Shijiazhuang |Shijiazhuang |Shijiazhuang |Шицзячжуан |石家庄  |NA    |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      | 1159149907|

**Comment by nvkelso** [comment]
@elliotap can you verify the wikidataid is good-as is, or document what should change, please?

**Comment by elliotap** [comment]
@nvkelso wikidata values are good as-is

for ``Shijiazhuang``, ``wikidataid=Q58401`` - https://www.wikidata.org/wiki/Q58401
for ``Xiangyang``, ``wikidataid=Q71284`` - https://www.wikidata.org/wiki/Q71284

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
