### ISSUE TITLE
Continent boundary estimates are way off

### ISSUE THREAD

**Issue by osharaki** [nvkelso/natural-earth-vector#431]
I'm using the [1:10 Physical Labels dataset](https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-physical-labels/) to get continent boundaries. When I render the rectangular bounds in Leaflet, however, the coordinates are WAY off. Here's are two examples:
| Africa | South America |
|:---:|:---:|
|![ne_10m_geography_regions_polys_AFRICA](https://user-images.githubusercontent.com/38385026/97778654-e4961a80-1b78-11eb-8a14-8282d1771445.png)|![ne_10m_geography_regions_polys_SAMERICA](https://user-images.githubusercontent.com/38385026/97778655-e52eb100-1b78-11eb-8ae3-45346b849d58.png)|

**Comment by nvkelso** [comment]
Can you include more reproduction steps, please?

**Comment by osharaki** [comment]
I'm using [geopandas](https://geopandas.readthedocs.io/en/latest/index.html) to extract the bounds. My Python code looks like so:
```
import geopandas as gpd

shapefile = gpd.read_file("ne_10m_geography_regions_polys.shp") # read in label areas dataset
containingArea = shapefile[shapefile["name_en"] == "South America"]
containingAreaShape = containingArea.iloc[0].geometry
minx, miny, maxx, maxy = containingAreaShape.bounds
```
I then use these coordinates in Leaflet like so:
```
L.rectangle([[-81.44420325, -55.7012265] , [-34.88731849,  12.17786286]]).addTo(mymap);
```

**Comment by osharaki** [comment]
I've realized my own mistake. Leaflet expects coordinates as latitude followed by longitude. Instead, I was passing in the coordinates as I received them from the dataset, which is in the form of longitude followed by latitude. Flipping the values fixed the issue.
