### ISSUE TITLE
www.naturalearthdata.com download links return error 500 when referer is not set

### ISSUE THREAD

**Issue by pnorman** [nvkelso/natural-earth-vector#434]
``curl -I https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip`` returns

```
HTTP/2 500
server: nginx/1.14.1
date: Sat, 14 Nov 2020 22:44:50 GMT
content-type: text/html; charset=UTF-8
expires: Wed, 11 Jan 1984 05:00:00 GMT
cache-control: no-cache, must-revalidate, max-age=0
pragma: no-cache
x-endurance-cache-level: 2
```

wget gets a similar error. 

If I instead do `curl -e 'https://www.naturalearthdata.com/downloads/110m-cultural-vectors/' -I https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip` I get 

```
HTTP/2 302
server: nginx/1.14.1
date: Sat, 14 Nov 2020 22:47:02 GMT
content-type: text/html; charset=UTF-8
location: http://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip
expires: Wed, 11 Jan 1984 05:00:00 GMT
cache-control: no-cache, must-revalidate, max-age=0
pragma: no-cache
x-endurance-cache-level: 2
```

**Comment by mstrimas** [comment]
This change to requiring the referrer URL now means it's no longer possible to download Natural Earth data programmatically with R using `download.file()`. I use these data in R packages and online tutorials and will need to remove Natural Earth from these resources if this change is permanent. Would love to be able to keep using these data if the referrer URL requirement could be dropped.

**Comment by nvkelso** [comment]
I didn't make change to NE server so will need to look into this more. Why can't you set a referrer?

**Comment by mstrimas** [comment]
Strange, something most have changed because I'm now also getting an error when I try to download directly in Chrome. It's saying the file can't be downloaded securely and directs me [here](https://support.google.com/chrome/answer/6261569?p=mixed_content_downloads&visit_id=637412363447104689-3279678246&rd=1). I can ask Chrome to download anyway, but this wasn't an issue until recently.

Regarding R, the `download.file()` function doesn't allow setting a referrer as far as I know and using something like `curl` won't work cross platform.

Thanks!

**Comment by khufkens** [comment]
As for @mstrimas I've got the same issue here, impacting automated map generation. This issue wasn't there until a couple of days ago. Downloads work in the browser not using the `download.file()` function in R.

**Comment by andysouth** [comment]
@nvkelso can you advise whether this is likely to be temporary and return to previous behaviour ? or do I need to try to adapt to address ropensci/rnaturalearth#40 as identified by @mstrimas. Thanks.

**Comment by nvkelso** [comment]
I'll research and provide an update here by Monday. It's not an intentional change.

**Comment by nvkelso** [comment]
Looking at access logs, this change occurred November 12th when all new requests include a referrer.  Before that date there were a mix of valid referrer and null referrer.

It looks like the visual theme for the site is also borked, so might be related to an underlying auto update?

I'll keep investigating...

**Comment by nvkelso** [comment]
Some progress: Visual theme is fixed. 

Looks like rest of this is related to mixed https and http content and SSH and Chrome being more fussy about that these days. So a path forward but more journey to take.

**Comment by pnorman** [comment]
I'm no longer getting the 500 error. Instead I'm getting a redirect with an extra step, from `https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip` to  `http://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip` to `https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip`. The first and last are https, the middle isn't. This could be the cause of problems to download with mixed content.

**Comment by nvkelso** [comment]
Would be great if it was a 1 char fix! I'll give that a try.

**Comment by khufkens** [comment]
Things seem to work again, thanks!

**Comment by nvkelso** [comment]
@pnorman can you try that download again, please? I've fixed the redirect to point at the final https location directly, and added MIME type for application/zip.

**Comment by nvkelso** [comment]
(This has been completed for all download links, not just the example above.)

**Comment by nvkelso** [comment]
@andysouth Is it resolved for you now?

**Comment by pnorman** [comment]
All the responses look appropriate now, thanks.

**Comment by SomeoneElseOSM** [comment]
Works for me too (I logged https://github.com/gravitystorm/openstreetmap-carto/issues/4249 , which is related to this issue).

**Comment by andysouth** [comment]
Thankyou @nvkelso, yes this is resolved for rnaturalearth now.
