### ISSUE TITLE
 ERROR 500: Internal Server Error. 

### ISSUE THREAD

**Issue by AlexandreFrolov** [nvkelso/natural-earth-vector#435]
wget https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip
--2020-11-17 13:09:31--  https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip
Resolving www.naturalearthdata.com (www.naturalearthdata.com)... 66.147.242.194
Connecting to www.naturalearthdata.com (www.naturalearthdata.com)|66.147.242.194|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-11-17 13:09:33 ERROR 500: Internal Server Error.

**Comment by nvkelso** [comment]
https://github.com/nvkelso/natural-earth-vector/issues/434
