### ISSUE TITLE
unable to download data

### ISSUE THREAD

**Issue by jaycaesa** [nvkelso/natural-earth-vector#437]
I have tried on two different computers to download the natural earth raster data. On windows it simply wont download and on mac it says that the zip file cannot be downloaded securely. Any help would be greatly appreciated

**Comment by nvkelso** [comment]
Is this in Chrome? Please try Firefox or Safari as workaround. Else raw files are available here on GH.

**Comment by jaycaesa** [comment]
Yeah it was in chrome, thanks!

**Comment by nvkelso** [comment]
This is a dup of https://github.com/nvkelso/natural-earth-vector/issues/434.
