### ISSUE TITLE
Inconsistent use of Mount vs Mt. and Peak vs Pk.

### ISSUE THREAD

**Issue by almccon** [nvkelso/natural-earth-vector#439]
In the Western US, we have a mix of "Mount" and "Mt.", and mix of "Peak" and "Pk.".  The labels should all use either all abbreviations or no abbreviations.

<img width="712" alt="Screen Shot 2020-11-20 at 6 28 36 PM" src="https://user-images.githubusercontent.com/1212178/99865433-7680ba00-2b5e-11eb-9115-65e47f909576.png">

**Comment by nvkelso** [comment]
Is this in name or one of the name_en variant?

Agree they should be consistent.

**Comment by almccon** [comment]
That screenshot was the `name` field.

Interesting, in `name_en`, "Mount" is used consistently which is great, but the two "Pk." features in `name` do not have any labels at all in `name_en`.

Here's `name_en`
<img width="804" alt="Screen Shot 2020-11-20 at 7 10 58 PM" src="https://user-images.githubusercontent.com/1212178/99866231-489e7400-2b64-11eb-8457-5dc44049d7ed.png">

**Comment by elliotap** [comment]
Proposed Edits:
Expand Mt. -> Mount & Pk. -> Peak in name, namealt, and label values for the following features in ne_10m_geography_regions_elevation_points.shp

name | lat_y | long_x | ne_id
-- | -- | -- | --
Seweweekspoort Pk. | -33.395807 | 21.3657333 | 1159105217
Mt. Ramlo | 13.3924014 | 41.7277938 | 1159105253
Mt. Kenya | -0.150079 | 37.2999374 | 1159105297
Mt. Kilimanjaro | -3.0757382 | 37.3532821 | 1159105301
Mt. McMaster | -66.763482 | 51.9521591 | 1159105395
Mt. Erebus | -77.514459 | 167.182872 | 1159105397
Mt. Kirkpatrick | -84.339654 | 166.450328 | 1159105403
Mt. Damavand | 35.9552066 | 52.1090194 | 1159105649
Grandiozny Pk. | 53.9256656 | 96.0385848 | 1159105685
Mt. Everest | 27.9804752 | 86.8806258 | 1159105715
Mt. Macdonald | 64.7507999 | -132.8012 | 1159106065
Cold Mt. | 52.8853214 | 173.133433 | 1159106077
Harney Pk. | 43.8862979 | -103.53978 | 1159106101
Pummel Pk. | 29.2916324 | -103.24431 | 1159106123
Mt. Roosevelt | 58.4426334 | -125.3344 | 1159106163
Aniakchak Pk. | 56.8728091 | -158.12352 | 1159106199
Mt. Shasta | 41.4093082 | -122.195 | 1159106277
Mt. Hood | 45.3844669 | -121.69658 | 1159106287
Mt. Whitney | 36.5827091 | -118.29223 | 1159106313
Mt. Roraima | 5.14331696 | -60.762624 | 1159106519
Mt. Warning | -28.397149 | 153.270885 | 1159106735
Mt. Kosciuszko | -36.455865 | 148.263194 | 1159106753
Mt. Apo | 6.99707673 | 125.269908 | 1159107155
Canlaon Pk. | 10.4564883 | 123.141734 | 1159107301
Mt. Popomanaseu | -9.702081 | 160.06483 | 1159107467
Aoraki (Mt. Cook) | -43.595636 | 170.141124 | 1159107729
Mt. Taranaki | -39.296319 | 174.06483 | 1159107753

**Comment by elliotap** [comment]
Proposed Edits:
Expand Mt. -> Mount in name values for the following features in ne_50m_geography_regions_elevation_points.shp

name | lat_y | long_x | ne_id
-- | -- | -- | --
Mt. Everest | 27.9804752 | 86.8806258 | 1159105715
Mt. Kilimanjaro | -3.0757382 | 37.3532821 | 1159105301
Mt. Whitney | 36.5827091 | -118.29223 | 1159106313
Mt. Kosciuszko | -36.455865 | 148.263194 | 1159106753
Mt. Shasta | 41.4093082 | -122.195 | 1159106277
Mt. Hood | 45.3844669 | -121.69658 | 1159106287
Mt. Kenya | -0.150079 | 37.2999374 | 1159105297

**Comment by elliotap** [comment]
Proposed Edits:
Expand Mt. -> Mount in name values for the following features in ne_110m_geography_regions_elevation_points.shp

name | lat_y | long_x | ne_id
-- | -- | -- | --
Mt. Everest | 27.9804752 | 86.8806258 | 1159105715
Mt. Kilimanjaro | -3.0757382 | 37.3532821 | 1159105301
Mt. Whitney | 36.5827091 | -118.29223 | 1159106313
Mt. Kosciuszko | -36.455865 | 148.263194 | 1159106753

**Comment by nvkelso** [comment]
Both the `ne_50m_geography_regions_elevation_points` and `ne_110m_geography_regions_elevation_points` are derived files... once you edit the `ne_10m_geography_regions_elevation_points` you can run `make derived_physical_labels` and it'll do the work for you.

**Comment by nvkelso** [comment]
The proposal in https://github.com/nvkelso/natural-earth-vector/issues/439#issuecomment-793166716 works for me.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/497.
