### ISSUE TITLE
Territory of Azerbaijan

### ISSUE THREAD

**Issue by elvintarverdiyev** [nvkelso/natural-earth-vector#442]
Could you please remove the dotted lines and highlighted color around the so-called land Nagorno-Karabakh? It no longer exists. Based on the agreement signed between Armenia, Azerbaijan and Russia, status of former Nagorno-Karabakh has been abolished on November 10, 2020. Besides, it already lost its autonomy status back in 1991, and UN as well as all other international organizations and countries recognize this area as part of Azerbaijan.

![image](https://user-images.githubusercontent.com/33378874/101418940-5e53bd80-3908-11eb-9a26-21616aaad25f.png)

**Comment by nvkelso** [comment]
Thanks for the feedback! 

Generally speaking we let things settle for a little bit before updating the admin boundaries. But I’ll flag this for next release.

**Comment by nvkelso** [comment]
Can you provide a link to the website that is screenshotted, please?

Changing the data here is one thing, but whoever is using the data over there would also need to upgrade.

**Comment by jrus** [comment]
Wikipedia has a clear summary of the ceasefire agreement https://en.wikipedia.org/wiki/2020_Nagorno-Karabakh_ceasefire_agreement

It seems that a large chunk of territory was (re)captured by Azerbaijan, but a large area remains under the de facto control of https://en.wikipedia.org/wiki/Republic_of_Artsakh

Under the policy that:

> Natural Earth Vector draws boundaries of sovereign states according to defacto status. We show who actually controls the situation on the ground. For instance, we show China and Taiwan as two separate states. But we show Palestine as part of Israel. Please feel free to mashup our countries and disputed areas themes to match your particular political outlook.

... should Artsakh be drawn as a separate sovereign entity?

**Comment by nvkelso** [comment]
In the associated PR, it will continue to be shown as an (2020 events adjusted) breakaway region:

![image](https://user-images.githubusercontent.com/853051/121847213-15a50480-cc9d-11eb-9828-fe37012dfa18.png)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/446.
