### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by hartmut-mariadb** [nvkelso/natural-earth-vector#444]
Looks as if the naturalearthdata.com domain expired, and is now served by some domain squatter?

**Comment by SomeoneElseOSM** [comment]
For info, I currently see via "nslookup www.naturalearthdata.com 8.8.8.8":

Non-authoritative answer:
www.naturalearthdata.com        canonical name = naturalearthdata.com.
Name:   naturalearthdata.com
Address: 50.87.236.238

Website cert is a wildcard "*.bluehost.com", verified by "Sectigo Limited", expires "09 February 2021".

My recollection was that (a couple of days ago) the valid site had a letsencrypt certificate expiring in March.

**Comment by hartmut-mariadb** [comment]
Right now I only see "Copyright 2020 Privacy Policy", with privacy policy linking to:

http://www.parkingcrew.net/privacy.html

**Comment by nvkelso** [comment]
I'll have a look...

**Comment by nvkelso** [comment]
The earlier issue was https://github.com/nvkelso/natural-earth-vector/issues/443.

Working with the host to straighten this out. Sorry folks!

**Comment by nvkelso** [comment]
This sometime comes up:

![image](https://user-images.githubusercontent.com/853051/101950293-e3113680-3ba9-11eb-90ff-d6057441f35d.png)

**Comment by nvkelso** [comment]
Site is back up, fixed some caching issues. Theme is borked again, but downloads should all work. Will pick this up in a bit.

**Comment by nvkelso** [comment]
Perhaps the site theme is fixed (on every page). And the site should be faster now.

**Comment by nvkelso** [comment]
Still working after 24 hours, closing.
