### ISSUE TITLE
Update WOF concordances in NE populated places file

### ISSUE THREAD

**Issue by stepps00** [nvkelso/natural-earth-vector#447]
As part of https://github.com/whosonfirst-data/whosonfirst-data/issues/1547, I'm reviewing the Natural Earth "populated places" file on [this page](http://www.naturalearthdata.com/downloads/10m-cultural-vectors/). I noticed that 56 of the features in that file have outdated concordances to Who's On First. 

Here's a list of them: [mismatched_concordances.csv.txt](https://github.com/nvkelso/natural-earth-vector/files/6111984/mismatched_concordances.csv.txt)

Rows:
`ne_id`:  Natural Earth id
`old_wof`: The outdated concordance to WOF
`new_id`: The correct concordance to WOF

**Comment by mizmay** [comment]
@stepps00 can you edit the link to your CSV? Looks like it didn't come through.

**Comment by stepps00** [comment]
@mizmay - I've re-uploaded the file, let me know if that works for you.

**Comment by elliotap** [comment]
@mizmay Verified - see table below for recommended fixes


ne_id | old_wof | new_id | Recommended Action
-- | -- | -- | --
1159136389 | 1141907109 | 421190297 | change id
1159146257 | 101720571 | 101720567 | change id
1159146503 | 102002573 | 1175613621 | change id
1159146881 | 890512949 | 102027991 | change id
1159147443 | 85817091 | 85981333 | change id
1159148225 | 101913781 | 101913783 | change id, change namealt to Lodz or remove value of   "L"
1159149127 | 890444347 | 421189725 | change id
1159149245 | 1141909161 | 85970739 | change id
1159149299 | 85809317 | 85949461 | change id
1159149367 | 1141909171 | 101750467 | change id
1159149385 | 890440341 | 421171291 | change id
1159149697 | 1141909211 | 1125988111 | change id
1159149705 | 1141909215 | 1125880387 | change id
1159149795 | 890516741 | 102027777 | change id
1159149893 | 1141909249 | 102027827 | change id
1159150029 | 102029167 | 102030245 | change id
1159150127 | 85903159 | 421202467 | change id
1159150469 | 85953209 | 890437681 | change id
1159150507 | 890442123 | 421186751 | change id
1159150519 | 1141909337 | 101723183 | change id
1159150591 | 101750621 | 1175612707 | change id
1159150621 | 421173107 | 1125905513 | change id
1159150847 | 421169109 | 421173233 | change id
1159150849 | 421176367 | 421171925 | change id
1159150853 | 890439929 | 421191785 | change id
1159150931 | 101955041 | 102016833 | change id
1159150997 | 890444429 | 421189675 | change id
1159151059 | 85784763 | 101735873 | change id
1159151127 | 1141909395 | 1125853197 | change id
1159151133 | 890442179 | 421176731 | change id
1159151181 | 1141909405 | 101919427 | change id
1159151263 | 85687595 | 101751949 | change id
1159151277 | 890441449 | 421200923 | change id
1159151281 | 101751917 | 1495123997 | do not change - new_id not found in spelunker, old geo is valid
1159151287 | 85907577 | 421191101 | change id
1159151291 | 102008119 | 1158857531 | change id
1159151303 | 890451601 | 421188981 | change id
1159151341 | 421174875 | 1125373543 | change id
1159151347 | 85670445 | 421186583 | change id
1159151359 | 101714627 | 101748113 | change id
1159151401 | 421204951 | 890429209 | change id
1159151417 | 1141909423 | 1125955239 | change id
1159151421 | 1141909427 | 1125929605 | change id
1159151453 | 85765525 | 101950447 | change id
1159151465 | 101751573 | 1175610569 | change id
1159151503 | 421201239 | 101748283 | change id
1159151511 | 890442199 | 421186805 | change id
1159151525 | 421168919 | 1159397249 | change id
1159151545 | 101752329 | 1175612731 | change id
1159151549 | 890441645 | 421170391 | change id
1159151593 | 85936575 | 101752607 | change id
1159151601 | 890444995 | 421186687 | change id
1159151615 | 101958341 | 102016915 | change id
1159151623 | 85771099 | 101932003 | change id
1159151703 | 101915059 | 101914257 | change id

**Comment by mizmay** [comment]
AFTER

|      NE_ID|NAME             |NAMEASCII        |NAMEPAR   |NAMEALT                               |WIKIDATAID |     WOF_ID|
|----------:|:----------------|:----------------|:---------|:-------------------------------------|:----------|----------:|
| 1159136389|Ad Damman        |Ad Damman        |NA        |Ad-Dammam                             |Q160320    |  421190297|
| 1159146257|Providence       |Providence       |NA        |NA                                    |Q18383     |  101720567|
| 1159146503|Velikiy Novgorod |Velikiy Novgorod |NA        |Novgorod&#124;Nizhniy Novgorod        |Q2235      | 1175613621|
| 1159146881|Xingyi           |Xingyi           |NA        |Xingyi, Guizhou                       |Q1359367   |  102027991|
| 1159147443|Charlotte        |Charlotte        |NA        |NA                                    |Q16565     |   85981333|
| 1159148225|Łódź             |Lodz             |NA        |                                      |Q580       |  101913783|
| 1159149127|Benin City       |Benin City       |NA        |NA                                    |Q320704    |  421189725|
| 1159149245|Kansas City      |Kansas City      |NA        |NA                                    |Q41819     |   85970739|
| 1159149299|Baltimore        |Baltimore        |NA        |NA                                    |Q5092      |   85949461|
| 1159149367|Birmingham       |Birmingham       |NA        |NA                                    |Q2256      |  101750467|
| 1159149385|Kigali           |Kigali           |NA        |NA                                    |Q3859      |  421171291|
| 1159149697|Ibadan           |Ibadan           |NA        |NA                                    |Q183298    | 1125988111|
| 1159149705|Kaduna           |Kaduna           |NA        |NA                                    |Q208318    | 1125880387|
| 1159149795|Suzhou           |Suzhou           |NA        |Suzhou, Anhui                         |Q360643    |  102027777|
| 1159149893|Yueyang          |Yueyang          |NA        |NA                                    |Q151958    |  102027827|
| 1159150029|Guwahati         |Guwahati         |NA        |Gauhati&#124;Dispur&#124;Gauhati      |Q199605    |  102030245|
| 1159150127|Basra            |Basra            |NA        |Al-Basrah                             |Q48195     |  421202467|
| 1159150469|Montevideo       |Montevideo       |NA        |NA                                    |Q1335      |  890437681|
| 1159150507|Valencia         |Valencia         |NA        |NA                                    |Q54880     |  421186751|
| 1159150519|Nashville        |Nashville        |NA        |Nashville-Davidson                    |Q23197     |  101723183|
| 1159150591|Glasgow          |Glasgow          |NA        |NA                                    |Q4093      | 1175612707|
| 1159150621|Asunción         |Asuncion         |NA        |Asuncion                              |Q2933      | 1125905513|
| 1159150847|Quito            |Quito            |NA        |NA                                    |Q2900      |  421173233|
| 1159150849|San José         |San Jose         |NA        |San Jose                              |Q3070      |  421171925|
| 1159150853|San Salvador     |San Salvador     |NA        |NA                                    |Q3110      |  421191785|
| 1159150931|Valparaíso       |Valparaiso       |NA        |Valparaiso                            |Q33986     |  102016833|
| 1159150997|Conakry          |Conakry          |NA        |NA                                    |Q3733      |  421189675|
| 1159151059|Ottawa           |Ottawa           |NA        |Ottawa-Gatineau                       |Q1930      |  101735873|
| 1159151127|Phnom Penh       |Phnom Penh       |NA        |Phnum Penh                            |Q1850      | 1125853197|
| 1159151133|La Paz           |La Paz           |NA        |NA                                    |Q1491      |  421176731|
| 1159151181|San Juan         |San Juan         |NA        |NA                                    |Q41211     |  101919427|
| 1159151263|Bucharest        |Bucharest        |Bucuresti |NA                                    |Q19660     |  101751949|
| 1159151277|Jeddah           |Jeddah           |NA        |Jiddah                                |Q374365    |  421200923|
| 1159151281|Oslo             |Oslo             |NA        |NA                                    |Q585       |  101751917|
| 1159151287|Karachi          |Karachi          |NA        |NA                                    |Q8660      |  421191101|
| 1159151291|St. Petersburg   |St. Petersburg   |NA        |Sankt Peterburg&#124;Saint Petersburg |Q656       | 1158857531|
| 1159151303|Pyongyang        |Pyongyang        |NA        |P'yongyang                            |Q18808     |  421188981|
| 1159151341|Guayaquil        |Guayaquil        |NA        |NA                                    |Q43509     | 1125373543|
| 1159151347|Havana           |Havana           |NA        |La Habana                             |Q1563      |  421186583|
| 1159151359|Prague           |Prague           |Praha     |NA                                    |Q1085      |  101748113|
| 1159151401|Santo Domingo    |Santo Domingo    |NA        |NA                                    |Q34820     |  890429209|
| 1159151417|Tel Aviv-Yafo    |Tel Aviv-Yafo    |NA        |Tel Aviv-Jaffa                        |Q33935     | 1125955239|
| 1159151421|Mashhad          |Mashhad          |NA        |NA                                    |Q121157    | 1125929605|
| 1159151453|Salvador         |Salvador         |NA        |NA                                    |Q36947     |  101950447|
| 1159151465|Brussels         |Brussels         |NA        |Bruxelles-Brussel                     |Q239       | 1175610569|
| 1159151503|Madrid           |Madrid           |NA        |NA                                    |Q2807      |  101748283|
| 1159151511|Lima             |Lima             |NA        |NA                                    |Q2868      |  421186805|
| 1159151525|Manila           |Manila           |NA        |NA                                    |Q1461      | 1159397249|
| 1159151545|Athens           |Athens           |Athenai   |Athinai                               |Q1524      | 1175612731|
| 1159151549|Addis Ababa      |Addis Ababa      |NA        |NA                                    |Q3624      |  421170391|
| 1159151593|Rome             |Rome             |NA        |NA                                    |Q220       |  101752607|
| 1159151601|Bogota           |Bogota           |NA        |Bogota                                |Q2841      |  421186687|
| 1159151615|Santiago         |Santiago         |NA        |NA                                    |Q2887      |  102016915|
| 1159151623|Sydney           |Sydney           |NA        |NA                                    |Q3130      |  101932003|
| 1159151703|Auckland         |Auckland         |NA        |NA                                    |Q37100     |  101914257|

**Comment by nvkelso** [comment]
One minor change here... we should update Oslo's WOF ID to [1495123997](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-no/master/data/149/512/399/7/1495123997.geojson).

The WOF Spelunker hasn't had a data update in a little bit (which isn't obvious, sorry!), so it's not reflecting the actual state of the WOF data in Github. When you click out to the raw file in GH from the Spelunker link for https://spelunker.whosonfirst.org/id/101751917/ you'll see that file lists a large number of superceded_by pointers, including the one Stephen suggests. That original WOF record was expansive and was cut up into pieces, including one for the actual capital shape.

**Comment by nvkelso** [comment]
Fixed via #508, #510, #515 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
