### ISSUE TITLE
10m Populated Places: State-Wide Name Updates in Karnataka, India

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#448]
In 2014, Karnataka renamed 11 populated places present in NE 10m dataset. Requesting names be updated for the following places:

Bangalore->Bengaluru, ID:1159151543
Mangalore->Mangaluru, ID:1159150015
Bellary->Ballari, ID:1159148527
Bijapur->Vijayapura, ID:1159147195
Belgaum->Belagavi, ID:1159148531
Gulbarga->Kalaburagi, ID:1159150019
Mysore->Mysuru, ID:1159150017
Hospet->Hosapete, ID:1159141837
Shimoga->Shivamogga, ID:1159141827
Hubli->Hubballi, ID:1159150013
Tumkur->Tumakuru, ID:1159148523

Reference: https://www.thehindu.com/news/national/karnataka/from-bangalore-to-bengaluru/article6553314.ece

**Comment by nvkelso** [comment]
I agree with these changes... the default **name** field should be updated, after moving the existing value to **namepar**.

This will result in map labels like:

`Bengaluru (Bangalore)`

Which will enable people who are used to the old name to still find it, but respect the new name by default.

**Comment by mizmay** [comment]
This can be achieved programmatically as wikidataids are correct and wikidata values match these.

**Comment by mizmay** [comment]
Note this change is not reflected in localizations/Wikidata.

BEFORE:

|      NE_ID|NAME      |NAMEPAR |NAMEALT       |NAMEASCII |SOV0NAME |ADM0NAME |ADM1NAME  |MEGANAME      |LS_NAME   |NAME_EN    |NAME_DE       |NAME_ES   |NAME_FR       |NAME_PT    |NAME_RU  |NAME_ZH  |NAME_AR |NAME_BN |NAME_EL |NAME_HI |NAME_HU |NAME_ID |NAME_IT |NAME_JA |NAME_KO |NAME_NL |NAME_PL |NAME_SV |NAME_TR |NAME_VI |
|----------:|:---------|:-------|:-------------|:---------|:--------|:--------|:---------|:-------------|:---------|:----------|:-------------|:---------|:-------------|:----------|:--------|:--------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|
| 1159141827|Shimoga   |NA      |NA            |Shimoga   |India    |India    |Karnataka |NA            |Shimoga   |Shivamogga |Shivamogga    |Shimoga   |Shimoga       |Shivamogga |Шимога   |希莫加   |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159141837|Hospet    |NA      |NA            |Hospet    |India    |India    |Karnataka |NA            |Hospet    |Hospet     |Hospet        |Hospet    |Hospet        |Hospet     |NA       |霍斯佩特 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159147195|Bijapur   |NA      |NA            |Bijapur   |India    |India    |Karnataka |NA            |Bijapur   |Bijapur    |Bijapur       |Bijapur   |Bîjâpur       |Bijapur    |Биджапур |比贾普尔 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159148523|Tumkur    |NA      |NA            |Tumkur    |India    |India    |Karnataka |NA            |Tumkur    |Tumkur     |Tumkur        |Tumkur    |Tumkur        |Tumkur     |Тумкур   |杜姆古尔 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159148527|Bellary   |NA      |NA            |Bellary   |India    |India    |Karnataka |NA            |Bellary   |Bellary    |Bellary       |Bellary   |Bellary       |Bellary    |Беллари  |贝拉里   |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159148531|Belgaum   |NA      |NA            |Belgaum   |India    |India    |Karnataka |NA            |Belgaum   |Belgaum    |Belgaum       |Belgaum   |Belgaum       |Belgaum    |Белгаум  |贝尔高姆 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159150013|Hubli     |NA      |Hubli-Dharwad |Hubli     |India    |India    |Karnataka |Hubli-Dharwad |Hubli     |Hubli      |Hubli-Dharwad |Hubli     |Hubli-Dharwad |Hubli      |Хубли    |胡布利   |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159150015|Mangalore |NA      |NA            |Mangalore |India    |India    |Karnataka |NA            |Mangalore |Mangalore  |Mangaluru     |Mangalore |Mangalore     |Mangalore  |Мангалор |门格洛尔 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159150017|Mysore    |NA      |NA            |Mysore    |India    |India    |Karnataka |Mysore        |Mysore    |Mysore     |Mysore        |Mysore    |Mysore        |Mysore     |Майсур   |迈索尔   |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159150019|Gulbarga  |NA      |NA            |Gulbarga  |India    |India    |Karnataka |NA            |Gulbarga  |Gulbarga   |Gulbarga      |Gulbarga  |Gulbarga      |Gulbarga   |Гулбарга |古尔伯加 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159151543|Bangalore |NA      |Bengaluru     |Bangalore |India    |India    |Karnataka |Bangalore     |Bangalore |Bangalore  |Bangalore     |Bangalore |Bangalore     |Bangalore  |Бангалор |班加羅爾 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |

**Comment by mizmay** [comment]
AFTER:

|      NE_ID|NAME       |NAMEPAR   |NAMEALT |NAMEASCII  |SOV0NAME |ADM0NAME |ADM1NAME  |MEGANAME      |LS_NAME   |NAME_EN    |NAME_DE       |NAME_ES   |NAME_FR       |NAME_PT    |NAME_RU  |NAME_ZH  |NAME_AR |NAME_BN |NAME_EL |NAME_HI |NAME_HU |NAME_ID |NAME_IT |NAME_JA |NAME_KO |NAME_NL |NAME_PL |NAME_SV |NAME_TR |NAME_VI |
|----------:|:----------|:---------|:-------|:----------|:--------|:--------|:---------|:-------------|:---------|:----------|:-------------|:---------|:-------------|:----------|:--------|:--------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|
| 1159141827|Shivamogga |Shimoga   |        |Shivamogga |India    |India    |Karnataka |NA            |Shimoga   |Shivamogga |Shivamogga    |Shimoga   |Shimoga       |Shivamogga |Шимога   |希莫加   |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159141837|Hosapete   |Hospet    |        |Hosapete   |India    |India    |Karnataka |NA            |Hospet    |Hospet     |Hospet        |Hospet    |Hospet        |Hospet     |NA       |霍斯佩特 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159147195|Vijayapura |Bijapur   |        |Vijayapura |India    |India    |Karnataka |NA            |Bijapur   |Bijapur    |Bijapur       |Bijapur   |Bîjâpur       |Bijapur    |Биджапур |比贾普尔 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159148523|Tumakuru   |Tumkur    |        |Tumakuru   |India    |India    |Karnataka |NA            |Tumkur    |Tumkur     |Tumkur        |Tumkur    |Tumkur        |Tumkur     |Тумкур   |杜姆古尔 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159148527|Ballari    |Bellary   |        |Ballari    |India    |India    |Karnataka |NA            |Bellary   |Bellary    |Bellary       |Bellary   |Bellary       |Bellary    |Беллари  |贝拉里   |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159148531|Belagavi   |Belgaum   |        |Belagavi   |India    |India    |Karnataka |NA            |Belgaum   |Belgaum    |Belgaum       |Belgaum   |Belgaum       |Belgaum    |Белгаум  |贝尔高姆 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159150013|Hubballi   |Hubli     |        |Hubballi   |India    |India    |Karnataka |Hubli-Dharwad |Hubli     |Hubli      |Hubli-Dharwad |Hubli     |Hubli-Dharwad |Hubli      |Хубли    |胡布利   |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159150015|Mangaluru  |Mangalore |        |Mangaluru  |India    |India    |Karnataka |NA            |Mangalore |Mangalore  |Mangaluru     |Mangalore |Mangalore     |Mangalore  |Мангалор |门格洛尔 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159150017|Mysuru     |Mysore    |        |Mysuru     |India    |India    |Karnataka |Mysore        |Mysore    |Mysore     |Mysore        |Mysore    |Mysore        |Mysore     |Майсур   |迈索尔   |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159150019|Kalaburagi |Gulbarga  |        |Kalaburagi |India    |India    |Karnataka |NA            |Gulbarga  |Gulbarga   |Gulbarga      |Gulbarga  |Gulbarga      |Gulbarga   |Гулбарга |古尔伯加 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |
| 1159151543|Bengaluru  |Bangalore |        |Bengaluru  |India    |India    |Karnataka |Bangalore     |Bangalore |Bangalore  |Bangalore     |Bangalore |Bangalore     |Bangalore  |Бангалор |班加羅爾 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
