### ISSUE TITLE
10m Populated Places: Duplicate Records for Adapazarı, Turkey

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#449]
Two features in the populated place dataset appear to represent the same city. 

**Name | ID | Wikidata**
Sakarya | 1159113425 | [Q175323](https://www.wikidata.org/wiki/Q175323)
Adapazarı | 1159146375 | [Q175323](https://www.wikidata.org/wiki/Q175323)

Adapazarı appears to be the correct name for this city, while Sakarya is the province it is within: https://en.wikipedia.org/wiki/Adapazar%C4%B1

**Comment by nvkelso** [comment]
I'd delete 1159146375 and keep 1159113425 (which is marked as the admin-1 capital and has better position), but first copy over some of the NE population guestimates (max, min pops and bbox).

**Comment by mizmay** [comment]
Makes sense to consolidate these two records and keep `1159146375` and `Admin 1` but Wikipedia is not consistent about whether this place should be called Adapazarı or Sakarya (city). Based on wikidataid `Q175323` let's keep Adapazarı as @elliotap suggests and move Sakarya to `NAMEPAR`

**Comment by nvkelso** [comment]
Works for me. Let's check to make sure the feature class is right (admin 1 cap), it was likely confused because of that.

**Comment by mizmay** [comment]
On closer inspection, I am having trouble concluding Adapazarı and Sakarya city are the same place. While Wikipedia uses the names interchangeably and refers to each as the provincial capital, all other sources I checked show both.

OpenStreetMap - [Sakarya](https://www.openstreetmap.org/node/6088495935) and [Adapazarı](https://www.openstreetmap.org/node/25869708)

[Google Maps](https://www.google.com/maps/@40.7888541,30.370935,11z)

**Comment by mizmay** [comment]
There is a wikidata id for Sakarya - Q3945164. I will update this record to that value.

https://www.sakarya.bel.tr/

**Comment by nvkelso** [comment]
One way or another, I suspect there should just be a single record for this place in Natural Earth.

Yandex has a customized Turkish map:

- https://yandex.com.tr/harita/profile?ll=30.399680%2C40.784850&z=14

They show the two on top of each other, and around zoom 14 one label dissolves into the other one. They are using Sakarya as the capital city name and Adapazarı as what looks like a borough (city section / large neighbourhood) name.

Switching to Google... If you click on the two labels in GMaps you can see one has a polygon and one doesn't... and one has associated Wiki data and one doesn't.

**Comment by nvkelso** [comment]
Looks like the "localadmin" in WOF speak is `Adapazari` and self declares in this "tourist map app: https://keos.adapazari.bel.tr:8086/keos/. I'm fine to use the value as the default name in Natural Earth. Confriming what @elliotap originally proposed :)

**Comment by elliotap** [comment]
I dug a little deeper into this also - from what I found:

Adapazari is the precedent name for the city (https://www.sakarya.bel.tr/tr/Sayfa/sakarya-rehberi/1), and now established as a municipality

There was some significant administrative restructuring (https://www.tandfonline.com/doi/full/10.1080/01900692.2014.903277?scroll=top&needAccess=true) between 2004-2012, that established the Sakarya Metropolitan Municipality (
http://www.lawsturkey.com/law/law-on-metropolitan-municipalities-5216, https://www.resmigazete.gov.tr/eskiler/2012/12/20121206-1.htm _Article 1 (2)_)

The best of my understanding now is that Sakarya Metropolitan Municipality is an administrative entity named for the province, which now contains Adapazari

**Comment by nvkelso** [comment]
From @elliotap's link:

```
With the “Law on Establishment of Districts within the Borders of the Metropolitan Municipality and Making Amendments to Certain Laws” dated 6 March 2008 and numbered 5747, published in the Official Gazette dated 22 March 2008 and numbered 26824;
- Adapazarı Municipality (affiliated as Adapazarı Central Municipality in 2000)
- Arifiye Municipality (affiliated as the first level municipality in 2000)
- Erenler Municipality (affiliated as the first level municipality in 2000)
- Serdivan Municipality (affiliated as the first level municipality in 2000)
```

**Comment by mizmay** [comment]
Sounds good.

Makes sense to do detailed manual updates after batch updates, so for now just updated the record (https://github.com/nvkelso/natural-earth-vector/pull/457) and made sure the other aspects of this issue are tracked (https://gist.github.com/mizmay/89f6eed0e571e5e324bb7e13005715fc)

**Comment by nvkelso** [comment]
**Adapazarı** with ne_id of `1159146375 ` should be changed as **featurecla** to `Admin-1 capital`. The other place near here **Sakarya** should be deleted. Technically both these places are true in their own ways, but we only need a single point here for balance in the overall composition. 

The **name_alt** of `1159146375` should change to `Sakarya`.

Delete Sakarya **ne_id** `1159113425` entirely.

**Comment by mizmay** [comment]
Sure. Here are the fields with significantly differing values:

| ne_id | SCALERANK | NATSCALE | min_zoom | wof_id | POP_MAX | POP_MIN | POP_OTHER | 
|-|-|-|-|-|-|-|-|
| 1159113425 (deleted) | 10 | 1 | 7 | 101912667 | 286787 | 286787 | 0 |
| 1159146375 (maintained) | 6 | 30 | 5.1 | 1141908503 | 260109 | 260109 | 226654 |

The BBOX and other values are only populated in the maintained record.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
