### ISSUE TITLE
10m Populated Places: Location of Bodø, Norway

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#450]
Requesting slight adjustment to location of Bodø from approximately 67.24709747, 14.4008082 to 67.2827, 14.3751. 

Current location is in the Saltfjorden (https://en.wikipedia.org/wiki/Saltfjorden). Requested location is given in wikipedia: https://en.wikipedia.org/wiki/Bod%C3%B8

**Comment by elliotap** [comment]
Positional accuracy is off for several layers on the peninsula here compared to OSM + Google, including admin 0, admin 1, roads, railroads, and parks & protected lands

view of 10m:
<img width="1792" alt="Screen Shot 2021-03-08 at 1 32 49 PM" src="https://user-images.githubusercontent.com/64806657/110384746-ee41fa00-8012-11eb-85f0-ef6df215556f.png">
<img width="1792" alt="Screen Shot 2021-03-08 at 1 32 43 PM" src="https://user-images.githubusercontent.com/64806657/110384759-f13cea80-8012-11eb-9f39-6868e26fc16f.png">

**Comment by nvkelso** [comment]
Oh, that's not great. Changing the coastline around can be quite involved as it also impacts the raster layers, which I was very much hoping to avoid.

Suggest moving the townspot into the urban polygon which at least overlaps with the IRL ground config.

**Comment by elliotap** [comment]
Proposed edits:
Move point feature to 67.27643458622849, 14.429284888498778
Change latitude to 67.27643458622849
Change longitude to 14.429284888498778

**Comment by nvkelso** [comment]
Works for me.

**Comment by mizmay** [comment]
BEFORE:
|      NE_ID|NAME | LATITUDE| LONGITUDE|
|----------:|:----|--------:|---------:|
| 1159146401|Bodø | 67.24677|  14.39901|

**Comment by mizmay** [comment]
AFTER:
|      NE_ID|NAME | LATITUDE| LONGITUDE|
|----------:|:----|--------:|---------:|
| 1159146401|Bodø | 67.27643|  14.42928|

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
