### ISSUE TITLE
All Layers: Request for Persian Language Support

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#451]
Requesting, if feasible, name field for Persian (Farsi) language (ISO 639-1: fa) - 53 million native speakers per https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers

**Comment by nvkelso** [comment]
Good idea, shouldn't be too much work.

**Comment by nvkelso** [comment]
I have this working locally.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/446.
