### ISSUE TITLE
10m Populated Places: Ammochostos/Famagusta, Nicosia

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#452]
For feature 1159132353, name=Ammochostos. Ammochostos appears to be historical Greek name, and Famagusta appears to be the broadly preferred name. Requesting update for name=Famagusta & namealt=Ammochostos 

**References:**
Cartographic history: http://157.181.182.3/hun/doktoran/arkan/arkan-dissertation.pdf (p. 18-56)
Wikipedia: https://en.wikipedia.org/wiki/Famagusta
AP Style: https://apnews.com/article/media-virus-outbreak-social-media-cyprus-8f6b30e10fa00d03a5118b544d16ffc8

**Comment by mizmay** [comment]
Verified via [OpenStreetMap](https://www.openstreetmap.org/node/306213529
[Google Maps]) (https://www.google.com/maps/place/Famagusta/@35.1194059,33.8989477,13z/data=!3m1!4b1!4m5!3m4!1s0x14dfc842da4c163d:0x29db03c5a5d3ce87!8m2!3d35.1149116!4d33.919245)
and Apple Maps
<img width="868" alt="Screen Shot 2020-12-28 at 4 11 00 PM" src="https://user-images.githubusercontent.com/3074691/103250155-5693a180-4927-11eb-9dad-4e0019f20882.png">

**Comment by mizmay** [comment]
BEFORE

|      NE_ID|NAME        |NAMEPAR |NAMEALT |NAMEASCII   |SOV0NAME        |ADM0NAME        |ADM1NAME |MEGANAME |LS_NAME     |NAME_EN   |NAME_DE   |NAME_ES   |NAME_FR    |NAME_PT   |NAME_RU   |NAME_ZH    |NAME_AR |NAME_BN |NAME_EL |NAME_HI |NAME_HU |NAME_ID |NAME_IT |NAME_JA |NAME_KO |NAME_NL |NAME_PL |NAME_SV |NAME_TR |NAME_VI |
|----------:|:-----------|:-------|:-------|:-----------|:---------------|:---------------|:--------|:--------|:-----------|:---------|:---------|:---------|:----------|:---------|:---------|:----------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|
| 1159132353|Ammochostos |NA      |NA      |Ammochostos |Northern Cyprus |Northern Cyprus |NA       |NA       |Ammochostos |Famagusta |Famagusta |Famagusta |Famagouste |Famagusta |Фамагуста |法马古斯塔 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |

**Comment by mizmay** [comment]
AFTER:

|      NE_ID|NAME      |NAMEPAR |NAMEALT     |NAMEASCII |SOV0NAME        |ADM0NAME        |ADM1NAME |MEGANAME |LS_NAME     |NAME_EN   |NAME_DE   |NAME_ES   |NAME_FR    |NAME_PT   |NAME_RU   |NAME_ZH    |NAME_AR |NAME_BN |NAME_EL |NAME_HI |NAME_HU |NAME_ID |NAME_IT |NAME_JA |NAME_KO |NAME_NL |NAME_PL |NAME_SV |NAME_TR |NAME_VI |
|----------:|:---------|:-------|:-----------|:---------|:---------------|:---------------|:--------|:--------|:-----------|:---------|:---------|:---------|:----------|:---------|:---------|:----------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|
| 1159132353|Famagusta |NA      |Ammochostos |Famagusta |Northern Cyprus |Northern Cyprus |NA       |NA       |Ammochostos |Famagusta |Famagusta |Famagusta |Famagouste |Famagusta |Фамагуста |法马古斯塔 |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |

**Comment by nvkelso** [comment]
I think the **NAME** and **NAMEASCII** should be `Famagusta`, but the earlier name should be **NAMEPAR** = `Ammochostos` (not **NAMEALT**) to recognize the historical and conflict status.

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
