### ISSUE TITLE
10m Populated Places: Rida, Yemen

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#453]
Feature 1159134263 has name value of "Rida" (which may refer to a former province of North Yemen, https://en.wikipedia.org/wiki/Administrative_divisions_of_Yemen#Provinces_of_North_Yemen). No value is present for wikidata.

Correct name is "Rada'a", with wikidata=[Q2125362](https://www.wikidata.org/wiki/Q2125362) 
https://ar.wikipedia.org/wiki/%D8%B1%D8%AF%D8%A7%D8%B9

**Comment by mizmay** [comment]
[OpenStreetMap](https://www.openstreetmap.org/node/5587743988) calls this Rada' with Rada'a a nearby residential district.
Verfied on Google Maps and Apple Maps

**Comment by mizmay** [comment]
See https://github.com/nvkelso/natural-earth-vector/pull/457

**Comment by nvkelso** [comment]
The default **name** value should change to `Rada'a` and **name_alt** to `Rida` to preserve the earlier value, and **nameascii** value should change to `Radaa`. The **geonameid** should be `71491`.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
