### ISSUE TITLE
10m Populated Places: Wikidata for Banners in Inner Mongolia

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#455]
The following features in Inner Mongolia do not currently have a value for wikidata but correspond with the following wikidata IDs:

Name | ID | Wikidata
Bairin Zuoqi | 1159141123 | Q1329235
Ergun Zuoqi | 1159130275  | Q1354108
Hanggin Houqi | 1159130301 | Q1202314
Alxa Zuoqi | 1159141109 | Q1367222

In addition, "Ergun Zuoqi" is now named "Genhe" (https://en.wikipedia.org/wiki/Genhe)

**Comment by elliotap** [comment]
Verified

For Genhe, compare to Apple:
<img width="1398" alt="Screen Shot 2021-03-18 at 3 42 41 PM" src="https://user-images.githubusercontent.com/64806657/111707217-e3504c00-8800-11eb-893e-1a65afec2544.png">
Google:
<img width="1680" alt="Screen Shot 2021-03-18 at 3 45 21 PM" src="https://user-images.githubusercontent.com/64806657/111707278-01b64780-8801-11eb-979d-e363ad40e990.png">

OSM:
<img width="1680" alt="Screen Shot 2021-03-18 at 3 45 39 PM" src="https://user-images.githubusercontent.com/64806657/111707288-04b13800-8801-11eb-9c4d-0be2ff33b839.png">

Proposed edits:
for feature with ne_id=1159130275
Change name from Ergun Zuoqi to Genhe
Change namepar from NULL to Ergun Zuoqi
Add wikidataid "Q1354108"

for feature with ne_id= 1159141123:
add wikidataid "Q1329235"

for feature with ne_id= 1159130275:
add wikidataid "Q1354108"

for feature with ne_id= 1159130301:
add wikidataid "Q1202314"

**Comment by elliotap** [comment]
@mizmay adding you on this for your script

**Comment by nvkelso** [comment]
Works for me, thanks!

**Comment by mizmay** [comment]
After

|      NE_ID|NAME          |NAMEASCII     |NAMEPAR     |WIKIDATAID |
|----------:|:-------------|:-------------|:-----------|:----------|
| 1159130275|Genhe         |Genhe         |Ergun Zuoqi |Q1354108   |
| 1159130301|Hanggin Houqi |Hanggin Houqi |NA          |Q1202314   |
| 1159141109|Alxa Zuoqi    |Alxa Zuoqi    |NA          |Q1367222   |
| 1159141123|Bairin Zuoqi  |Bairin Zuoqi  |Lindong     |Q1329235   |

**Comment by nvkelso** [comment]
@elliotap do you remember why we tagged this with admin-1, or was that done in error?

If there in admin-1 edit to make then that process detailed in https://github.com/nvkelso/natural-earth-vector/issues/396#issuecomment-789428141.

Else the related commit will resolve the issue.

**Comment by elliotap** [comment]
@nvkelso believe it is an errant tag - not related to #160 and these places are contained by the admin-1 ``CHN-1838``

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
