### ISSUE TITLE
Wikidata | Populated_Places | China |   County -> City replacement

### ISSUE THREAD

**Issue by ImreSamu** [nvkelso/natural-earth-vector#458]
* based of the latest wikidata dump info  ( 1w ago ) + NE `v5-prequel` branch (~1 day old ) + my old scripts ... 
* imho:  "currently" lot of "county of China"   should be a  "town/city"
   * the new wikidata id-s is not perfect .. but so much better than the current wikidata ( ~ based of 2y old data )
   

| ne_id	| ne_name	| current_wd_id	| _suggested_wd_id_url	| old_p31_instance_of	| new_p31_instance_of |
| ------------|-----------| ----------------------------------------- | --------------------------------------    | ------------------------------------| -----------------------------------   |          
| 1159130307	| Qinggang	| https://www.wikidata.org/wiki/Q1197347	| https://www.wikidata.org/wiki/Q8836938	| `[{"Q1289426": "county of China"}]` |	`[{"Q735428": "town in China"}]`      |   
| 1159130333	| Suileng	| https://www.wikidata.org/wiki/Q1197498	| https://www.wikidata.org/wiki/Q13992688	| `[{"Q1289426": "county of China"}]` |	`[{"Q735428": "town in China"}]`      |   
| 1159140833	| Wenshan	| https://www.wikidata.org/wiki/Q1371362	| https://www.wikidata.org/wiki/Q1201048	| `[{"Q1289426": "county of China"}]` |	`[{"Q1070990": "county-level city"}]` |        
| 1159141055	| Liuhe	    | https://www.wikidata.org/wiki/Q1361265	| https://www.wikidata.org/wiki/Q11109923	| `[{"Q1289426": "county of China"}]` |	`[{"Q735428": "town in China"}]`      |   
| 1159141079	| Wangqing	| https://www.wikidata.org/wiki/Q699138	    | https://www.wikidata.org/wiki/Q13897219	| `[{"Q1289426": "county of China"}]` |	`[{"Q735428": "town in China"}]`      |   
| 1159141183	| Tailai	| https://www.wikidata.org/wiki/Q1333142	| https://www.wikidata.org/wiki/Q11145142	| `[{"Q1289426": "county of China"}]` |	`[{"Q735428": "town in China"}]`      |   
| 1159141193	| Gannan	| https://www.wikidata.org/wiki/Q562234	    | https://www.wikidata.org/wiki/Q1493582	| `[{"Q1289426": "county of China"}]` |	`[{"Q735428": "town in China"}]`      |   
| 1159141223	| Lanxi	    | https://www.wikidata.org/wiki/Q379189	    | https://www.wikidata.org/wiki/Q10893722	| `[{"Q1289426": "county of China"}]` |	`[{"Q735428": "town in China"}]`      |   
| 1159141231	| Nancha	| https://www.wikidata.org/wiki/Q476833	    | https://www.wikidata.org/wiki/Q2043360	| `[{"Q1289426": "county of China"}]` |	`[{"Q735428": "town in China"}]`      |

**Comment by nvkelso** [comment]
Scheduled for v5.1

**Comment by nvkelso** [comment]
The value changes look good to me.

**Comment by mizmay** [comment]
BEFORE

|      NE_ID|NAME     |WIKIDATAID |
|----------:|:--------|:----------|
| 1159130307|Qinggang |Q1197347   |
| 1159130333|Suileng  |Q1197498   |
| 1159140833|Wenshan  |Q1371362   |
| 1159141055|Liuhe    |Q1361265   |
| 1159141079|Wangqing |Q699138    |
| 1159141183|Tailai   |Q1333142   |
| 1159141193|Gannan   |Q562234    |
| 1159141223|Lanxi    |Q379189    |
| 1159141231|Nancha   |Q476833    |

AFTER

|      NE_ID|NAME     |WIKIDATAID |
|----------:|:--------|:----------|
| 1159130307|Qinggang |Q8836938   |
| 1159130333|Suileng  |Q13992688  |
| 1159140833|Wenshan  |Q1201048   |
| 1159141055|Liuhe    |Q11109923  |
| 1159141079|Wangqing |Q13897219  |
| 1159141183|Tailai   |Q11145142  |
| 1159141193|Gannan   |Q1493582   |
| 1159141223|Lanxi    |Q10893722  |
| 1159141231|Nancha   |Q2043360   |

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
