### ISSUE TITLE
wikidata | 10m populated_places | replace 

### ISSUE THREAD

**Issue by ImreSamu** [nvkelso/natural-earth-vector#459]
some low hanging fruits ... for update ..  please double check as usual ... 
[  record format: " ne_id | min_zoom | featurecla | ne_name" ]

1159150235 | 5.6 | Populated place | Peace River 
* now: https://www.wikidata.org/wiki/Q2220 ( river )
* proposal: https://www.wikidata.org/wiki/Q1743985 (town in Alberta )

1159149079 | 6 | Admin-0 capital | Tarawa 
* now:  https://www.wikidata.org/wiki/Q2486  ( island , atoll ) 
* proposal https://www.wikidata.org/wiki/Q131233  ( https://en.wikipedia.org/wiki/South_Tarawa )

1159143805 | 6.7 | Populated place | Chapleau 
* now: https://www.wikidata.org/wiki/Q5073210  ( First Nation )
* proposal: https://www.wikidata.org/wiki/Q2957549 ( township of Ontario, Canada )

1159136041 | 6.7 | Populated place | Chilca 
* now: https://www.wikidata.org/wiki/Q8837741 ( Rocket launch site in Peru )
* proposal:  https://www.wikidata.org/wiki/Q16890238 ( town in Lima, Peru )

1159132375 | 7 | Populated place | Oymyakon 
* now: https://www.wikidata.org/wiki/Q16896007 ( Null Island?? ;strange error .. ) 
* proposal: https://www.wikidata.org/wiki/Q192098 ( rural locality in the Sakha Republic, Russia )

1159130545 | 7 | Populated place | Chuquicamata 
* now: https://www.wikidata.org/wiki/Q746606  ( copper mine )
* proposal:  https://www.wikidata.org/wiki/Q55342984 ( ghost town; population=0 )
     * https://es.wikipedia.org/wiki/Chuquicamata_(ciudad) )

1159134475 | 6.1 | Populated place | Hua Hin 
* now:  https://www.wikidata.org/wiki/Q1666491 (district )
* proposal: https://www.wikidata.org/wiki/Q667576  ( city )

1159134483 | 8 | Admin-1 capital | Samut Prakan 
* now: https://www.wikidata.org/wiki/Q2219208 ( district in Samut Prakan province, Thailand )
* proposal: https://www.wikidata.org/wiki/Q13139252  ( city in Samut Prakan province, Thailand )

1159134373 | 8 | Populated place | Thung Song 
* now: https://www.wikidata.org/wiki/Q476950 ( district in Nakhon Si Thammarat province, Thailand )
* proposal: https://www.wikidata.org/wiki/Q15199303 ( town in Nakhon Si Thammarat province, Thailand )

1159146177 | 6 | Admin-1 capital | Miaoli 
* now:  https://www.wikidata.org/wiki/Q63706 ( county in Taiwan ) 
* proposal: https://www.wikidata.org/wiki/Q701651 ( A county-controlled city in Miaoli County )

1159147191 | 6 | Populated place | Warangal 
* now: https://www.wikidata.org/wiki/Q213077 ( district of Telangana, India )
* proposal: https://www.wikidata.org/wiki/Q25563103  ( city in Warangal district, Telangana, India )

1159139891 | 6.7 | Populated place | Makale 
* now:  https://www.wikidata.org/wiki/Q1886233 ( district in Tana Toraja Regency, Sulawesi Selatan Province, Indonesia )
* proposal: https://www.wikidata.org/wiki/Q57079173 ( city in Sulawesi )

1159147325 | 6 | Populated place | Gorakhpur 
* now: https://www.wikidata.org/wiki/Q244415 (village in Haryana, India  : https://en.wikipedia.org/wiki/Gorakhpur,_Haryana  )
* proposal: https://www.wikidata.org/wiki/Q5584396  ( city : https://en.wikipedia.org/wiki/Gorakhpur  )

1159150217 | 5.6 | Populated place | Vitória da Conquista 
* now: https://www.wikidata.org/wiki/Q330208  ( cebuano import ; only 1 wikipage )
* proposal: https://www.wikidata.org/wiki/Q22062839 ( municipality of Bahia State, Brazil )

1159134277 | 6.1 | Admin-1 capital | Ras al Khaymah 
* now: https://www.wikidata.org/wiki/Q170024 ( emirate of United Arab Emirates )
* proposal:  "Ras al-Khaimah"  https://www.wikidata.org/wiki/Q2126436  ( capital of Ras al-Khaimah, UAE )

1159113499 | 9 | Admin-1 capital | Antioch 
* now: https://www.wikidata.org/wiki/Q200441 (ancient city;archaeological site)
* proposal: https://www.wikidata.org/wiki/Q80561 ( district and city in Turkey )

1159135187 | 6.7 | Populated place | Hatay 
* now: https://www.wikidata.org/wiki/Q200441 ( ancient city )  + duplicated wikidata  ne_id=1159113499
* proposal: ?????

1159138309 | 6.7 | Populated place | Villa Ahumada 
* now:  https://www.wikidata.org/wiki/Q4111395   ( cebuano import )
* proposal https://www.wikidata.org/wiki/Q20148488 ( seems better )

1159138313 | 6.7 | Populated place | Ciudad Camargo 
* now:  https://www.wikidata.org/wiki/Q2652276 ( municipality in the Mexican state of Chihuahua )
* proposal:  Santa Rosalía de Camargo | https://www.wikidata.org/wiki/Q2528602  ( seems better )

1159139183 | 6.7 | Populated place | Sonbong 
* now:  https://www.wikidata.org/wiki/Q1149302 
   *  ( ?? Sonbong County | subdivision of the North Korean city of Rason )
* ?? proposal:  https://www.wikidata.org/wiki/Q221734 ( North Korean city and ice-free port in the East Sea )
   * "Rason (formerly Rajin-Sŏnbong; "  https://en.wikipedia.org/wiki/Rason
   

1159139193 | 6.1 | Populated place | Hungnam 
* now:  https://www.wikidata.org/wiki/Q224982 ( " In late 2005, nearby Hŭngnam was made a ward (kuyŏk) within Hamhŭng-si")
* delete / or  --> Hamhung | https://www.wikidata.org/wiki/Q109356 ?

1159144565 | 6.1 | Populated place | Ali Bayramli 
* now:  https://www.wikidata.org/wiki/Q172902  ( district of Turkey )
* proposal: "Şirvan" | https://www.wikidata.org/wiki/Q241116  ( city in Azerbaijan, Ali Bayramli, Şirvan, Azerbaijan Shirvan )
   * "The city was called Zubovka prior to 1938, then was renamed Ali Bayramli in honor of Ali Bayramov from 1938 to 2008."

1159149873 | 5 | Populated place | Xigaze 
* now: https://www.wikidata.org/wiki/Q116656 ( Samzhubzê District ?? )
* proposal: Shigatse | https://www.wikidata.org/wiki/Q1211183 ( prefecture-level city in Tibet Autonomous Region, China )

**Comment by Andrettin** [comment]
@ImreSamu can that data be used for this project? Wouldn't there be a license incompatibility, as wikidata is licensed under the CC-BY-SA and Natural Earth under the CC0? Unless the next version of Natural Earth has CC-BY-SA as its license...

Perhaps @nvkelso can clarify.

**Comment by ImreSamu** [comment]
@Andrettin:

yes, I agree with you, the license is extreme important !
 
> Wouldn't there be a license incompatibility, as wikidata is licensed under the CC-BY-SA and Natural Earth under the CC0? 

I am not a license expert, and my basic understandings is:

My "matching" work is based on **"Wikidata Dump"** -  see https://dumps.wikimedia.org/legal.html
* _"Wikidata:  Rights in Wikidata are waived using the Creative Commons Zero public domain dedication."_

other info: https://www.wikidata.org/wiki/Wikidata:Licensing
* _"The statement of Wikidata's policy is at Wikidata:Copyright. **All structured data from the main, property and lexeme namespaces is available under the Creative Commons CC0 License;**"_

imho:  what is the "main namespace"?  -> https://www.wikidata.org/wiki/Help:Namespaces#Main_namespace 
  * _"Pages are titled according to their unique identifiers (Q###). They don't contain wiki code and their content is internally formatted in JSON."_    example: https://www.wikidata.org/wiki/Q142

If you have a better info, please share !  :+1: 
*  ( imho:  it would be better to create a new issue, because is so important !! )

**Comment by Andrettin** [comment]
@ImreSamu It was an error on my part then, sorry for the misunderstanding and thanks for the clarification!

**Comment by ImreSamu** [comment]
@Andrettin : No problem :smile:  ;  If you have any question, proposal,feedback - just ask :+1:

**Comment by nvkelso** [comment]
Scheduled for v5.1

**Comment by nvkelso** [comment]
All the proposed changes look good to me, over to @mizmay

**Comment by elliotap** [comment]
Verified, see table below with recommended actions:


NE ID | Former WD | Proposed WD | Recommended Action
-- | -- | -- | --
1159150235 | Q2220 | Q1743985 | change WD
1159149079 | Q2486 | Q131233 | change WD
1159143805 | Q5073210 | Q2957549 | change WD
1159136041 | Q883774 | Q16890238 | change WD
1159132375 | Q16896007 | Q192098 | change WD
1159130545 | Q746606 | Q55342984 | change WD, POP_MAX/MIN/OTHER to 0
1159134475 | Q166491 | Q667576 | change WD
1159134483 | Q2219208 | Q13139252 | change WD
1159134373 | Q476950 | Q15199303 | change WD
1159146177 | Q63706 | Q701651 | change WD
1159147191 | Q213077 | Q25563103 | change WD
1159139891 | Q1886233 | Q57079173 | change WD
1159147325 | Q244415 | Q5584396 | change WD
1159150217 | Q330208 | Q22062839 | change WD
1159134277 | Q170024 | Q2126436 | change WD
1159113499 | Q200441 | Q80561 | redundant records at this location - agree with changing   wikidata id, recommend deleting record ﻿1159135187, recommend changing name   to Antakya (https://en.wikipedia.org/wiki/Antakya)
1159135187 | Q200441 | ? | see above row - recommend deletion
1159138309 | Q4111395 | Q20148488 | change WD
1159138313 | Q2652276 | Q2528602 | change WD
1159139183 | Q1149302 | Q221734 | change name to Rason (changed 2000), change WD
1159139193 | Q224982 | Q109356 | recommend deletion - has been incorporated into Hamhung and   geometry is located in water
1159144565 | Q172902 | Q241116 | change name to Şirvan, nameascii to Shirvan, change WD
1159149873 | Q116656 | Q1211183 | change WD, no change to name

@mizmay

**Comment by mizmay** [comment]
AFTER

|      NE_ID|NAME                 |NAMEASCII            |NAMEALT         |WIKIDATAID |
|----------:|:--------------------|:--------------------|:---------------|:----------|
| 1159113499|Antakya              |Antakya              |Antioch         |Q80561     |
| 1159130545|Chuquicamata         |Chuquicamata         |NA              |Q55342984  |
| 1159132375|Oymyakon             |Oymyakon             |Oimekon         |Q192098    |
| 1159134277|Ras al Khaymah       |Ras al Khaymah       |Ra's Al-Khaymah |Q2126436   |
| 1159134373|Thung Song           |Thung Song           |NA              |Q15199303  |
| 1159134475|Hua Hin              |Hua Hin              |NA              |Q667576    |
| 1159134483|Samut Prakan         |Samut Prakan         |NA              |Q13139252  |
| 1159136041|Chilca               |Chilca               |NA              |Q16890238  |
| 1159138309|Villa Ahumada        |Villa Ahumada        |NA              |Q20148488  |
| 1159138313|Ciudad Camargo       |Ciudad Camargo       |NA              |Q2528602   |
| 1159139183|Rason                |Rason                |Sonbong         |Q221734    |
| 1159139891|Makale               |Makale               |NA              |Q57079173  |
| 1159143805|Chapleau             |Chapleau             |NA              |Q2957549   |
| 1159144565|Shirvan              |Shirvan              |Ali Bayramli    |Q241116    |
| 1159146177|Miaoli               |Miaoli               |NA              |Q701651    |
| 1159147191|Warangal             |Warangal             |NA              |Q25563103  |
| 1159147325|Gorakhpur            |Gorakhpur            |NA              |Q5584396   |
| 1159149079|Tarawa               |Tarawa               |NA              |Q131233    |
| 1159149873|Xigaze               |Xigaze               |NA              |Q1211183   |
| 1159150217|Vitória da Conquista |Vitoria da Conquista |NA              |Q22062839  |
| 1159150235|Peace River          |Peace River          |NA              |Q1743985   |

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
