### ISSUE TITLE
wikidata | 10m populated_places | extreme distance candidates .. for debug 

### ISSUE THREAD

**Issue by ImreSamu** [nvkelso/natural-earth-vector#460]
case:  "no wikidata yet"   AND  the best proposal in the wikidata is too far ..
* probably needs a deeper debugging  ( double checking the coordinates in NE  and/or Wikidata ... )

|ne_id	| min_zoom | ne_name	 |   best candidate in wikidata  |_distance_category |
| ------| ---------| ------------| ----------------------------------| ------------------|
|1159130147| 7	 | Shashi |	Shashi	https://www.wikidata.org/wiki/Q11139987	|	250-300km |
|1159130281| 7	 | Shangdu |	Shangdu	https://www.wikidata.org/wiki/Q10868289	|	250-300km |
|1159133655| 6.1 | Chaguaramas |	Chaguaramas	https://www.wikidata.org/wiki/Q1058829	|	100-150km |
|1159135963| 6.7 | Sechura |	Sechura	https://www.wikidata.org/wiki/Q3236446	|	250-300km |
|1159137527| 6.7 | Yamburg |	Yamburg	https://www.wikidata.org/wiki/Q1679866	|	250-300km |
|1159139657| 6.7 | Hechi |	Hechi	https://www.wikidata.org/wiki/Q572089	|	250-300km |
|1159139779| 8	 | Pati |	Pati	https://www.wikidata.org/wiki/Q4554019	|	200-250km |
|1159141037| 6.1 | Fuyu |	Fuyu	https://www.wikidata.org/wiki/Q185940	|	100-150km |
|1159142075| 6.7 | Lagunas  | Lagunas	https://www.wikidata.org/wiki/Q1800551	|	300-400km |
|1159144693| 6.7 | Cacolo	  | Cacolo	https://www.wikidata.org/wiki/Q1620901	|	300-400km |
|1159148383| 6	 | Kotabumi |	Kotabumi	https://www.wikidata.org/wiki/Q14635420	|	100-150km |
|1159148559| 6	 | Chanaral |	Chañaral	https://www.wikidata.org/wiki/Q3763	|	300-400km |
|1159148783| 6	 | Aripuana |	Aripuanã	https://www.wikidata.org/wiki/Q1805412	|	150-200km |

EDIT:   better  -->  #334 
|1159139297| 6.7 | Bol'sheretsk |	Bolsheretsk	https://www.wikidata.org/wiki/Q16268949	|	080-090km |

**Comment by nvkelso** [comment]
Scheduled for 5.1

**Comment by nvkelso** [comment]
I think for **Bol'sheretsk**  the existing `Q2502620` via #334 is okay as-is.

**Comment by elliotap** [comment]
Verified - see table below for proposed changes @mizmay 


ne_id | ne_name | best candidate in wikidata | link | _distance_category | Recommendation
-- | -- | -- | -- | -- | --
1159148783 | Aripuana | Aripuanã | https://www.wikidata.org/wiki/Q1805412 | 150-200km | move geometry to -10.17666,-59.44387, add WD (confirmed with   google & OSM, see   https://www.openstreetmap.org/node/343588838#map=17/-10.17666/-59.44387)
1159144693 | Cacolo | Cacolo | https://www.wikidata.org/wiki/Q1620901 | 300-400km | add WD - first WD location is incorrect, second is correct,   distance is calculated on first location
1159133655 | Chaguaramas | Chaguaramas | https://www.wikidata.org/wiki/Q1058829 | 100-150km | move geometry to 9.33597,-66.25448, add WD (confirmed with   google and OSM, see:   https://www.openstreetmap.org/node/3846781260#map=17/9.33597/-66.25448)
1159148559 | Chanaral | Chañaral | https://www.wikidata.org/wiki/Q3763 | 300-400km | move geometry to -26.34810,-70.62147, add WD, (confirmed with   google and OSM,   see:https://www.openstreetmap.org/node/214189440#map=18/-26.34810/-70.62147)
1159141037 | Fuyu | Fuyu | https://www.wikidata.org/wiki/Q185940 | 100-150km | Fuyu is a county-level city under the administration of   prefecture-level city Songyuan. Geometry right now is located at Songyuan.   Recommend changing feature to represent Songyuan, population 495900,   wikidataid=Q92364
1159139657 | Hechi | Hechi | https://www.wikidata.org/wiki/Q572089 | 250-300km | move geometry to 24.695252134251945, 108.08299950401414, add   WD (confirmed with google & OSM, see   https://www.openstreetmap.org/node/5729719789)
1159148383 | Kotabumi | Kotabumi | https://www.wikidata.org/wiki/Q14635420 | 100-150km | better WD -> Q10372500
1159142075 | Lagunas | Lagunas | https://www.wikidata.org/wiki/Q1800551 | 300-400km | cannot verify - no action
1159139779 | Pati | Pati | https://www.wikidata.org/wiki/Q4554019 | 200-250km | better WD -> Q4135102
1159135963 | Sechura | Sechura | https://www.wikidata.org/wiki/Q3236446 | 250-300km | appears to be a phantom feature, actual Sechura is far away   (https://www.openstreetmap.org/node/2505711675) and no nearby populated   places - recommend deletion/deprecation
1159130281 | Shangdu | Shangdu | https://www.wikidata.org/wiki/Q10868289 | 250-300km | This feature appears to generalize a county - best match for   county would be Q1305772
1159130147 | Shashi | Shashi | https://www.wikidata.org/wiki/Q11139987 | 250-300km | Feature represents a district of prefecture-level city   Jingzhou - name should change to Jingzhou, better WD -> Q71247,   (see:https://www.openstreetmap.org/node/244080788)
1159137527 | Yamburg | Yamburg | https://www.wikidata.org/wiki/Q1679866 | 250-300km | move geometry to 67.92211738288061, 74.92531301724216, add WD   (confirmed with google and OSM,   see:https://www.openstreetmap.org/node/1349074061)

**Comment by nvkelso** [comment]
Fixed via #508, #510, #515 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
