### ISSUE TITLE
wikidata | 10m populated_places | other proposals ... 

### ISSUE THREAD

**Issue by ImreSamu** [nvkelso/natural-earth-vector#461]
| ne_id	   | min_zoom |	featurecla	| ne_name |	proposal wd_id |
| ---------- | --- | ------------------ | ----------  | ---------------------------------- | 
| 1159139143 | 6.7 | 	Admin-1 capital | Xiangkhoang |	Xieng Khouang	https://www.wikidata.org/wiki/Q2597463 |
| 1159140703 | 6.1 |	Populated place | Gar | Gar Chongsar	https://www.wikidata.org/wiki/Q5524556 |
| 1159140801 | 6.7 |	Populated place | Zhijiang | Zhijiang Town	https://www.wikidata.org/wiki/Q14297991 |

1159145189 | 6.7 | Populated place | Mohembo 
* East or West ?
  * Mohembo East : https://www.wikidata.org/wiki/Q171096 https://www.openstreetmap.org/node/294528373
  * Mohembo West : https://www.wikidata.org/wiki/Q171089 https://www.openstreetmap.org/node/2467637562

1159148437 |	6	| Admin-1 capital |	El Kharga
* now:	https://www.wikidata.org/wiki/Q428570	( Kharga Oasis )
* proposal: "el-Kharga Town"	https://www.wikidata.org/wiki/Q4063326 

1159126925 |	8	| Admin-1 capital |	Umm al Qaywayn	
* now: https://www.wikidata.org/wiki/Q175021 ( one of the seven emirates of the United Arab Emirates )	
* proposal: https://www.wikidata.org/wiki/Q2788830 ( human settlement in United Arab Emirates )
  * https://en.wikipedia.org/wiki/Umm_al-Quwain_(city) 

1159146095 | 6.1 | Scientific station | Escudero Base
* proposal: https://www.wikidata.org/wiki/Q2714138

1159146863 | 6 | Populated place | Oktyabrskiy
* proposal: https://www.wikidata.org/wiki/Q1691320 

1159148901 | 6 | Populated place | Lansdowne House
* proposal: https://www.wikidata.org/wiki/Q14875338 
 * "Neskantaga First Nation (formerly known as Lansdowne House Indian Band)"
   * https://en.wikipedia.org/wiki/Neskantaga_First_Nation 

1159148779 | 6 | Populated place | Mato Grosso
 * proposal: "Vila Bela da Santíssima Trindade"	https://www.wikidata.org/wiki/Q732088
  * "Vila Bela da Santíssima Trindade is a Brazilian municipality in Mato Grosso with 14,523 inhabitants"

1159129673 | 7 | Populated place | Pakhachi	
 * proposal: Pakhatsji	https://www.wikidata.org/wiki/Q4347325

1159129551 | 7 | Populated place | Aqadyr
* proposal: https://www.wikidata.org/wiki/Q4056543

1159129085 | 7 | Populated place | Omchak		
* proposal: https://www.wikidata.org/wiki/Q14545882

1159128511 | 7 | Populated place | Zvezdnyy
* proposal: Zvëzdnyj	https://www.wikidata.org/wiki/Q2305684

1159126955 | 6 | Populated place | Gyzlarbat
* proposal:	 "Serdar"	https://www.wikidata.org/wiki/Q1015618 
 * "Serdar (formerly Kyzyl-Arvat or Gyzylarbat) is a location in Turkmenistan,"
 * https://en.wikipedia.org/wiki/Serdar_(city)

EDIT: 

dups .. first  proposal in #455 
~~1159130275 | 7 | Populated place | Ergun Zuoqi~~
~~* proposal: Genhe	https://www.wikidata.org/wiki/Q1354108~~
~~* https://en.wikipedia.org/wiki/Genhe formerly "Ergun Left Banner" or "Ergun Zuoqi"~~

dups .. first proposal in #453 
~~1159134263 | 6.7 | Populated place | Rida~~    Same is included in the current proposal:  "Fix_10m_Populated_Places_WikidataIDs.R"
~~* proposal: Rada'a	https://www.wikidata.org/wiki/Q2125362~~
~~  * https://www.openstreetmap.org/node/5587743988 alt_name="Redā‘; Rida`; Ridā‘; Reda`"~~

**Comment by nvkelso** [comment]
Thank you, these all look promising! Are you using the scripts as before or manually reviewing?

Please note: With New Years Eve my responses will be delayed the next couple days.

**Comment by ImreSamu** [comment]
>  Are you using the scripts as before or manually reviewing?

both of them
* now I am refreshing the "old" scripts ( adding `ne_id`,  updating wikidata taxonomies , ...   +  still working on the WOF scripts ...  )
* AND  manually checking the results  ( including low scored suggestions )  

my wikidata-ne suggestions ( multiple issues in the last few days )
~ 90%  based on scripts results  
~ 10%  based on manually debugging strange cases ... 

imho:  it is a high quality .. but not perfect ... so need a 3rd party review ..  ( I have my own bias .. )

**Comment by nvkelso** [comment]
Scheduling this for 5.1

**Comment by nvkelso** [comment]
These look good to me.

**Comment by elliotap** [comment]
Verified - proposed changes below @mizmay 


NE ID | Former WD | Proposed WD | Recommended Action
-- | -- | -- | --
1159139143 |   | Q2597463 | this town is no longer the admin-1 capital - feature should be   moved to 19.451895771215643, 103.19599722986072, name changed to Phonsavan   (https://en.wikipedia.org/wiki/Phonsavan), population changed to 37507, WD   changed to Q1011711
1159140703 |   | Q5524556 | resolved in #339
1159140801 |   | Q14297991 | add WD
1159145189 |   | Q171089 | add WD
1159148437 | Q428570 | Q4063326 | change WD
1159126925 | Q175021 | Q2788830 | change WD
1159146095 |   | Q2714138 | add WD
1159146863 |   | Q1691320 | add WD, change population to 1534   (https://ru.wikipedia.org/wiki/%D0%9E%D0%BA%D1%82%D1%8F%D0%B1%D1%80%D1%8C%D1%81%D0%BA%D0%B8%D0%B9_(%D0%9A%D0%B0%D0%BC%D1%87%D0%B0%D1%82%D1%81%D0%BA%D0%B8%D0%B9_%D0%BA%D1%80%D0%B0%D0%B9))
1159148901 |   | Q14875338 | resolved in #333
1159148779 |   | Q732088 | change name to "Vila Bela da Santíssima Trindade",   add WD, change population to 16271
1159129673 |   | Q4347325 | add WD
1159129551 |   | Q4056543 | add WD
1159129085 |   | Q14545882 | add WD
1159128511 |   | Q2305684 | add WD, change name to Zvëzdnyj
1159126955 |   | Q1015618 | add WD, change name to Serdar

**Comment by mizmay** [comment]
BEFORE

(only those that are changing per @elliotap's comments above, so 1159148901 and 1159140703 excluded)

|      NE_ID|NAME           |NAMEASCII      |NAMEPAR |NAMEALT        |WIKIDATAID |     WOF_ID|FEATURECLA         | POP_MAX| POP_MIN| POP_OTHER|
|----------:|:--------------|:--------------|:-------|:--------------|:----------|----------:|:------------------|-------:|-------:|---------:|
| 1159126925|Umm al Qaywayn |Umm al Qaywayn |NA      |Umm Al Qaywayn |Q175021    |  890455645|Admin-1 capital    |   44411|   32651|     32651|
| 1159126955|Gyzlarbat      |Gyzlarbat      |NA      |NA             |NA         |  421168645|Populated place    |   48458|   12000|     52689|
| 1159128511|Zvezdnyy       |Zvezdnyy       |NA      |NA             |NA         | 1141906445|Populated place    |      10|      10|         0|
| 1159129085|Omchak         |Omchak         |NA      |NA             |NA         | 1141906475|Populated place    |      10|      10|         0|
| 1159129551|Aqadyr         |Aqadyr         |NA      |NA             |NA         |  421175805|Populated place    |    9710|    1009|      1009|
| 1159129673|Pakhachi       |Pakhachi       |NA      |NA             |NA         | 1141906511|Populated place    |      10|      10|         0|
| 1159139143|Xiangkhoang    |Xiangkhoang    |NA      |NA             |NA         | 1141907459|Admin-1 capital    |    5189|    5189|         0|
| 1159140801|Zhijiang       |Zhijiang       |NA      |NA             |NA         | 1141907681|Populated place    |  113907|  113907|    113594|
| 1159145189|Mohembo        |Mohembo        |NA      |NA             |NA         | 1141908261|Populated place    |     757|     757|         0|
| 1159146095|Escudero Base  |Escudero Base  |Chile   |NA             |NA         | 1141908413|Scientific station |      20|      20|         0|
| 1159146863|Oktyabrskiy    |Oktyabrskiy    |NA      |NA             |NA         | 1141908609|Populated place    |   67386|   67386|     66801|
| 1159148437|El Kharga      |El Kharga      |NA      |El-Kharga      |Q428570    | 1141908931|Admin-1 capital    |   49991|   49991|     49991|
| 1159148779|Mato Grosso    |Mato Grosso    |NA      |NA             |NA         | 1141909013|Populated place    |    1612|    1612|      1612|

**Comment by mizmay** [comment]
Nice work @elliotap!

I followed along and annotated with comments where I incorporated these changes in the PR, the only thing I saw worth mentioning is that in the Wikidata entry for Serdar (Q1015618), there are two "Also known as" entries, Gyzylarbat and Kyzyl-Arvat. I set NAMEALT to Gyzylarbat, as this was the previous value, but weigh in if NAMEALT/NAMEPAR should be assigned differently.

**Comment by elliotap** [comment]
I took a look at google scholar instances for both, and both return meaningful results. In publications since 1980, Kyzyl-Arvat looks to be preferred to Gyzylarbat as a spelling/stylization by about 2:1 

I'd speculate the variation stems from Turkmenistan using arabic, latin, and cyrillic alphabets in the 20th century (https://en.wikipedia.org/wiki/Turkmen_alphabet)

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
