### ISSUE TITLE
wikidata | ne_10m_airports

### ISSUE THREAD

**Issue by ImreSamu** [nvkelso/natural-earth-vector#463]
proposed changes:

**1159116365 | Airport | Kanpur**	    
* now: https://www.wikidata.org/wiki/Q10852571 ( closed! )
* proposed: Kanpur Airport	https://www.wikidata.org/wiki/Q6364347
  * please modify the GPS code in the NE table !

**1159119791 | Airport | Kunming Wujiaba Int'l**
* now:	https://www.wikidata.org/wiki/Q1190274  ( Closed in 2012! )	
* proposal: "Kunming Changshui International Airport"	https://www.wikidata.org/wiki/Q1371636		
  * please modify the GPS code in the NE table !

**Comment by elliotap** [comment]
Kanpur Airport - Verified

Compare to Google:
<img width="1142" alt="Screen Shot 2021-03-11 at 10 56 47 AM" src="https://user-images.githubusercontent.com/64806657/110839680-b0ceae00-8258-11eb-93f6-573af8c6ca81.png">
OpenStreetMap:
<img width="1145" alt="Screen Shot 2021-03-11 at 10 56 32 AM" src="https://user-images.githubusercontent.com/64806657/110841841-42d7b600-825b-11eb-9b03-634d39147568.png">

Proposed Changes:
Move feature to 26.40602949633114, 80.41638444526912
Change attribute wikidataid from Q10852571 to Q6364347
ICAO code remains VIKA per wikipedia

Kunming Wujiaba Int'l - Verified

Compare to Google (does not have feature):
<img width="1680" alt="Screen Shot 2021-03-11 at 11 24 28 AM" src="https://user-images.githubusercontent.com/64806657/110842747-5f282280-825c-11eb-8904-3b7d23333902.png">
Apple:
<img width="1398" alt="Screen Shot 2021-03-11 at 11 24 07 AM" src="https://user-images.githubusercontent.com/64806657/110842772-64856d00-825c-11eb-934b-228f4cb1a515.png">
OpenStreetMap:
<img width="1148" alt="Screen Shot 2021-03-11 at 11 17 01 AM" src="https://user-images.githubusercontent.com/64806657/110842809-6c451180-825c-11eb-8d14-1b6ce3d67e07.png">


Proposed Changes:
Move feature to 25.1058147939695, 102.93175617376069
Increase scalerank - **What is appropriate rank for 45m passengers (top 50 in world)?** 
Change attribute name from Kunming Wujiaba Int'l to Kunming Changshui Int'l
Change attribute wikidataid from Q1190274 to Q1371636
IATA/ICAO codes remain KMG/ZPPP per wikipedia

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/509.
