### ISSUE TITLE
Feature request: canals and waterways

### ISSUE THREAD

**Issue by Maxszik** [nvkelso/natural-earth-vector#466]
Without canals and man-made waterways, Natural Earth feels sort of incomplete. It would be truly useful to have, in order to render a complete map.

I remember reading from the maintainer of Natural Earth somewhere long ago, that this data seemed impossible to find. Can it still be so?

**Comment by nvkelso** [comment]
Great idea! Do you have any data or research time to contribute for canals?

**Comment by nvkelso** [comment]
This is a dupe of https://github.com/nvkelso/natural-earth-vector/issues/15.
