### ISSUE TITLE
10m populated places: location precision for Windsor, Ontario

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#468]
Windsor, Ontario, id 1159147661, is currently located on the USA side of the USA/Canada border at 42.33329327300,-83.03334029310

Requesting slight adjustment to move feature across the border to 42.311024115116965, -83.0349099770059 or thereabouts.

https://www.openstreetmap.org/#map=11/42.3118/-83.0285

![image](https://user-images.githubusercontent.com/64806657/104665381-ff5f3200-5685-11eb-86f8-00f82d28db89.png)

**Comment by nvkelso** [comment]
Yikes!

**Comment by elliotap** [comment]
Confirmed

Compare to Google:
<img width="1680" alt="Screen Shot 2021-03-05 at 10 08 08 AM" src="https://user-images.githubusercontent.com/64806657/110155723-e37d3000-7d9a-11eb-99e0-a222e63684fa.png">

Apple:
<img width="1398" alt="Screen Shot 2021-03-05 at 10 07 39 AM" src="https://user-images.githubusercontent.com/64806657/110155744-e8da7a80-7d9a-11eb-9316-6a6405828613.png">

OpenStreetMap:
<img width="1680" alt="Screen Shot 2021-03-05 at 10 07 24 AM" src="https://user-images.githubusercontent.com/64806657/110155756-ed9f2e80-7d9a-11eb-9a4e-59a312d3e24a.png">


Proposed edits:
Move geometry to 42.315457041007065, -83.03685247914979
Change latitude to 42.315457041007065
Change longitude to  -83.03685247914979

**Comment by nvkelso** [comment]
Move sounds good!

The name of the feature is already correct? The issue title spelling is off.

**Comment by elliotap** [comment]
Shoot! That was a typo on my part

**Comment by mizmay** [comment]
BEFORE

|      NE_ID|NAME | LATITUDE| LONGITUDE|
|----------:|:----|--------:|---------:|
| 1159146401|Bodø | 67.27643|  14.42928|

**Comment by mizmay** [comment]
AFTER

|      NE_ID|NAME    | LATITUDE| LONGITUDE|
|----------:|:-------|--------:|---------:|
| 1159147661|Windsor | 42.31546| -83.03685|

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
