### ISSUE TITLE
QGIS mistakenly depicting the Crimean peninsula

### ISSUE THREAD

**Issue by olekrd7** [nvkelso/natural-earth-vector#469]
QGIS app based on the most recent large scale countries (version 4.1.0) from natural earth data for some reason depicts and defines Crimea and the entire peninsula as part of Russia although the UN, OSCE, EU and many other international organizations have not recognized the occupation of Crimea by Russia. Hence, according to the international law in the app Crimea should be depicted as part of Ukraine. Whom should I inform about this issue?

**Comment by nvkelso** [comment]
Can you attach a screenshot, please?

**Comment by jmikola** [comment]
@nvkelso: This appears to be the same issue reported in #401, #390, #391, which are currently being tracked in your [v5.0.0 milestone](https://github.com/nvkelso/natural-earth-vector/milestone/5).

**Comment by nvkelso** [comment]
I agree, but am curious about the QGIS part and if something there will need an update, too, once v5 of Natural Earth is released.

**Comment by Andrettin** [comment]
@nvkelso I don't think it has anything to do with QGIS, it was probably just the app they happened to use to open it. The Natural Earth country map seems to generally follow the de facto situation rather than de jure, as can be seen e.g. in Western Sahara as well.

**Comment by olekrd7** [comment]
@Andrettin, indeed, it is more relater to the Natural Earth creators, not to qgis specifically. do you know whom I should contact fron Natural earth regarding this matter? I see there were previously discussions in this forum regarding their approach, but it indeed distorts the international law

**Comment by nvkelso** [comment]
Closing in favor of the earlier issues #401, #390, #391, which are currently being tracked in the v5.0.0 milestone already.
