### ISSUE TITLE
Website replaced with SEO/website design page

### ISSUE THREAD

**Issue by pnorman** [nvkelso/natural-earth-vector#470]
http://naturalearthdata.com/ is not returning the Natural Earth website

**Comment by SomeoneElseOSM** [comment]
CDN seems unaffected, so https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip appears to be still there (and the same file as it was the last time this problem occurred)

**Comment by nvkelso** [comment]
Looks like the web host changed serves again. I’ll ping them...

In the meantime file hosting was approved for AWS, I plan on setting that up in Feb.

**Comment by nvkelso** [comment]
The secure site works now after updating A record IP address (the server moved again): https://www.naturalearthdata.com/

The unsecure http://naturalearthdata.com still shows the other content (see below).

The https link works fine and is recommended:
- https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip
- (note https and http//www above)


![image](https://user-images.githubusercontent.com/853051/106371292-9cbd9580-6317-11eb-875f-d6a79eac6adf.png)

**Comment by nvkelso** [comment]
The redirect from http to https seems to work again (took longer to propagate). Closing.
