### ISSUE TITLE
Two Lake Onega features in Lakes + Reservoirs (110m)

### ISSUE THREAD

**Issue by Drumstick42** [nvkelso/natural-earth-vector#472]
I opened up the most recent version of the 110m lakes and reservoirs data set in QGIS. In the attribute table for the layer, there are two entries for Lake Onega. One is in Russia, and the other is in the continental U.S. Judging by the lat/lon of the feature in the U.S., Salt Lake is incorrectly labeled as Lake Onega.

**Comment by MrGawsome** [comment]
I can confirm that the duplicate Lake Onega is in fact supposed to be the Great Salt Lake. We should update ne_id 1159113251 to be the Great Salt Lake using wikidata Q178741 (https://www.wikidata.org/wiki/Q178741). See below for an image of this duplicate (the lake is zoomed out for context):

![image](https://user-images.githubusercontent.com/78829897/111015501-eb6e3e80-835d-11eb-9d64-defeaa4f4254.png)

**Comment by nvkelso** [comment]
Uff how did that happen!? I agree with the proposed change:

For feature **ne_id** = `1159113251` in the 110m lakes theme:

**name** = `Great Salt Lake`
**name_abb** = `Great Salt L.`
**label** = `Great Salt Lake`
**wikidata** = `Q178741`

All the name localizations would update with the general "update wikidata names script" before cutting the release – those don't need to be updated in the PR associated with this issue.

_NOTE: generally lakes names shouldn't include `Lake` in the **name** field... but seems like this 110 theme doesn't follow that practice yet? That's a different issue._

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/525.
