### ISSUE TITLE
Add more 50m data for states/province (like 10m theme)

### ISSUE THREAD

**Issue by anandtiwary** [nvkelso/natural-earth-vector#479]

**Comment by nvkelso** [comment]
The short answer is `no` for two reasons:

- The admin-1 changes a surprising amount of time and it's hard enough to keep the 1:10m theme updated.
- Most admin-1 in the world are too small to be meaningfully displayed at 1:50m scale – like they are only 1 to 20 pixels big. 

Longer answer: I do think it would be useful to have _more_ admin-1 included at 1:50m scale for the largest geographic countries. Say:

- US (already included)
- Canada
- Brazil
- India
- China
- Russia
- Australia
- South Africa

What's your use case? What countries would you include?

**Comment by anandtiwary** [comment]
Yeah. If we can include those countries then it would be great. I want to provide more granular markers in our geo map at least the bigger countries.

Is this something we can generate from 10m data? Happy to collaborate on this if you could guide/give a direction.

**Comment by anandtiwary** [comment]
@nvkelso Could you please help in including those countries data at 50m scale?

**Comment by nvkelso** [comment]
If you want to run the 10m boundary lines thru mapshaper to match the 50m simplification, and work on getting their polygons to build, that'd be helpful! But it'll likely be for v5.1 release.

**Comment by nvkelso** [comment]
Bringing this into the v5 milestone as it's implicated in the admin-0, admin-1 POV work.

![image](https://user-images.githubusercontent.com/853051/128626506-5e6dbec7-0ea2-4474-a39d-5da950039b89.png)

**Comment by nvkelso** [comment]
Fixed via a0077ee839a3b689a9671c596fc37b34412bb285 and 7de76f1f5c7c9772afb70eea55ccc00532b43c9f and c152ce7a7d5e9f7c43654a863a5b69b6bf706a2a in v5-prequel branch with PR #446.

Added 50m admin-1 for CHN, IDN, IND, RUS, ZAF.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/446.
