### ISSUE TITLE
countries10 pop_est year 2017 for Papua New Guinea incorrect

### ISSUE THREAD

**Issue by kiwibrew** [nvkelso/natural-earth-vector#481]
The 2017 population estimate for Papua New Guinea is stated in this data set as 6,909,701.
The UN's 2017 population estimate for PNG is 8,438,036.

**Comment by nvkelso** [comment]
I'm updating all the countries per World Bank population and GDP at the moment. The new population estimate per World Bank will be `8,776,109` circa 2019.

**Comment by nvkelso** [comment]
Via 0fdbda702479e7fe2c0ed91d6276e5da688171a2.

**Comment by nvkelso** [comment]
In the associated PR:

![image](https://user-images.githubusercontent.com/853051/121847405-60bf1780-cc9d-11eb-9be9-bd49ebb84684.png)

**Comment by kiwibrew** [comment]
Hey there, thanks for the update. Just wondering how/when this flows through to what's published here:
http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip

I pulled this into R a moment ago to check & the file date is 21 May 2018.

**Comment by nvkelso** [comment]
Once the whole v5 release is done then it'll be published. I expect that to be in July this year.

Unfortunately it's hard to push updates to single themes as they often implicate other themes and this release in particular has gotten a little unwieldy and long in the tooth. Shakes hand in the air at 2020 and COVID.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/446.
