### ISSUE TITLE
ne_10m_roads: incorrect attributes on a segment of I-94 in North Dakota

### ISSUE THREAD

**Issue by almccon** [nvkelso/natural-earth-vector#482]
I was filtering `ne_10m_roads` to show only interstates by doing `"level" = 'Interstate' AND "sov_a3" = 'USA'` in QGIS, and I noticed a gap in the road network in North Dakota.

It turns out there's a segment of I-94 that is tagged as name "83" instead of "94", and with "level" = "Federal" instead of "Interstate".

<img width="1146" alt="Screen Shot 2021-02-25 at 7 26 24 PM" src="https://user-images.githubusercontent.com/1212178/109250993-83392d80-779f-11eb-9717-fb2d75200318.png">
<img width="1348" alt="Screen Shot 2021-02-25 at 7 26 44 PM" src="https://user-images.githubusercontent.com/1212178/109251020-94823a00-779f-11eb-8715-c0d7ce4f6691.png">

**Comment by elliotap** [comment]
Verified - road path described here: https://en.wikipedia.org/wiki/Interstate_94_in_North_Dakota

On-the-ground signage observed in Mapillary:
Westbound from Fargo: 
<img width="1680" alt="Screen Shot 2021-03-09 at 12 08 25 PM" src="https://user-images.githubusercontent.com/64806657/110532181-60791400-80d1-11eb-9977-89683e5852b9.png">
Eastbound from Bismarck:
<img width="1680" alt="Screen Shot 2021-03-09 at 12 18 54 PM" src="https://user-images.githubusercontent.com/64806657/110532437-a7ffa000-80d1-11eb-9e23-8361d45d4ed8.png">


Proposed Edits:
same as almcon's proposal
Change name from 83 to 94
Change level from Federal to Interstate

**Comment by nvkelso** [comment]
Works for me!

**Comment by nvkelso** [comment]
Fixed via #504.
