### ISSUE TITLE
10m populated places: Request to update name for Kuwait City

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#483]
for feature 1159151361, requesting to update name value from "Kuwait" to "Kuwait City" - this appears to be the customary English name for the place 

Sources:
AP files from Kuwait City: https://apnews.com/hub/kuwait-city
https://en.wikipedia.org/wiki/Kuwait_City
https://www.geonames.org/285787/kuwait-city.html

**Comment by elliotap** [comment]
Sources in issue suggest name change.

Comparison to Apple:
<img width="1398" alt="Screen Shot 2021-03-04 at 3 02 48 PM" src="https://user-images.githubusercontent.com/64806657/110042550-c98c1080-7cfa-11eb-95ba-f97d535a65aa.png">

Google:
<img width="1680" alt="Screen Shot 2021-03-04 at 3 04 07 PM" src="https://user-images.githubusercontent.com/64806657/110042617-e58fb200-7cfa-11eb-92d4-5c748b8405ca.png">

OpenStreetMap:
<img width="1680" alt="Screen Shot 2021-03-04 at 3 05 14 PM" src="https://user-images.githubusercontent.com/64806657/110042727-0bb55200-7cfb-11eb-9792-1451a8dde837.png">


Proposed attribute changes: 
name from Kuwait to Kuwait City
namealt from Al Kuwayt|Kuwait City to Al Kuwayt (to avoid redundancy)

**Comment by nvkelso** [comment]
Keep researching these, please. But hold off on PR for populated places for a couple days to let me wrap up Stephanie’s changes and for #5.

**Comment by mizmay** [comment]
@elliotap if you want I can hoover this one up in my next round of name edits, feel free to assign it to me if you do.

**Comment by mizmay** [comment]
Recommendations & research above make sense to me!

BEFORE

|      NE_ID|NAME   |NAMEPAR |NAMEALT                    |NAMEASCII |SOV0NAME |ADM0NAME |ADM1NAME  |MEGANAME                |LS_NAME |NAME_EN     |NAME_DE      |NAME_ES          |NAME_FR |NAME_PT |NAME_RU |NAME_ZH |NAME_AR |NAME_BN |NAME_EL |NAME_HI |NAME_HU |NAME_ID |NAME_IT |NAME_JA |NAME_KO |NAME_NL |NAME_PL |NAME_SV |NAME_TR |NAME_VI |
|----------:|:------|:-------|:--------------------------|:---------|:--------|:--------|:---------|:-----------------------|:-------|:-----------|:------------|:----------------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|
| 1159151361|Kuwait |NA      |Al Kuwayt&#124;Kuwait City |Kuwait    |Kuwait   |Kuwait   |Al Kuwayt |Al Kuwayt (Kuwait City) |Kuwait  |Kuwait City |Kuwait-Stadt |Ciudad de Kuwait |Koweït  |Kuwait  |Кувейт  |科威特  |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |

**Comment by mizmay** [comment]
AFTER

|      NE_ID|NAME        |NAMEPAR |NAMEALT   |NAMEASCII   |SOV0NAME |ADM0NAME |ADM1NAME  |MEGANAME                |LS_NAME |NAME_EN     |NAME_DE      |NAME_ES          |NAME_FR |NAME_PT |NAME_RU |NAME_ZH |NAME_AR |NAME_BN |NAME_EL |NAME_HI |NAME_HU |NAME_ID |NAME_IT |NAME_JA |NAME_KO |NAME_NL |NAME_PL |NAME_SV |NAME_TR |NAME_VI |
|----------:|:-----------|:-------|:---------|:-----------|:--------|:--------|:---------|:-----------------------|:-------|:-----------|:------------|:----------------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|
| 1159151361|Kuwait City |NA      |Al Kuwayt |Kuwait City |Kuwait   |Kuwait   |Al Kuwayt |Al Kuwayt (Kuwait City) |Kuwait  |Kuwait City |Kuwait-Stadt |Ciudad de Kuwait |Koweït  |Kuwait  |Кувейт  |科威特  |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
