### ISSUE TITLE
Documentation to explain how to change the language of the names

### ISSUE THREAD

**Issue by mayeulk** [nvkelso/natural-earth-vector#484]
Some documentation should help the user of the QGIS package to change the language preferences. (Default is: Greek)
Something like, in a readme / documentation file:

_You can select your preferred language for labelling countries, cities, seas and other features.
To do so, in QGIS, once you have opened the Natural Earth project file (Natural_Earth_quick_start_for_QGIS_v3.qgs), 
select the menu "Project > Properties" then the "Variables" item on the left pane. Then, in the Project section, change the "project_language" variable.
For instance, for labels in French, replace the default value for the Project variable "project_language", which is "name_el", by "name_fr". You can also replace the "project_language_fallback" variable (a second language which used when no translation is found for the first language)._ 

Full list of allowed values should be given.
Useful links:
https://github.com/nvkelso/natural-earth-vector/blob/bf7720b54dd9ac2d4d7f735174901b3862b5362a/CHANGELOG#L45
https://www.naturalearthdata.com/blog/miscellaneous/natural-earth-v4-1-0-release-notes/

**Comment by nvkelso** [comment]
Good idea! On website and also go in a file in the QGIS package zip download. I'll consider to change the default to English, too.

**Comment by nvkelso** [comment]
Via https://github.com/nvkelso/natural-earth-vector/pull/446/commits/0c806175aaf32015ae1f855721ceadb72f62d513.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/446.
