### ISSUE TITLE
Add wikidata and name translations to recovered 50m lakes

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/natural-earth-vector#498]
In https://github.com/nvkelso/natural-earth-vector/issues/422 we discovered that v4 regressed the number of lakes in the 50m theme.

We can recover those geoms and feature properties from an earlier version, but they then are missing the wikidata IDs and name translations that were otherwise added in v4. 

Two options:

1.  Harvest the ne_id, wikidata IDs and localized names off the 10m lakes theme
2. Recalculate the ne_id, wikidata IDs, and localized names from scratch (paging @ImreSamu).

**Comment by nvkelso** [comment]
I think option 1 can probably be done in QGIS without too much trouble? What do you think @elliotap and @MrGawsome? Otherwise we'd love your help @ImreSamu (and would provide the missing `ne_id`)!

**Comment by elliotap** [comment]
option 1 sounds feasible, what do you think @MrGawsome?

**Comment by MrGawsome** [comment]
Option 1 sounds good to me as well

**Comment by nvkelso** [comment]
Cool, let's try option 1 soonish so if it doesn't work out @ImreSamu still has lead time.

**Comment by ImreSamu** [comment]
I have created a preliminary test match - based on the last week wikidata dump.
* all 405 records. ( without filter ,  known bad match included )
* ~65% looks OK for me.  ( +lot of type1/2 errors expected ) 
* -->  [results-google-sheets](https://docs.google.com/spreadsheets/d/1TtHLazrO2VxjfaI0-DSP5c-AviRgtCAwe04JYGhGNEY/edit?usp=sharing) 

columns : 
- ogc_fid ( from the shp file )
- ne_id ( temporary id,  generated myself .. ) 
- ne_name, ne_name_alt  : ne  lakes name - with `ne_` prefix
- **_suggested_wd_id  :  my proposal ( not always ok )**
- new_wd_label  :  proposed wikidata label 
- `_firstmatch_distance_category`  -  ne vs. wikidata distance ..   high distance -> bad 
   - `000-005km` - GOOD
   - `150-200km` - BAD
- `_matching_category`  my subjective category  
   -  `OK- ....`   looks good ( has a similar name )
   -  `MAYBE0 .. `  need check 
   -  `SUGGESTION1....`  no clear match .. maybe 
   -  `SUGGESTION2...`   probably a false match  
- **`_wd_candidate2` | `_wd_candidate3` | `_wd_candidate4` | `_wd_candidate5`   :  other wikidata candidates ..** 

If you find a strange wikidata - please also  correct in the wikidata site.
*  so fix/add the "Label/"Also known as"/"Instance of"/"coordinate location"/ etc

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/532.
