### ISSUE TITLE
South Sudan ISO Code

### ISSUE THREAD

**Issue by grijohn** [nvkelso/natural-earth-vector#501]
I make a lot of world maps and have noticed that the  3 character code used by Natural Earth for South Sudan (SDS) is not consistent with the three character ISO code SSD. It is a nuisance having to make the changes and some new users may not notice the problem.  Otherwise I think your data is great.

**Comment by nvkelso** [comment]
As you're trying to join data using ISO codes, please refer to the ISO columns and not the adm0_a3 codes which are peculiar to Natural Earth. The ISO columns already have the data you are looking for.

The v4 series has the following:

![image](https://user-images.githubusercontent.com/853051/120272059-43cc2280-c261-11eb-9707-e64d2b8e0628.png)

Which matches ISO:

- Alpha-2 code: `SS`
- Alpha-3 code: `SSD`
- Numeric code: `728`

The v5 series has the following:

![image](https://user-images.githubusercontent.com/853051/120272106-57778900-c261-11eb-833f-54eb6a80d84c.png)
