### ISSUE TITLE
Missing Tuvalu in 50M dataset

### ISSUE THREAD

**Issue by Bonurbe** [nvkelso/natural-earth-vector#511]
Hello,

I just downloaded the 50M dataset (countries and map sub-units) and both are missing Tuvalu which is an independent country like Nauru, Palau and other small island countries in the Pacific.

Thank you,
Bruno

**Comment by nvkelso** [comment]
Those tiny countries are in a separate download:

- https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_tiny_countries.zip

**Comment by Bonurbe** [comment]
Tuvalu is a sovereign country just like Nauru, Vatican City, Monaco, San Marino, ... and they are all part of the 50M Sovereignty dataset.

Can Tuvalu be added to it?

Thanks,
Bruno

**Comment by nvkelso** [comment]
@Bonurbe Can you tell me more about your use case? Are you doing thematic mapping my country (more typical) or sovereign country (extremely rare)? 

Also worth noting that in v5 of Natural Earth (in development) we'll support different "worldview" or "point-of-view" for administrative boundaries. Are you the right person at World Bank to add an organizational viewpoint (while the launch viewpoints are for per country audiences)?

**Comment by Bonurbe** [comment]
Yes, this is for thematic mapping. The idea is to link to the WB data and since Tuvalu is a sovereign country, we have lots of indicators for it to join but can't because it's not present in the main dataset.

In terms of boundaries and cartography, yes I'm in charge of the WB Cartography Unit and I can pass along our guidelines or way we cartography the world.

**Comment by nvkelso** [comment]
I can reproduce the problem and agree it should be fixed. Re-opening the issue and assigning to v5 milestone.

There is _land_ in the 50m theme for Tuvalu, but we're missing the equivalent admin_0 polygon in the `ne_50m_admin_0_scale_rank` theme. The land polygon should be copied over, and setup with basic properties that would result in it appearing in all the derived admin_0 themes, including `ne_50m_admin_0_counties` and `ne_50m_admin_0_sovereignty` (after running the `make mapshaper` target).

All other "tiny countries" that are point geometry are ALSO represented as polygons in the other admin_0 themes except Tuvalu, so we should meet that convention.

@Bonurbe Thanks for helping me understand this problem. Drop me an email at nvkelso@gmail.com so we can open a dialog about WB cartography guidelines? Having more direct linkage in the data as most of the population and GDP numbers in v5 are updated from WB now!

**Comment by nvkelso** [comment]
This remains outstanding.

**Comment by nvkelso** [comment]
Fix is in https://github.com/nvkelso/natural-earth-vector/commit/ec8bf0959b7e2bbc3735985c79ff4b6099ec971e which is part of PR #446.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/446.
