### ISSUE TITLE
Island detail level discrepancies between layers

### ISSUE THREAD

**Issue by FangedHedgehog** [nvkelso/natural-earth-vector#521]
I noticed that the ne_10_ocean is more detailed than ne_10m_land and ne_10m_bathymetry_L_0

![image](https://user-images.githubusercontent.com/83017751/115721715-9a9b2e00-a37e-11eb-916d-4696723d9ad4.png)
Example from Southern Sweden, Europe

**Comment by nvkelso** [comment]
Look at land scale rank with minor islands?
