### ISSUE TITLE
Uncaught TypeError: $(...).ready is not a function, Blocked loading mixed active content

### ISSUE THREAD

**Issue by matkoniecz** [nvkelso/natural-earth-vector#529]
To reproduce: 

(1) enable network log in FF from F12 menus.

(2) Go to https://www.naturalearthdata.com/downloads/10m-cultural-vectors/

found while investigating #528

There is earlier `Blocked loading mixed active content “http://www.naturalearthdata.com/dataTables/media/js/jquery.dataTables.js”`

**Comment by nvkelso** [comment]
This should be fixed now, server was in a bad PHP version state vis-a-vis WP plugins including the site theme.
