### ISSUE TITLE
https://www.naturalearthdata.com/wp-content/themes/NEV/ is 500ing

### ISSUE THREAD

**Issue by matkoniecz** [nvkelso/natural-earth-vector#530]
To reproduce: 

(1) enable network log in FF from F12 menus.

(2) Go to https://www.naturalearthdata.com/downloads/10m-cultural-vectors/

https://www.naturalearthdata.com/wp-content/themes/NEV/ is actually 500ing when I open it in FF

found while investigating #528

**Comment by hholzgra** [comment]
Getting 500 errors when trying to download files with wget or curl from the command line, too ...

**Comment by nvkelso** [comment]
This should be fixed now, server was in a bad PHP version state vis-a-vis WP plugins including the site theme.
