### ISSUE TITLE
"Add your own relief shading" - how?

### ISSUE THREAD

**Issue by edent** [nvkelso/natural-earth-vector#567]
I'm trying to create a South Up map. When I use the map with relief shading, things look weird:
<img src="https://user-images.githubusercontent.com/837136/126872746-6deadf51-8064-4d70-8f64-0f9f254ec516.png" width="300" /><img src="https://user-images.githubusercontent.com/837136/126872748-af77ca7f-28bb-4fe5-9289-1daf125465d7.png" width="300" />

[Natural Earth 1](https://www.naturalearthdata.com/downloads/10m-natural-earth-1/10m-natural-earth/) says:
>  Coloring based on land cover. Add your own relief shading.

How would I go about inverting the shading so it looks better on an "upside down" map?

(Thanks for the great resources - and sorry if this is a simple question.)

**Comment by tsmcgrath** [comment]
It's the shadows. Our brain sees the relief best when the lighting source is from Northwest. Even if the map is inverted. I remember a Nat. Geo. atlas that had the bathymetry inverted (accidentally). The trenches looked like ridges. You could make it flip in your mind but it took some time studying it. You're probably best off generating your own relief from source elevation.

**Comment by edent** [comment]
Thanks! Where can I find the source elevation used for this?

Sorry if that is an obvious question.

**Comment by elliotap** [comment]
@edent you could make a try with some Digital Elevation data from here https://www.usgs.gov/centers/eros/science/usgs-eros-archive-products-overview?qt-science_center_objects=0#qt-science_center_objects
