### ISSUE TITLE
Use either Czechia or Czech Republic

### ISSUE THREAD

**Issue by technetium** [nvkelso/natural-earth-vector#569]
In the provinces-state map the admin label for the country is Czech Republic, in the country map the ADMIN label is Czechia. (I've only checked the 10m versions)

I don't care about the politics of the name, but I don't like the compromise of using a different one for different versions of the maps. Please choose one and use it in both versions.

**Comment by nvkelso** [comment]
Agree. There might be a couple other country name changes to consider, too.

**Comment by nvkelso** [comment]
Czech Republic, Swaziland, Macedonia, Vatican

**Comment by nvkelso** [comment]
Fixed in https://github.com/nvkelso/natural-earth-vector/pull/446/commits/ae0c5993e4d206d50ee30f1fdf56cb7ea8539860.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/446.
