### ISSUE TITLE
Michigan appearing as a blob in ne_10m_admin_1_states_provinces

### ISSUE THREAD

**Issue by mell0kat** [nvkelso/natural-earth-vector#571]
Michigan's borders do not appear to be accurate. Is this because it includes the lakes as part of the state?

<img width="1667" alt="Screen Shot 2021-08-04 at 11 14 14 AM" src="https://user-images.githubusercontent.com/14907923/128213053-893cf803-d825-4a80-bf50-e62032d265ed.png">

**Comment by nvkelso** [comment]
You want the alternate theme download for "without lakes" instead.

**Comment by mell0kat** [comment]
We sure do! Thank you @nvkelso
