### ISSUE TITLE
Update name value for Plattsburgh, NY (10m populated places)

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#572]
quick copy edit fix: feature with NE_ID= 1159125717 needs an "h" appended to the end of its name=* value. WIKIDATAID and NAME_EN are good

https://en.wikipedia.org/wiki/Plattsburgh_(city),_New_York

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/713.
