### ISSUE TITLE
Unable to download Cultural Vectors - Countries

### ISSUE THREAD

**Issue by pyJain108** [nvkelso/natural-earth-vector#574]
When I click on Download Countries, I get an error : 
![image](https://user-images.githubusercontent.com/75158219/130493294-f210b5f0-a5c9-4263-b400-2374ec22cadc.png)

![image](https://user-images.githubusercontent.com/75158219/130493362-69ea9f7c-03d2-4f2f-a7e8-025ddb1cc40e.png)

**Comment by pyJain108** [comment]
Update: The older versions are working, some errors with the latest version 4.1.0.

**Comment by barronh** [comment]
Same issue for physical vector Land (and other). Same solution. I can download 4.0.0 no problem.

**Comment by ImreSamu** [comment]
try : https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_admin_0_countries.zip

( link  adapted from:  https://github.com/nvkelso/natural-earth-vector/issues/528#issuecomment-834070559 )

**Comment by Ataye** [comment]
Just some more info, its the URLs that aren't being built correctly:

**Comment by nvkelso** [comment]
Hmm, I'm hitting the same problem. Debugging. Thanks @ImreSamu for being on top of it.

**Comment by acarapetis** [comment]
@Ataye: While that looks like a broken link, I'm not sure that's really the case - if you "correct" it to http://www.naturalearthdata.com/download/10m/physical/ne_10m_coastline.zip you get a 404. The weird link 
https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_coastline.zip in fact successfully 302 redirects to https://naciscdn.org/naturalearth/10m/physical/ne_10m_coastline.zip. Looks like the real issue right now is that naciscdn.org is down.

**Comment by nvkelso** [comment]
Yeah the weird link is just the WP download manager. Its the upstream server that's having issues. It's DNS recently renewed but several weeks ago so that doesn't seem to be the problem. Still investigating.

**Comment by nvkelso** [comment]
Tracking this with https://github.com/nvkelso/natural-earth-vector/issues/581.
