### ISSUE TITLE
Can't download Natural Earth quick start kit

### ISSUE THREAD

**Issue by megwoodard** [nvkelso/natural-earth-vector#575]
I am trying to download the natural earth quick-start kit and it is currently not working. I have tried on windows and mac and chrome and safari browsers and none of it worked. When I try to click the download for the quick-start kit, the page fails and will not load.

**Comment by ImreSamu** [comment]
try:  https://naturalearth.s3.amazonaws.com/packages/Natural_Earth_quick_start.zip

( link  adapted from:  https://github.com/nvkelso/natural-earth-vector/issues/528#issuecomment-834070559 )

**Comment by megwoodard** [comment]
> try: https://naturalearth.s3.amazonaws.com/packages/Natural_Earth_quick_start.zip
> 
> ( link adapted from: [#528 (comment)](https://github.com/nvkelso/natural-earth-vector/issues/528#issuecomment-834070559) )

Thank you!

**Comment by nvkelso** [comment]
Tracking this with https://github.com/nvkelso/natural-earth-vector/issues/581.
