### ISSUE TITLE
Connection to server error

### ISSUE THREAD

**Issue by dwnadler** [nvkelso/natural-earth-vector#577]
Hi all. Any help would be greatly appreciated.

This code worked one day ago:
lakes110 <- ne_download(scale = 110, type = "lakes",  category = "physical")

Today I get this output:
trying URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/physical/ne_110m_lakes.zip'
Error in utils::download.file(file.path(address), zip_file <- tempfile()) : 
  cannot open URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/physical/ne_110m_lakes.zip'
In addition: Warning message:
In utils::download.file(file.path(address), zip_file <- tempfile()) :
  InternetOpenUrl failed: 'A connection with the server could not be established'

**Comment by wcornwell** [comment]
it also doesn't work from the website, so I think a server somewhere needs to get restarted or something.

**Comment by nvkelso** [comment]
I can reproduce this bug. In the meantime the files are available via
Github in this repo, or now via AWS S3.

**Comment by nvkelso** [comment]
Tracking this with https://github.com/nvkelso/natural-earth-vector/issues/581.
