### ISSUE TITLE
Cannot download naciscdn.org data from naturalearthdata.com

### ISSUE THREAD

**Issue by yoheym** [nvkelso/natural-earth-vector#581]
Hi all. Any help would be greatly appreciated.

When I attempt to download https://naciscdn.org/naturalearth/110m/physical/ne_110m_ocean.zip, , the request times out.

**Comment by nvkelso** [comment]
I’m working to repoint the naciscdn.org domain at the new S3 buckets this weekend.

**Comment by ldekay** [comment]
I assume you're still working on this because I can't get to https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/raster/OB_LR.zip
Responds with This site can’t be reached naciscdn.org took too long to respond.
Any ETA for the repoint???

**Comment by fernsehmuell** [comment]
Hello, are there any news on the naciscdn.org outage?

**Comment by nvkelso** [comment]
The original private server backing naciscdn.org seems to be busted. 

I'm in the process of redirecting to S3. Here are some file resource patterns in the meantime:

Official S3 public data:
http://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_admin_0_countries.zip
(note `10m_cultural` where naturalearthdata.com uses `10m/cultural` with `/` not `_` so you'll need to update more than your domain)

Eventually this will get naciscdn.org pretty domain:
http://naciscdn.org.s3-website-us-west-2.amazonaws.com/naturalearth/10m/cultural/10m_cultural.zip
(same file structure as naturalearthdata.com)

**Comment by dwnadler** [comment]
Is there a way to download a raster file with an AWS link?

**Comment by nvkelso** [comment]
Oops, I missed the rasters the first attempt, thanks for flagging that. Adding the 10m and 50m rasters now.

**Comment by nvkelso** [comment]
@dwnadler The rasters should all be there now.

**Comment by jjakoboski** [comment]
Is this still down?  I currently can't access the server at naciscdn.org.  Thanks  :)

**Comment by raybellwaves** [comment]
FWIW I downloaded data from the S3 URL using geopandas
`gpd.read_file("https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_populated_places.zip")`

**Comment by ldekay** [comment]
I was able to download
https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_bathymetry_all.zip by
going to https://naturalearth.s3.amazonaws.com/ and going through the file
listings until I found 10m_physical/ne_10m_bathymetry_all.zip. Concatenated
the two strings in a link and used that to download. Tedious but effective.
*Lloyd DeKay*

**Comment by DanielJWood** [comment]
If you need to find one of these links and made it this far, here they are in a gist, until the site is restored. Taken from the index at https://naturalearth.s3.amazonaws.com/ 

https://gist.github.com/DanielJWood/b71237cc200831acf8e637c05ce2c375

**Comment by ldekay** [comment]
Daniel,
I wanted to say thank you for your hard work on getting this database back
up and running. It looks like it's been a fairly monumental task so far,
but it's a valuable database that the public needs, nd your efforts are key
to keeping it available to the public. I just wanted to let you know how
much you're appreciated.
Cheers,
*Lloyd DeKay*

**Comment by jjakoboski** [comment]
Downloaded the files successfully - thank you!

**Comment by mccartneypaul** [comment]
Just wanted to say thanks for rehosting it on https://naturalearth.s3.amazonaws.com/
The same url structure worked for me to download the files I needed for cartopy.
Appreciate it!

**Comment by julia-remke** [comment]
Hey! 
First of all thanks for sharing the downloads! I have all of the data saved locally now, but cartopy still wants to download the packages from naciscdn.org. How do I tell the programm to use the local files instead of trying to download?
I tried changing the config with cartopy.config['pre_existing_data_dir']=expanduser('~/cartopy-data') but it still won't work. Might be a stupid question, but help would be appreciated!

Julia

**Comment by SomeoneElseOSM** [comment]
@https://github.com/julia-remke I'm not a cartopy user, but https://github.com/SciTools/cartopy/pull/1833 and https://github.com/SciTools/cartopy/issues/1849 suggests that a new release of cartopy (v0.20.0) should address this.  If you're using that and it still doesn't work, that's probably something to raise at https://github.com/SciTools/cartopy/issues .

**Comment by ttruksa** [comment]
@julia-remke I'm in the same situation. It still seems to be pulling from the non-AWS site and I'm not sure how to change that.

**Comment by mccartneypaul** [comment]
@ttruksa I ended up just downloading them manually and putting them into cartopy's offline data. ...You may also need the cartopy offline data package as well.  Not sure, as I ended up going with folium...
>>> import cartopy.config        
>>> cartopy.config['data_dir']
'/home/pelson/.local/share/cartopy'

**Comment by nvkelso** [comment]
The `https` versions should also now work again, meaning downloads from naturalearthdata.com should be operational again.

**Comment by nvkelso** [comment]
For posterities sake, the nameservers configs were scrambled / not auto generated correctly. Manually setting them to the same 4 values in all the places corrected the problem, and unblocked adding the SSL cert.
