### ISSUE TITLE
Unable to download Natural Earth products

### ISSUE THREAD

**Issue by MINDJE** [nvkelso/natural-earth-vector#582]
Greetings

Briefly, we appreciate your kind sharing of products at free cost. However, we are unable to download these products as we receive the following notice 

( This site can’t be reached
The webpage at https://naciscdn.org/naturalearth/10m/raster/NE2_HR_LC_SR_W_DR.zip might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED)

Please kindly assist us

**Comment by vnovik21** [comment]
Trying to download at Admin 1 level, getting the same error "This site can't be reached"

**Comment by nvkelso** [comment]
This is a dupe of https://github.com/nvkelso/natural-earth-vector/issues/581.
