### ISSUE TITLE
Natural Earth map data are missing

### ISSUE THREAD

**Issue by atmsfer** [nvkelso/natural-earth-vector#583]
The URL for the Natural Earth data is missing. Specifically, I am looking for https://naciscdn.org/naturalearth/10m/physical/ne_10m_land.zip, which is linked from http://www.naturalearthdata.com/downloads/10m-physical-vectors/. This crashes Cartopy maps.

**Comment by atmsfer** [comment]
Repeat of prior issue.

**Comment by nvkelso** [comment]
Duplicate of https://github.com/nvkelso/natural-earth-vector/issues/581.
