### ISSUE TITLE
broken links (1:110m Cultural Vectors - Admin 0 – Countries)

### ISSUE THREAD

**Issue by leomiquelutti** [nvkelso/natural-earth-vector#584]
Dear,

the links under the **Admin 0 – Countries** section, in the [downloads of the 110m cultural vectors](https://www.naturalearthdata.com/downloads/110m-cultural-vectors/) seems to be broken.

Best regards,

**Comment by nvkelso** [comment]
Duplicate of https://github.com/nvkelso/natural-earth-vector/issues/581.
