### ISSUE TITLE
This site can't be reached

### ISSUE THREAD

**Issue by mmapperr** [nvkelso/natural-earth-vector#589]
Hi,

I am trying to download Shaded Relief, but see an error saying THIS SITE CAN'T BE REACHED. 

Can someone help PLEASE....!

Kind Regards

**Comment by almccon** [comment]
See more discussion in #581

**Comment by mmapperr** [comment]
Thanks aloot

**Comment by nvkelso** [comment]
Dupe of https://github.com/nvkelso/natural-earth-vector/issues/581.
