### ISSUE TITLE
wikidata | ne_10m | geography_regions_polys

### ISSUE THREAD

**Issue by ImreSamu** [nvkelso/natural-earth-vector#590]
+49 new wikidata matches.
https://docs.google.com/spreadsheets/d/1dSSBg-jVVjII8ywNJsBapJ27yw0xtz0CNOY4wcssXkA/edit?usp=sharing

* ne_id
* _suggested_wd_id = proposals
* wd_enwiki = english wikipedia page ( if exists )

not critical comment:

I have found different values for the same `ne_id`
I am expecting the same `name`, `label` columns in this case.

```
+------------+--------------------------+---------+--------------------------+------------+------------+
|   ne_id    |           name           | namealt |          label           | wikidataid | featurecla |
+------------+--------------------------+---------+--------------------------+------------+------------+
| 1159103969 | CORD. OCCIDENTAL         |         |                          | Q8463325   | Range/mtn  |
| 1159103969 | CORDILLERA OCCIDENTAL    |         | CORDILLERA OCCIDENTAL    | Q8463325   | Range/mtn  |
```

**Comment by nvkelso** [comment]
@ImreSamu since you're on a roll... there are a couple hundred new rivers and lakes in North America, too, that could use some ❤️ ... I hope to finish processing them today and push them to the same branch as Australia rivers.

**Comment by nvkelso** [comment]
In the case of `CORDILLERA OCCIDENTAL` I remember that South American range has several distinct parts. Probably they should be merged in NE (like we did elsewhere with Med. Sea and few others).
