### ISSUE TITLE
Parks and Protected Lands

### ISSUE THREAD

**Issue by C9Piero** [nvkelso/natural-earth-vector#595]
I can't dowload this file "Parks and Protected Lands"  (160.35 KB) version 4.0.0
Could someone help me? pls

**Comment by nvkelso** [comment]
Dupliate of https://github.com/nvkelso/natural-earth-vector/issues/581.

See https://github.com/nvkelso/natural-earth-vector/issues/581#issuecomment-916250782 for workaround.
