### ISSUE TITLE
Natural Earth Admin 0 Countries File

### ISSUE THREAD

**Issue by autumnpecarovich** [nvkelso/natural-earth-vector#596]
I have tried to access Natural Earth data a few time now over the week but have not been able to successfully download the file. I get a "file cannot be downloaded securely message" every time I select "Save Link as".

**Comment by nvkelso** [comment]
Duplicate of https://github.com/nvkelso/natural-earth-vector/issues/581.

There's a [GIST](https://github.com/nvkelso/natural-earth-vector/issues/581#issuecomment-916250782) showing where to find the files in the meantime.
