### ISSUE TITLE
The downloads on the website do not work !

### ISSUE THREAD

**Issue by EstebanOD** [nvkelso/natural-earth-vector#597]
http://www.naturalearthdata.com/downloads/10m-raster-data/10m-cross-blend-hypso/
All the "Download large size" buttons do not work

**Comment by nvkelso** [comment]
Duplicate of https://github.com/nvkelso/natural-earth-vector/issues/581.

There's a [GIST](https://github.com/nvkelso/natural-earth-vector/issues/581#issuecomment-916250782) showing where to find the files in the meantime.
