### ISSUE TITLE
Cultural Vectors 1:10 m won't download

### ISSUE THREAD

**Issue by sschmunk** [nvkelso/natural-earth-vector#601]
Clicking on the download buttons either yields no results or gives you this error: 
![image](https://user-images.githubusercontent.com/80072065/135480334-fdea417d-a4d0-4483-8a12-95d29d838c35.png)

**Comment by crudarchives** [comment]
Yes--I am having this same issue with all vector files.

**Comment by SomeoneElseOSM** [comment]
See the [gist](https://gist.github.com/DanielJWood/b71237cc200831acf8e637c05ce2c375) on [this comment](https://github.com/nvkelso/natural-earth-vector/issues/581#issuecomment-916250782) that explains where to get files from.

**Comment by crudarchives** [comment]
Thank you!

**Comment by nvkelso** [comment]
This is fixed now, and a dup of #581.
