### ISSUE TITLE
Many of the most recent versions for data are having issues downloading

### ISSUE THREAD

**Issue by crudarchives** [nvkelso/natural-earth-vector#602]
For any of the 4.1 version of the physical files on 1:10m and any of the recent versions of the raster maps, this is what shows up when attempting to download the file:

![Screenshot (23)](https://user-images.githubusercontent.com/91702959/135541190-32035ec4-b581-4624-98c8-e2ae48075a61.png)

A server not found page shows up, despite no other symptoms showing any problems of connectivity. Earlier version files download fine. I am using the earlier version files except for the raster base maps, where no earlier versions are available.

Thank you for your time.

**Comment by Kaputmaher** [comment]
<img width="983" alt="Снимок экрана 2021-10-02 в 12 00 00" src="https://user-images.githubusercontent.com/12089056/135710885-7956cda1-3055-44c5-8fbc-6a9fea9a4f94.png">

**Comment by ImreSamu** [comment]
See the [gist](https://gist.github.com/DanielJWood/b71237cc200831acf8e637c05ce2c375)
( context:   [this comment](https://github.com/nvkelso/natural-earth-vector/issues/581#issuecomment-916250782)  )

**Comment by nvkelso** [comment]
This is fixed now, and a dup of #581.
