### ISSUE TITLE
Download Large Data button not working

### ISSUE THREAD

**Issue by Underhttp** [nvkelso/natural-earth-vector#603]
Whenever i try to download the large dataset for natural earth 1:10m it gives me a DNS error, I restarted my router and all my other online applications are working without a problem. Thought I might submit a bug report just in case.

**Comment by ImreSamu** [comment]
Thanks for posting this issue! It's a valid concern, and we're already tracking it in a previous issue, #581 

Temporary you can use this   [gist](https://gist.github.com/DanielJWood/b71237cc200831acf8e637c05ce2c375)  file (   [mentioning in this comment](https://github.com/nvkelso/natural-earth-vector/issues/581#issuecomment-916250782)  )  for the correct download links.

**Comment by nvkelso** [comment]
This is fixed now, and a dup of #581.
