### ISSUE TITLE
Download raster data

### ISSUE THREAD

**Issue by kmithof** [nvkelso/natural-earth-vector#604]
Dear Sir, I am not able to download 1:10m / 50m Raster Data. message: The page  is not avialable.

**Comment by ImreSamu** [comment]
Hi @kmithof

Thanks for posting this issue! It's a valid concern, and we're already tracking it in a previous issue, #581 

Temporary you can use this   [gist](https://gist.github.com/DanielJWood/b71237cc200831acf8e637c05ce2c375)  file (   [mentioning in this comment](https://github.com/nvkelso/natural-earth-vector/issues/581#issuecomment-916250782)  )  for the correct download links.

Just search for "10m_raster/"  + zip file name

**Comment by nvkelso** [comment]
This is fixed now, and a dup of #581.
