### ISSUE TITLE
Donbas is a misleading name for disputed area in Eastern Ukraine

### ISSUE THREAD

**Issue by seriar** [nvkelso/natural-earth-vector#625]
1. Donbas region is a bigger historical, cultural, and/or economic entity than the area marked as "Donbas" in the dataset
2. Furthermore, neither Ukraine, nor Russia, nor even breakaway republics define the marked area as Donbas (i guess it is fair to say that all parties agree that those territories are part of Donbas, but not entire Donbas)

* The international documents (e.g. ones of OSCE) usually define it as "separate territories of Donetsk and Luhansk regions" or "non-government-controlled areas of Donetsk and Luhansk regions"
* Ukrainian government additionally uses "temporarily occupied territories of Donetsk and Luhansk Oblasts"
* The leaders of the breakaway entities themselves use "Donetsk People Republic" and "Luhansk People Republic"
* In the media "Breakaway republics in Eastern Ukraine", "territories controlled by separatists" are used

Although all the abovementioned options are much more verbose, "Donbas" in my option is an inaccurate tag to be used for that area. Something like the "non-government-controlled parts of Donbas" would be more accurate in my opinion.

**Comment by nvkelso** [comment]
I have made the **formal name** of the disputed area to `non-government-controlled areas of Donetsk and Luhansk regions` via 3aa16bdc7acfa611d5196d5aa0ba10d51db762bb but kept the short name short (single word brevity) as `Donbas`.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/579.
