### ISSUE TITLE
China,Bangladesh,Brasil Coastline

### ISSUE THREAD

**Issue by martinpflaum** [nvkelso/natural-earth-vector#626]
Hi, i really like this project :). I was putting the map on a sphere with some images from NASA visible earth (link https://visibleearth.nasa.gov/collection/1484/blue-marble?page=2 ). It really worked perfectly with all borders matching 1 to 1 to the coastline. But in 3 cases the border wasn't matching with the coastline. The images are from 1994. So maybe the reason is that the sea level shifted and the borders are perfectly fine. It also could be that i made a mistake somewhere. Anyway here are the images of the earth with the borders:

China coastline:
![something](https://user-images.githubusercontent.com/63510484/140642071-14d9b0d9-11dc-49bb-aa40-a98546ac9961.png)

Brasil (or above) coastline:
![something_brasil](https://user-images.githubusercontent.com/63510484/140642420-f1b5f59a-0e70-4750-a5b3-05a4167b2521.png)

Bangladesh coastline:
![something_bangladesh](https://user-images.githubusercontent.com/63510484/140642455-390f1211-05be-4f2f-9620-cea772338c8d.png)

**Comment by nvkelso** [comment]
These all look like sediment coming out of large river systems into the ocean.
