### ISSUE TITLE
Missing lake

### ISSUE THREAD

**Issue by LorenzK88** [nvkelso/natural-earth-vector#630]
Hi, 
I don't know if I'm doing something wrong but it seems that Lake Como (Italy) is missing from the data provided.

thanks for your time,
Lorenzo

**Comment by nvkelso** [comment]
**Lake Como** in Italy is included in the default 10m lakes theme, pictured below.

_(It is not included in the 10m Europe supplemental, or 50m lakes, or 110m lakes themes.)_

![image](https://user-images.githubusercontent.com/853051/141934523-20597f32-6819-4562-b8e6-fc66a08a1096.png)

**Comment by LorenzK88** [comment]
Hi,
thanks for your reply. Lake Como is the one highlighted in green.
Is there a way to add it somehow?


[image: unnamed.png]

**Comment by LorenzK88** [comment]
![unnamed](https://user-images.githubusercontent.com/94395834/142006623-6b834dae-4cc1-42e7-9329-31e7ac964f44.png)

**Comment by nvkelso** [comment]
It's already there, the entire map is Natural Earth data.
