### ISSUE TITLE
Rename Puerto Cabezas to Bilwi

### ISSUE THREAD

**Issue by pinakographos** [nvkelso/natural-earth-vector#633]
Puerto Cabezas (NE ID: 1159146421) in the 10m populated places shapefile could be renamed to Bilwi. The latter name seems to be coming into more common usage, as it is the local Miskito name for what is commonly described as their "capital" (it's an ADM1 capital in Nicaragua). Importantly, Bilwi is the official name approved for use by the US federal government, with Puerto Cabezas listed as a variant. OSM has adopted Bilwi, though Google seems to presently use Puerto Cabezas.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/713.
