### ISSUE TITLE
Download doesn't work

### ISSUE THREAD

**Issue by pesch** [nvkelso/natural-earth-vector#641]
Hello,
when I try to Download the Raster: Natural Earth I with Shaded Relief, Water, and Drainages it doen't work and only a XML Site shows up:
https://www.naturalearthdata.com/downloads/10m-raster-data/10m-natural-earth-1/
https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/raster/NE1_HR_LC_SR_W_DR.zip

Can you please fix it.

Thank you

Greetings

Peter

**Comment by nvkelso** [comment]
I can replicate the problem. I'll work on solution.

**Comment by nvkelso** [comment]
Should be fixed now.
