### ISSUE TITLE
Shape file problem with Mapbox Studio

### ISSUE THREAD

**Issue by Schnaer** [nvkelso/natural-earth-vector#647]
Hi. Im new to mapmaking and am trying to figure out how to use data from Natural Earth in Mapbox Studio. When I try to import data I get the error: zip file did not contain shp file.  I was trying to use Cross Blended Hypso with Shaded Relief. Where can I find a shapefile for this Raster data? Im sorry if this question is doesnt belong here. Like I said: Im new to this. 
Thank you for all your efforts and contributions.

**Comment by nvkelso** [comment]
The theme in question is not available as a vector shapefile, only as raster.

You would need to tile it, either using their tiling service or gdal.
