### ISSUE TITLE
South Sudan three letters code is SDS and not SSD

### ISSUE THREAD

**Issue by mikima** [nvkelso/natural-earth-vector#656]
the `SOV_A3` field for South Sudan and its boundaries is "SDS", but according to [ISO standards](https://www.iso.org/obp/ui/#iso:code:3166:SS) should be "SSD"

**Comment by nvkelso** [comment]
Look in iso_a3 instead? Natural Earth has its own a3 codes as ISO isn’t comprehensive.

**Comment by mikima** [comment]
ow, my bad, thank you.
