### ISSUE TITLE
Disputed boundaries: FEATURECLA field

### ISSUE THREAD

**Issue by mikima** [nvkelso/natural-earth-vector#664]
Are there definition of the FEATURECLA values?
I see ~~five~~ [edit: eight] unique values:
* "Indefinite (please verify)"
* "International boundary (verify)"
* "Disputed (please verify)"
* "Line of control (please verify)"
* "Lease limit"
* "Unrecognized"
* "Indeterminant frontier"
* "Overlay limit"

I think "international boundary" and "disputed" are quite clear, but not the other ones. I looked for documentation but with no luck. Sorry if i missed it.

**Comment by nvkelso** [comment]
There used to be documentation in a forum posting for those, but the forum is no longer active.

- "Indefinite (please verify)" - Not disputed, but the two countries on either side of their border haven't officially settled where their border is marked on the ground.
- "International boundary (verify)" - Not disputed, and it's demarcated on the ground.
- "Disputed (please verify)" - The two countries don't agree on their boundary, and sometimes other countries don't agree either.
- "Line of control (please verify)" - More of a military line in an active or "frozen" war zone.
- "Lease limit" - Sometimes countries will lease their territory to another country for some number of years, and temporarily give up administration there (the country leasing it will run the gov't, courts, police, which currency is used) 
- "Unrecognized" - The majority of countries don't recognize this boundary, it should be treating with extreme caution.
- "Indeterminant frontier" - Either you or the source data has this misspelled? There are only a couple of these, they're fun to read about on your own ;)
- "Overlay limit" - For UN policing zones where the sovereignty isn't in question, but day to day administration is handled by the UN or other international body.

**Comment by mikima** [comment]
Hi thank you for the detailed answer!

I checked again in "[ne_10m_admin_0_boundary_lines_land.geojson](https://github.com/nvkelso/natural-earth-vector/blob/master/geojson/ne_10m_admin_0_boundary_lines_land.geojson)" and "Indeterminant frontier" is misspelled in the data source. It is not present in the 50m version (just five values are present). I don't know if it's presente in the other version (shapefiles) of it.

**Comment by nvkelso** [comment]
Oddly there are multiple ways to spell Indeterminant, 🤷 .
