### ISSUE TITLE
Marine areas: Seto Inland Sea (Japan) labeled as Scottish Inner Seas

### ISSUE THREAD

**Issue by pbregener** [nvkelso/natural-earth-vector#665]
The [Seto Inland Sea](https://www.wikidata.org/wiki/Q231312) (Q231312) is labeled incorrectly as [Inner Seas off the West Coast of Scotland](https://www.wikidata.org/wiki/Q5762423) (Q5762423):
![image](https://user-images.githubusercontent.com/6407709/148535545-486c0ae7-a9fd-4957-85ad-3fe6b2caa126.png)

**Comment by nvkelso** [comment]
Whoops, good catch!

Let's also look at `Korea Straight` which is in your screenshot but without a clear polygon associated with it.

**Comment by nvkelso** [comment]
cc @mits003 and @Kanahiro who participated in discussion in #703.

Related work in https://github.com/nvkelso/natural-earth-vector/issues/697 which tracks both missing gulf between Iceland and Greenland, and proposal for grouping marine areas into ocean basins.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/713.
