### ISSUE TITLE
 Does the version 4.0.0 of Urban Area data represent the actual urban area in 2018 or in 2002-2003?

### ISSUE THREAD

**Issue by jiangyangxiaozhu** [nvkelso/natural-earth-vector#669]
It is noticed that the newest version of the Urban Area is 4.0.0, which was updated in 2018. But the describtion of this data says it was derived from 2002-2003 MODIS data. Therefore, I am not sure if the version 4.0.0 of Urban Area data represents the actual urban area in 2018 or in 2002-2003. 
Could you help me clarify this question? I think this is very important for the rational application of this data to scientific research.

**Comment by nvkelso** [comment]
2002-3

But if this representation is optimized for visual display not quantitative analysis. Use the original rasters for that.

**Comment by jiangyangxiaozhu** [comment]
> 

Thank you!

**Comment by jiangyangxiaozhu** [comment]
> 2002-3 But if this representation is optimized for visual display not quantitative analysis. Use the original rasters for that.
> […](#)
> On Jan 10, 2022, at 06:49, jiangyangxiaozhu ***@***.***> wrote: ﻿ It is noticed that the newest version of the Urban Area is 4.0.0, which was updated in 2018. But the describtion of this data says it was derived from 2002-2003 MODIS data. Therefore, I am not sure if the version 4.0.0 of Urban Area data represents the actual urban area in 2018 or in 2002-2003. Could you help me clarify this question? I think this is very important for the rational application of this data to scientific research. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

Thank you!
