### ISSUE TITLE
Mercator Projection for Natural Earth II?

### ISSUE THREAD

**Issue by iSyriux2** [nvkelso/natural-earth-vector#671]
Where can I find the Mercator Projection version of Natural Earth 2? I came across the map on a YouTube video and I've been asking around for months to no avail.
![image](https://user-images.githubusercontent.com/62969957/149654141-89192064-5254-497b-aa53-2fb575c6415f.png)
![image](https://user-images.githubusercontent.com/62969957/149654250-756f2577-6604-4247-ae9b-c9b412eea691.png)
Also, I would like the water body and river data as well in mercator projection, preferably with the Aral Sea at its original size.

**Comment by nvkelso** [comment]
Please use a software package like QGIS or GDAL to reproject the data. It is only available as WGS84 "geographic" projection here.
