### ISSUE TITLE
Cyprus belongs to Europe, not Asia

### ISSUE THREAD

**Issue by raspberryjoy** [nvkelso/natural-earth-vector#673]
For "SOVEREIGNT": "Cyprus", 
I think that the following item should be updated
 
"REGION_UN": "Asia",
 
to this one   
"REGION_UN": "Europe",

As of 2004 Cyprus belongs to EU [countries](https://european-union.europa.eu/principles-countries-history/country-profiles/cyprus_en)
Maybe it would be better to update this value, so that if one wants to load map  of Europe, Cyprus will also be listed.

Thanks

**Comment by nvkelso** [comment]
The United Nations considers Cyprus part of Asia, and that's what Natural Earth is following. These are more physical geography regions than cultural regions.

See also:

- https://unstats.un.org/unsd/methodology/m49/
