### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by ajmas** [nvkelso/natural-earth-vector#685]
The web site is returning 404 for the content sections.

For example, for https://www.naturalearthdata.com/downloads/

<img width="1015" alt="Screenshot 2022-02-24 at 23 50 37" src="https://user-images.githubusercontent.com/682269/155655777-c0daf673-a05c-431c-aa34-6bddeff15f4a.png">

**Comment by nvkelso** [comment]
Thanks for the report. This is partially resolved, I'll update when fully resolved.
