### ISSUE TITLE
French Guyana is missing from South America (re-opened)

### ISSUE THREAD

**Issue by SietzeN** [nvkelso/natural-earth-vector#694]
Hi @nvkelso,

I'm opening a new issue because I cannot re-open this one: https://github.com/nvkelso/natural-earth-vector/issues/677

[](https://user-images.githubusercontent.com/29064687/157458975-ace5e2ab-bc53-44a2-9c10-3fd168202894.png)You're right that French Guyana is politically part of France, but it is still located on the South American continent. Currently, selecting data for South America leaves a hole for French Guyana. I don't think this is desirable (see screenshot below, R code below).

![afbeelding](https://user-images.githubusercontent.com/29064687/157461638-26c67422-2e4e-420f-99f8-7f5d91d080c1.png)

sa <- rnaturalearth::ne_countries(continent = "South America", returnclass = "sf", scale = 110)
tmap::tm_shape(sa) + tmap::tm_polygons()

**Comment by nvkelso** [comment]
If you look in map units it should have the continent you are looking for.
