### ISSUE TITLE
Natural Earth India Boundary

### ISSUE THREAD

**Issue by Sakshimittal95** [nvkelso/natural-earth-vector#702]
Please rectify the Border of Jammu and Kashmir state in all your database. In newer version, you have shown the state in pakistan which is a blunder. Jammu and Kashmir is an integral part of India. The state is a part of India only. Please rectify the error asap.

**Comment by nvkelso** [comment]
Hello @Sakshimittal95, thanks for your feedback. Natural Earth shows the default alignment along the "line of control" between the two countries. But a download for the India point-of-view is available in https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries_ind.zip, or you can compose it using the fclass_in properties in the boundaries themes.

**Comment by KalamkarVA** [comment]
nvkelso, 
Line of control is not the boundary of the country.
You have closed the issue without resolving it.
