### ISSUE TITLE
Missing tagged release for `v5.0.1`

### ISSUE THREAD

**Issue by hummeltech** [nvkelso/natural-earth-vector#704]
The new version seems to have been released about two weeks ago but a tagged release has not yet been created.
https://github.com/nvkelso/natural-earth-vector/blob/917cf06793b6afd50a1fcc0cb07c017c5d57241e/CHANGELOG#L1

**Comment by nvkelso** [comment]
Doh! Thanks for noting. Fixed in https://github.com/nvkelso/natural-earth-vector/releases/tag/v5.0.1.

**Comment by hummeltech** [comment]
Thanks for the quick fix!
