### ISSUE TITLE
ne_10m_land_ocean_label_points without names

### ISSUE THREAD

**Issue by dieterdreist** [nvkelso/natural-earth-vector#706]
Is is intentional that there are no names in the 10m land ocean label points? I only see 3 fields and the Geometry: 
  ```
featurecla (String)
  scalerank (Integer64)
  min_zoom (Real)


```
referring to this file:
https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_land_ocean_label_points.zip

**Comment by nvkelso** [comment]
If you are looking for physical geography labels, look in the other themes: 

- https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-physical-labels/

The file you reference instead establishes which features are water and which are land, and their relative importance to each other (scalerank and min_zoom).
