### ISSUE TITLE
ne_10m_geography_marine_polys: Luzon Strait = sliver polygon

### ISSUE THREAD

**Issue by MLWorley** [nvkelso/natural-earth-vector#726]
In ne_10m_geography_marine_polys, the Luzon Strait region appears as a sliver polygon (almost a straight line rather than a polygon, at least visually). In the screenshot in this post, the Luzon Strait is selected and its "endpoints" are shown marked by red X's.

The fix would probably involve adjusting both it and the Philippine Sea polygon, similar to the earlier fix for the Korea Strait and the Sea of Japan (thank you for that one).

<img width="1127" alt="Screen Shot 2022-05-17 at 08 11 19" src="https://user-images.githubusercontent.com/97397103/168808237-cdc693eb-b5f7-4e10-85c9-ebd9920228c1.png">

**Comment by nvkelso** [comment]
Let's consolidate into https://github.com/nvkelso/natural-earth-vector/issues/735 as it's all the same big fix.
