### ISSUE TITLE
ne_10m_geography_marine_polys: Bab el Mandeb distortion

### ISSUE THREAD

**Issue by MLWorley** [nvkelso/natural-earth-vector#727]
In ne_10m_geography_marine_polys, the Bab el Mandeb region appears distorted - shows up as a series of lumps on either side of the Red Sea near where the Red Sea currently joins the Gulf of Aden, rather than as a region connecting the two. In the screenshot in this post, the Bab el Mandeb is selected and shows up in yellow, although it's a little hard to spot.

<img width="1066" alt="Screen Shot of Bab-el-Mandeb" src="https://user-images.githubusercontent.com/97397103/168810187-915b870b-5226-414f-bbab-0a5f5a7ad49c.png">

**Comment by nvkelso** [comment]
Let's consolidate into https://github.com/nvkelso/natural-earth-vector/issues/735 as it's all the same big fix.
