### ISSUE TITLE
ne_10m_geography_marine_polys: Karskiye Strait distortion

### ISSUE THREAD

**Issue by MLWorley** [nvkelso/natural-earth-vector#728]
In ne_10m_geography_marine_polys, the Karskiye Strait region appears distorted - shows up as a series of lumps on either side of the area where the Barents Sea currently joins the Kara Sea, rather than as a region connecting the two. In the screenshot in this post, the Karskiye Strait is selected and shows up in yellow.

<img width="1219" alt="Kara Strait" src="https://user-images.githubusercontent.com/97397103/168811511-11559913-b8cc-4041-b1a5-64045e27bb2c.png">

Possibly it has more or less the right boundary points but not quite in the right order?

**Comment by nvkelso** [comment]
Let's consolidate into https://github.com/nvkelso/natural-earth-vector/issues/735 as it's all the same big fix.
