### ISSUE TITLE
ne_10m_geography_marine_polys: La Pérouse Strait distortion

### ISSUE THREAD

**Issue by MLWorley** [nvkelso/natural-earth-vector#729]
First, thanks for updating the Korea Strait / Sea of Japan recently; it's a big improvement.

Looking at where the La Pérouse Strait joins the Sea of Japan and the Sea of Okhotsk, though - it seems to have its own issue, and appears as a series of lumps on either side of where I think the strait ought to be joining the other two bodies of water, as though the boundary points for the strait aren't quite in the right order. The strait polygon is shown in yellow in the associated picture.

<img width="1134" alt="La Perouse Strait" src="https://user-images.githubusercontent.com/97397103/168813923-857fb3ae-5b81-4123-9e69-2231fe6b7760.png">

**Comment by nvkelso** [comment]
Let's consolidate into https://github.com/nvkelso/natural-earth-vector/issues/735 as it's all the same big fix.
