### ISSUE TITLE
ne_10m_geography_marine_polys: Strait of Gibraltar distortion

### ISSUE THREAD

**Issue by MLWorley** [nvkelso/natural-earth-vector#730]
Instead of the Strait of Gibraltar joining the North Atlantic Ocean and the Alboran Sea at the western end of the Mediterranean, the Strait seems to be a series of lumps on either side of where the two regions currently join directly.

<img width="1195" alt="Strait of Gibraltar" src="https://user-images.githubusercontent.com/97397103/168815262-54de6a36-fe7a-434a-8977-e975ce07c570.png">

This and some of the other straits (e.g. Bab el Mandeb, Kara Strait) seem to have similar-looking issues.

**Comment by nvkelso** [comment]
Let's consolidate into https://github.com/nvkelso/natural-earth-vector/issues/735 as it's all the same big fix.
