### ISSUE TITLE
ne_10m_geography_marine_polys: Drake Passage distortion

### ISSUE THREAD

**Issue by MLWorley** [nvkelso/natural-earth-vector#731]
Something odd seems to be going on with the Drake Passage in ne_10m_geography_marine_polys; if it's selected, it's very hard to spot, and there seems to be some kind of distortion about it.

In the associated screen shot, the Drake Passage has been selected and some of its points are showing up marked by red X's.

<img width="1220" alt="Screen Shot Drake Passage" src="https://user-images.githubusercontent.com/97397103/168817559-a91d4e59-2710-4bf1-b919-4c2c66c06e66.png">

My impression is that the Drake Passage should be showing up as a region over an area that currently is being covered by the Southern Ocean etc in that area.

**Comment by nvkelso** [comment]
Let's consolidate into https://github.com/nvkelso/natural-earth-vector/issues/735 as it's all the same big fix.
