### ISSUE TITLE
ne_10m_geography_marine_polys: Yucatan Channel distortion

### ISSUE THREAD

**Issue by MLWorley** [nvkelso/natural-earth-vector#732]
Where the Yucatan Channel appears, it isn't appearing as a region joining the Yucatan basin of the Caribbean with the Gulf of Mexico; instead, it's appearing as a couple of clusters of vertices on either side of that area. (The one on the west side appears as a visible yellow polygon when selected, but only near the shore; the one on the east side isn't easily visible when selected that way.)

Screen shots:

<img width="663" alt="Yucatan Channel - red points" src="https://user-images.githubusercontent.com/97397103/168820067-3513e319-3124-43e2-968a-e74852bd65ee.png">

<img width="1019" alt="Screen Shot 2022-05-17 at 09 17 01" src="https://user-images.githubusercontent.com/97397103/168820292-2ad82b75-6da4-456b-a836-808811935764.png">

**Comment by nvkelso** [comment]
Let's consolidate into https://github.com/nvkelso/natural-earth-vector/issues/735 as it's all the same big fix.
