### ISSUE TITLE
website: broken link to ne_10m_admin_0_antarctic_claims.zip

### ISSUE THREAD

**Issue by Writ3r** [nvkelso/natural-earth-vector#753]
Off of the page: 
https://www.naturalearthdata.com/downloads/10m-cultural-vectors/

If you go to
Admin 0 – Breakaway, Disputed Areas  -> Download Antarctic claims

Click the button to download the data.

It redirects to the url: https://naciscdn.org/naturalearth//10m/cultural/ne_10m_admin_0_antarctic_claims.zip

Which is invalid, routing to an 'Access Denied' error page.
Removing the extra slash allows for downloading the data.

**Comment by nvkelso** [comment]
Fixed, thanks for the detailed report!
