### ISSUE TITLE
Countries point-of-views files naming

### ISSUE THREAD

**Issue by slaperche-zenly** [nvkelso/natural-earth-vector#780]
Seems like most of the files are named with the patter `admin_0_countries_<abc>` where `<abc>` is the ISO 3166-1 alpha-3 country code.
This is always true, except for:
- `admin_0_countries_bdg` (should be `admin_0_countries_bgd`)
- `admin_0_countries_nep` (should be `admin_0_countries_npl`)

I suppose it's a mistake and it could be fixed.

**Comment by nvkelso** [comment]
Hey @slaperche-zenly, the A3 codes used in Natural Earth are only semi-compatible with ISO, as ISO has a smaller set of A3 codes for a smaller set of countries than Natural Earth maintains. The POV files are named using the Natural Earth A3 code not the ISO codes.
