### ISSUE TITLE
Arunachal Pradesh incorrectly represented in China POV dataset

### ISSUE THREAD

**Issue by slaperche-zenly** [nvkelso/natural-earth-vector#800]
A part of Arunachal Pradesh is disputed between India and China, thus one would expect to see the disputed part as belonging to China in the China POV (`ne_10m_admin_0_countries_chn`), but this is not the case (it's shown as belonging to India)

<img width="600" alt="Screenshot 2022-08-23 at 16 38 40" src="https://user-images.githubusercontent.com/77592810/186188775-0ebb8f9b-59d3-4332-85e9-4bf91f18b849.png">

The disputed shape is correctly referenced in `ne_50m_admin_0_boundary_lines_disputed_areas` but seems missing from`ne_10m_admin_0_boundary_lines_disputed_areas`.

Could this be the root cause?

**Comment by almccon** [comment]
The place where you've marked a red X is in Assam, not Arunachal Pradesh. I'm not an expert in this area, but it looks like the borders in your screenshot are correct from the China POV.

**Comment by slaperche-zenly** [comment]
Yeah, the red X was just placed roughly to indicate the general area, it wasn't meant to be accurate.

That being said, you're totally right!
Arunachal Pradesh is just north of the red X, and is shown as part of China in the China POV, so no issue here.
I probably got confused with another layer I had loaded in QGIS.
