### ISSUE TITLE
Some of Boston Logan Airport is in the water

### ISSUE THREAD

**Issue by baseleg** [nvkelso/natural-earth-vector#815]
Hi,

I'm using the [Natural Earth 1:10m Cultural Vectors, Admin Countries ](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/) as a base map to plot worldwide airports on.  The issue I'm running into is that Logan Airport in Boston, MA has some of its property/runways extending outside the Natural Earth polygon, i.e. in the water.  Is there a way to put in a request to have some points moved/added so that the airport is fully on land?  Although we could add/move points ourselves, our preference is to use the Natural Earth maps as-is.  Please see image below of the polygon overlaid on a reference map.  

Thanks and Regards.

![image](https://user-images.githubusercontent.com/11303102/194343554-97511c45-df95-4b62-969f-6a839ea747ea.png)

**Comment by nvkelso** [comment]
Hey @baseleg. Natural Earth isn't meant to be used at such overzoomed scales. The screenshot you include is approximately at zoom 13, while Natural Earth's 1:10M scale is approximately zoom 6. We recommend pairing Natural Earth with another open data project like OpenStreetMap at those high zooms.

That said, Tom is working on updating the coastlines and that work will be available in ~ late 2023. See more: http://shadedrelief.com/ne-draft/.
