### ISSUE TITLE
Error 404 when using Coordinate Cleaner in R 

### ISSUE THREAD

**Issue by ArchaeoAmos** [nvkelso/natural-earth-vector#834]
When attempting to use CoordinateCleaner, there is an issue with the link to Natural Earth Data when running cc_sea causing the clean to fail. 
When I click the link in my browser it gives a 404 error.

**Comment by ImreSamu** [comment]
Hi @ArchaeoAmos

The https://github.com/ropensci/CoordinateCleaner repo is probably more ideal and better able to help you. 
And I see that others are having similar problems and have workarounds.
https://github.com/ropensci/CoordinateCleaner/issues?q=is%3Aissue+cc_sea 
* https://github.com/ropensci/CoordinateCleaner/issues/77
* https://github.com/ropensci/CoordinateCleaner/issues/69

**Comment by ArchaeoAmos** [comment]
Thanks so much, this solved my issues!
