### ISSUE TITLE
ne_50m_admin_1_states_provinces missing a lot of data

### ISSUE THREAD

**Issue by lincomatic** [nvkelso/natural-earth-vector#847]
I downloaded ne_50m_admin_1_states_provinces and found that it is missing a lot of regions that are fully described in ne_10m_admin_1_states_provinces. For instance, all of Mexico and most of Europe are missing from the 50m file, but are present in the 10m file

**Comment by nvkelso** [comment]
See response in https://github.com/nvkelso/natural-earth-vector/issues/738.
