### ISSUE TITLE
admin 1 for 110m is only us?

### ISSUE THREAD

**Issue by justinelliotmeyers** [nvkelso/natural-earth-vector#877]
should this download be global or is the output expected to be us only?

https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_1_states_provinces.zip

![image](https://github.com/nvkelso/natural-earth-vector/assets/5324316/dff2ca90-a0b8-4ca0-bab8-cfb653581f2c)

![QUESTION110](https://github.com/nvkelso/natural-earth-vector/assets/5324316/95bfbcaf-a0aa-4449-97bc-693e6b66cb77)

**Comment by nvkelso** [comment]
The output is expected to be USA only right now. I'll leave the issue open for revisiting that in v6.

In version 5 via https://github.com/nvkelso/natural-earth-vector/issues/479 we added a handful more countries at admin-1 level in the 1:50m scaleset. 

So I can see adding those, or a subset of those, to version 6 – namely:

- US (already included)
- Canada
- Brazil
- India
- Indonesia
- China
- Russia
- Australia
- South Africa

**Comment by justinelliotmeyers** [comment]
Thanks for letting me know. The admin 2 clearly calls that out - the admin 1 doesnt say anything so I was confused. 

Have a good week!
