### ISSUE TITLE
Not passing the linter?

### ISSUE THREAD

**Issue by kissu** [nvkelso/natural-earth-vector#885]
I've downloaded a geoJSON from here: https://github.com/nvkelso/natural-earth-vector/blob/master/geojson/ne_110m_admin_0_countries.geojson?short_path=1e6ab74

And since I'm new to geoJSONs, I read the [Wikipedia page](https://en.wikipedia.org/wiki/GeoJSON#External_links) of it. Saw that there is [a linter](https://geojsonlint.com/) and that this project's files do not pass it apparently regarding the right-hand rule.

![CleanShot 2023-12-22 at 00 10 51@2x](https://github.com/nvkelso/natural-earth-vector/assets/5133074/dbdc3fa4-3231-4735-bf20-d32548ace085)

I then saw this answer suggesting that there are [2 different specs](https://gis.stackexchange.com/a/259957/163255). I am hence curious as to why we're using the old one and not following the guidelines of the [2016's one](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.6).

[This package](https://github.com/mapbox/geojson-rewind#geojson-rewind) works well and indeed solves that issue and explains that the benefit of a valid geoJSON is
> This helps you generate compliant Polygon and MultiPolygon geometries. Furthermore, it lets you use [Canvas](http://www.bit-101.com/blog/?p=3702) and other drawing libraries' default behavior to color the interior rings of Polygon and MultiPolygon features.

Since I'm not an expert on the topic I was wondering if it was for wider compatibility or something alike? 😄 

---
Update: is it because of [some tools using the opposite convention](https://github.com/tyrasd/rfc7946-to-d3#why)?

**Comment by nvkelso** [comment]
Good question! My guess is there's a new setting in GDAL's org2org command to create spec v2 compliant GeoJSON? Ideally it's a config change in our existing tool chain rather than adding new software.

This can be part of the version 6 release. 

Until then please use the workaround you documented.

**Comment by kissu** [comment]
That would indeed be good to make the change during the generation. 🤗 
I'll use the workaround as expected yes. 😉 
Was mainly curious if that was deliberate (for some specific reasons) or just an oversight.

Also, do you have a public v6 project/branch or anything so that I could track the progress? 😺

**Comment by kissu** [comment]
We should probably also remove the `crs member` since it's being the default anyway, as mentioned here: https://macwright.com/2016/11/07/the-geojson-ietf-standard#the-crs-member-was-removed
