### ISSUE TITLE
Time zones for Russia

### ISSUE THREAD

**Issue by romanovgleb** [nvkelso/natural-earth-vector#888]
Hey there! Thanks for a dataset - it's very helpful.

However, there's a mistake in at least one place: the polygon containing Moscow displays its Timezone to be UTC+4 instead of UTC+3 which it should be

Would appreciate the correction. Thanks!

**Comment by hpvd** [comment]
possibly related to:
https://github.com/nvkelso/natural-earth-vector/issues/864

**Comment by nvkelso** [comment]
Duplicate of #864, closing (thanks @hpvd)
